_ONE_DAY = 1000 * 3600 * 24
_ONE_WEEK = _ONE_DAY * 7
_ONE_MONTH = _ONE_DAY * 30

JOB_TABLES_TTL = _ONE_WEEK
JOB_TABLES_AUTO_COMPACTION_PERIOD = _ONE_DAY

OPERATION_TABLES_TTL = _ONE_MONTH
OPERATION_TABLES_AUTO_COMPACTION_PERIOD = _ONE_WEEK

IS_OPENSOURCE = True
