{{- if not .Values.unmanagedSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include ".fullname" . }}
  labels:
    {{- include ".labels" . | nindent 4 }}
data:
  YT_TOKEN: {{ .Values.yt.token | b64enc | quote }}
{{- end }}
