# flake8: noqa
from yt_dashboard_generator.dashboard import Dashboard
from yt_dashboard_generator.specific_tags.tags import TemplateTag

from yt_dashboard_generator.backends.grafana import GrafanaTextboxDashboardParameter
from yt_dashboard_generator.backends.monitoring import MonitoringTag, MonitoringLabelDashboardParameter

from .user_load import build_max_lookup_select_execute_time_per_host, build_user_load
from .lsm import build_user_lsm
from .cpu import build_user_thread_cpu, build_total_cpu
from .maintenance import build_user_hydra, build_tablet_balancer, build_bundle_controller
from .memory import build_user_memory, build_reserved_memory
from .network import (
    build_tablet_network,
    build_user_network,
    build_throttling,
    build_rpc_request_rate,
    build_lookup_select_ack_time,
    build_rpc_message_size_stats_per_host,
)
from .disk import build_user_disk, build_user_background_disk, build_user_caches, build_block_cache_planning
from .efficiency import build_efficiency_rowset
from .resources import build_user_resource_overview_rowset, build_disk_statistics_rowsets
from .proxy_resources import build_rpc_proxy_resource_overview_rowset
from .proxy_details import (
    build_rpc_proxy_cpu,
    build_rpc_proxy_network,
    build_rpc_proxy_rpc_request_rate,
    build_rpc_proxy_rpc_request_wait,
    build_rpc_proxy_maintenance,
)
from .planning import (
    build_node_resource_capacity_planning,
    build_rpc_proxy_resource_capacity_planning,
    build_tablet_static_planning,
)

from ..key_filter import build_key_filter_rowset
from .key_filter import build_bundle_key_filter_rowset

from ..common.sensors import *


try:
    from ..constants import (
        BUNDLE_UI_DASHBOARD_DEFAULT_CLUSTER,
        BUNDLE_UI_DASHBOARD_DEFAULT_TABLET_CELL_BUNDLE,
        BUNDLE_UI_DASHBOARD_DEFAULT_PROXY_ROLE,
    )
except ImportError:
    from ..yandex_constants import (
        BUNDLE_UI_DASHBOARD_DEFAULT_CLUSTER,
        BUNDLE_UI_DASHBOARD_DEFAULT_TABLET_CELL_BUNDLE,
        BUNDLE_UI_DASHBOARD_DEFAULT_PROXY_ROLE,
    )

##################################################################


def build_dashboard(rowsets, bundle=False, role=False, host=False, only_parameters=False):
    d = Dashboard()
    for r in rowsets:
        d.add(r)

    d.add_parameter(
        "cluster",
        "YT cluster",
        MonitoringLabelDashboardParameter("yt", "cluster", BUNDLE_UI_DASHBOARD_DEFAULT_CLUSTER),
        backends=["monitoring"],
    )

    d.add_parameter(
        "cluster",
        "Cluster",
        GrafanaTextboxDashboardParameter(BUNDLE_UI_DASHBOARD_DEFAULT_CLUSTER),
        backends=["grafana"],
    )

    if bundle:
        if not only_parameters:
            d = d.value("tablet_cell_bundle", TemplateTag("tablet_cell_bundle"))
        d.add_parameter(
            "tablet_cell_bundle",
            "Tablet cell bundle",
            MonitoringLabelDashboardParameter("yt", "tablet_cell_bundle", BUNDLE_UI_DASHBOARD_DEFAULT_TABLET_CELL_BUNDLE),
            backends=["monitoring"],
        )
        d.add_parameter(
            "tablet_cell_bundle",
            "Tablet cell bundle",
            GrafanaTextboxDashboardParameter(BUNDLE_UI_DASHBOARD_DEFAULT_TABLET_CELL_BUNDLE),
            backends=["grafana"],
        )

    if role:
        if not only_parameters:
            d = d.value("proxy_role", TemplateTag("proxy_role"))
        d.add_parameter(
            "proxy_role",
            "Proxy role",
            MonitoringLabelDashboardParameter("yt", "proxy_role", BUNDLE_UI_DASHBOARD_DEFAULT_PROXY_ROLE),
            backends=["monitoring"],
        )
        d.add_parameter(
            "proxy_role",
            "Proxy role",
            GrafanaTextboxDashboardParameter(BUNDLE_UI_DASHBOARD_DEFAULT_PROXY_ROLE),
            backends=["grafana"],
        )

    if host:
        if not only_parameters:
            d = d.value(MonitoringTag("host"), TemplateTag("host"))
            d = d.value(GrafanaTag("pod"), TemplateTag("pod"))
        d.add_parameter(
            "host", "Host", MonitoringLabelDashboardParameter("yt", "host", "Aggr"), backends=["monitoring"]
        )
        d.add_parameter("pod", "Pod", GrafanaTextboxDashboardParameter(".*", ".*"), backends=["grafana"])

    return d


def build_bundle_dashboard(rowsets, *, host=False):
    return build_dashboard(rowsets, bundle=True, host=host)


def build_rpc_proxy_dashboard(rowsets, *, host=False):
    return build_dashboard(rowsets, role=True, host=host)


##################################################################


def build_bundle_ui_user_load():
    rowsets = [
        build_max_lookup_select_execute_time_per_host().aggr("#U").all(MonitoringTag("host")),
        build_user_load(),
    ]
    d = build_bundle_dashboard(rowsets)
    d.set_title("Bundle user load [Autogenerated]")
    return d


def build_bundle_ui_lsm():
    rowsets = [
        build_user_lsm(),
    ]
    d = build_bundle_dashboard(rowsets)
    d.set_title("Bundle LSM [Autogenerated]")
    return d


def build_bundle_ui_downtime():
    rowsets = [
        build_user_hydra(),
        build_tablet_balancer(),
        build_bundle_controller(),
    ]
    d = build_bundle_dashboard(rowsets)
    d.set_title("Bundle downtime [Autogenerated]")
    return d


def build_bundle_ui_cpu(has_porto):
    rowsets = [
        build_total_cpu(has_porto),
        build_user_thread_cpu(),
    ]
    d = build_bundle_dashboard(rowsets, host=True)
    d.set_title("Bundle CPU [Autogenerated]")
    return d


def build_bundle_ui_memory(has_cgroup):
    rowsets = [
        build_user_memory(has_cgroup),
        build_reserved_memory()
    ]
    d = build_bundle_dashboard(rowsets, host=True)
    d.set_title("Bundle memory [Autogenerated]")
    return d


def build_bundle_ui_network():
    rowsets = [
        build_user_network(),
        build_throttling(),
        build_rpc_request_rate(),
        build_tablet_network(),
        # build_user_bus_cpu(),
        build_lookup_select_ack_time(),
        build_rpc_message_size_stats_per_host(
            TabNodeRpcClient, "client", "Rpc client (yt_node)"),
        build_rpc_message_size_stats_per_host(
            TabNodeRpc, "server", "Rpc server (yt_node)"),
    ]
    d = build_bundle_dashboard(rowsets, host=True)
    d.set_title("Bundle network [Autogenerated]")
    return d


def build_bundle_ui_disk():
    rowsets = [
        build_user_disk(),
        build_user_background_disk(),
        build_user_caches(),
        build_block_cache_planning()
    ]
    d = build_bundle_dashboard(rowsets, host=True)
    d.set_title("Bundle disk [Autogenerated]")
    return d


def build_bundle_ui_resource_overview(has_porto):
    rowsets = [
        build_user_resource_overview_rowset(has_porto),
        *build_disk_statistics_rowsets()
    ]
    d = build_bundle_dashboard(rowsets)
    d.set_title("Bundle resource overview [Autogenerated]")
    return d


def build_bundle_ui_rpc_resource_overview():
    rowsets = [
        build_rpc_proxy_resource_overview_rowset(),
    ]
    d = build_rpc_proxy_dashboard(rowsets)
    d.set_title("Bundle RPC proxy resource overview [Autogenerated]")
    return d


def build_bundle_rpc_proxy_dashboard(has_porto):
    rowsets = [
        build_rpc_proxy_cpu(has_porto),
        build_rpc_proxy_network(),
        build_rpc_proxy_rpc_request_rate(),
        build_rpc_proxy_rpc_request_wait(),
        build_rpc_proxy_maintenance(has_porto),
    ]
    d = build_rpc_proxy_dashboard(rowsets, host=True)
    d.set_title("Bundle RPC proxy [Autogenerated]")
    return d


def build_bundle_ui_efficiency():
    rowsets = [
        build_efficiency_rowset(),
    ]
    d = build_dashboard(rowsets, bundle=True, only_parameters=True)
    d.set_title("Bundle efficiency [Autogenerated]")
    return d


def build_bundle_capacity_planning():
    rowsets = [
        build_tablet_static_planning(),
        build_node_resource_capacity_planning(),
        build_block_cache_planning(),
        build_rpc_proxy_resource_capacity_planning(),
    ]

    d = build_dashboard(rowsets, bundle=True, role=True, only_parameters=True)
    d.set_title("Bundle capacity planning [Autogenerated]")
    return d


def build_bundle_ui_key_filter():
    rowsets = [
        build_key_filter_rowset(),
        build_bundle_key_filter_rowset(),
    ]
    d = (build_bundle_dashboard(rowsets)
        .aggr("user", "table_path", "table_tag", MonitoringTag("host")))
    d.set_title("Bundle key filter [Autogenerated]")
    return d
