git add	cmake/conan-profiles/
git add	contrib/go/_std_1.22/src/archive/tar/stat_actime2.go
git add	contrib/go/_std_1.22/src/crypto/aes/asm_arm64.s
git add	contrib/go/_std_1.22/src/crypto/aes/gcm_arm64.s
git add	contrib/go/_std_1.22/src/crypto/internal/bigmod/nat_arm64.s
git add	contrib/go/_std_1.22/src/crypto/internal/boring/sig/sig_other.s
git add	contrib/go/_std_1.22/src/crypto/internal/edwards25519/field/fe_amd64_noasm.go
git add	contrib/go/_std_1.22/src/crypto/internal/edwards25519/field/fe_arm64.go
git add	contrib/go/_std_1.22/src/crypto/internal/edwards25519/field/fe_arm64.s
git add	contrib/go/_std_1.22/src/crypto/internal/nistec/p256_asm_arm64.s
git add	contrib/go/_std_1.22/src/crypto/md5/md5block_arm64.s
git add	contrib/go/_std_1.22/src/crypto/rand/rand_getentropy.go
git add	contrib/go/_std_1.22/src/crypto/sha1/sha1block_arm64.go
git add	contrib/go/_std_1.22/src/crypto/sha1/sha1block_arm64.s
git add	contrib/go/_std_1.22/src/crypto/sha256/sha256block_arm64.go
git add	contrib/go/_std_1.22/src/crypto/sha256/sha256block_arm64.s
git add	contrib/go/_std_1.22/src/crypto/sha512/sha512block_arm64.go
git add	contrib/go/_std_1.22/src/crypto/sha512/sha512block_arm64.s
git add	contrib/go/_std_1.22/src/crypto/subtle/xor_arm64.go
git add	contrib/go/_std_1.22/src/crypto/subtle/xor_arm64.s
git add	contrib/go/_std_1.22/src/crypto/x509/internal/
git add	contrib/go/_std_1.22/src/crypto/x509/root_darwin.go
git add	contrib/go/_std_1.22/src/hash/crc32/crc32_arm64.go
git add	contrib/go/_std_1.22/src/hash/crc32/crc32_arm64.s
git add	contrib/go/_std_1.22/src/internal/abi/abi_arm64.go
git add	contrib/go/_std_1.22/src/internal/bytealg/compare_arm64.s
git add	contrib/go/_std_1.22/src/internal/bytealg/count_arm64.s
git add	contrib/go/_std_1.22/src/internal/bytealg/equal_arm64.s
git add	contrib/go/_std_1.22/src/internal/bytealg/index_arm64.go
git add	contrib/go/_std_1.22/src/internal/bytealg/index_arm64.s
git add	contrib/go/_std_1.22/src/internal/bytealg/indexbyte_arm64.s
git add	contrib/go/_std_1.22/src/internal/chacha8rand/chacha8_arm64.s
git add	contrib/go/_std_1.22/src/internal/cpu/cpu_arm64.go
git add	contrib/go/_std_1.22/src/internal/cpu/cpu_arm64.s
git add	contrib/go/_std_1.22/src/internal/cpu/cpu_arm64_darwin.go
git add	contrib/go/_std_1.22/src/internal/cpu/cpu_no_name.go
git add	contrib/go/_std_1.22/src/internal/goarch/goarch_arm64.go
git add	contrib/go/_std_1.22/src/internal/goarch/zgoarch_arm64.go
git add	contrib/go/_std_1.22/src/internal/goos/zgoos_darwin.go
git add	contrib/go/_std_1.22/src/internal/poll/fd_fsync_darwin.go
git add	contrib/go/_std_1.22/src/internal/poll/fd_opendir_darwin.go
git add	contrib/go/_std_1.22/src/internal/poll/fd_writev_libc.go
git add	contrib/go/_std_1.22/src/internal/poll/sendfile_bsd.go
git add	contrib/go/_std_1.22/src/internal/poll/sys_cloexec.go
git add	contrib/go/_std_1.22/src/internal/syscall/unix/asm_darwin.s
git add	contrib/go/_std_1.22/src/internal/syscall/unix/at_libc2.go
git add	contrib/go/_std_1.22/src/internal/syscall/unix/at_sysnum_darwin.go
git add	contrib/go/_std_1.22/src/internal/syscall/unix/eaccess_other.go
git add	contrib/go/_std_1.22/src/internal/syscall/unix/getentropy_darwin.go
git add	contrib/go/_std_1.22/src/internal/syscall/unix/getentropy_darwin.s
git add	contrib/go/_std_1.22/src/internal/syscall/unix/kernel_version_other.go
git add	contrib/go/_std_1.22/src/internal/syscall/unix/net_darwin.go
git add	contrib/go/_std_1.22/src/internal/syscall/unix/pty_darwin.go
git add	contrib/go/_std_1.22/src/internal/syscall/unix/user_darwin.go
git add	contrib/go/_std_1.22/src/internal/sysinfo/cpuinfo_stub.go
git add	contrib/go/_std_1.22/src/math/big/arith_arm64.s
git add	contrib/go/_std_1.22/src/math/dim_arm64.s
git add	contrib/go/_std_1.22/src/math/exp2_asm.go
git add	contrib/go/_std_1.22/src/math/exp_arm64.s
git add	contrib/go/_std_1.22/src/math/floor_arm64.s
git add	contrib/go/_std_1.22/src/math/hypot_noasm.go
git add	contrib/go/_std_1.22/src/math/log_stub.go
git add	contrib/go/_std_1.22/src/math/modf_arm64.s
git add	contrib/go/_std_1.22/src/math/modf_asm.go
git add	contrib/go/_std_1.22/src/net/cgo_darwin.go
git add	contrib/go/_std_1.22/src/net/cgo_unix_cgo_darwin.go
git add	contrib/go/_std_1.22/src/net/cgo_unix_syscall.go
git add	contrib/go/_std_1.22/src/net/interface_bsd.go
git add	contrib/go/_std_1.22/src/net/interface_darwin.go
git add	contrib/go/_std_1.22/src/net/mptcpsock_stub.go
git add	contrib/go/_std_1.22/src/net/sendfile_unix_alt.go
git add	contrib/go/_std_1.22/src/net/sock_bsd.go
git add	contrib/go/_std_1.22/src/net/sockopt_bsd.go
git add	contrib/go/_std_1.22/src/net/sockoptip_bsdvar.go
git add	contrib/go/_std_1.22/src/net/splice_stub.go
git add	contrib/go/_std_1.22/src/net/sys_cloexec.go
git add	contrib/go/_std_1.22/src/net/tcpsockopt_darwin.go
git add	contrib/go/_std_1.22/src/net/unixsock_readmsg_cloexec.go
git add	contrib/go/_std_1.22/src/os/dir_darwin.go
git add	contrib/go/_std_1.22/src/os/executable_darwin.go
git add	contrib/go/_std_1.22/src/os/pipe_unix.go
git add	contrib/go/_std_1.22/src/os/stat_darwin.go
git add	contrib/go/_std_1.22/src/os/sticky_bsd.go
git add	contrib/go/_std_1.22/src/os/sys_bsd.go
git add	contrib/go/_std_1.22/src/os/user/cgo_lookup_syscall.go
git add	contrib/go/_std_1.22/src/os/user/getgrouplist_syscall.go
git add	contrib/go/_std_1.22/src/os/wait_unimp.go
git add	contrib/go/_std_1.22/src/os/zero_copy_stub.go
git add	contrib/go/_std_1.22/src/reflect/asm_arm64.s
git add	contrib/go/_std_1.22/src/runtime/asm_arm64.s
git add	contrib/go/_std_1.22/src/runtime/atomic_arm64.s
git add	contrib/go/_std_1.22/src/runtime/cgo/abi_arm64.h
git add	contrib/go/_std_1.22/src/runtime/cgo/asm_arm64.s
git add	contrib/go/_std_1.22/src/runtime/cgo/gcc_arm64.S
git add	contrib/go/_std_1.22/src/runtime/cgo/gcc_darwin_amd64.c
git add	contrib/go/_std_1.22/src/runtime/cgo/gcc_darwin_arm64.c
git add	contrib/go/_std_1.22/src/runtime/cgo/gcc_stack_darwin.c
git add	contrib/go/_std_1.22/src/runtime/cpuflags_arm64.go
git add	contrib/go/_std_1.22/src/runtime/defs_darwin_amd64.go
git add	contrib/go/_std_1.22/src/runtime/defs_darwin_arm64.go
git add	contrib/go/_std_1.22/src/runtime/duff_arm64.s
git add	contrib/go/_std_1.22/src/runtime/internal/atomic/atomic_arm64.go
git add	contrib/go/_std_1.22/src/runtime/internal/atomic/atomic_arm64.s
git add	contrib/go/_std_1.22/src/runtime/lock_sema.go
git add	contrib/go/_std_1.22/src/runtime/mem_darwin.go
git add	contrib/go/_std_1.22/src/runtime/memclr_arm64.s
git add	contrib/go/_std_1.22/src/runtime/memmove_arm64.s
git add	contrib/go/_std_1.22/src/runtime/nbpipe_pipe.go
git add	contrib/go/_std_1.22/src/runtime/netpoll_kqueue.go
git add	contrib/go/_std_1.22/src/runtime/os_darwin.go
git add	contrib/go/_std_1.22/src/runtime/os_darwin_arm64.go
git add	contrib/go/_std_1.22/src/runtime/os_unix_nonlinux.go
git add	contrib/go/_std_1.22/src/runtime/pprof/defs_darwin_amd64.go
git add	contrib/go/_std_1.22/src/runtime/pprof/defs_darwin_arm64.go
git add	contrib/go/_std_1.22/src/runtime/pprof/proto_darwin.go
git add	contrib/go/_std_1.22/src/runtime/pprof/vminfo_darwin.go
git add	contrib/go/_std_1.22/src/runtime/preempt_arm64.s
git add	contrib/go/_std_1.22/src/runtime/rt0_darwin_amd64.s
git add	contrib/go/_std_1.22/src/runtime/rt0_darwin_arm64.s
git add	contrib/go/_std_1.22/src/runtime/security_issetugid.go
git add	contrib/go/_std_1.22/src/runtime/signal_arm64.go
git add	contrib/go/_std_1.22/src/runtime/signal_darwin.go
git add	contrib/go/_std_1.22/src/runtime/signal_darwin_amd64.go
git add	contrib/go/_std_1.22/src/runtime/signal_darwin_arm64.go
git add	contrib/go/_std_1.22/src/runtime/stubs_arm64.go
git add	contrib/go/_std_1.22/src/runtime/stubs_nonlinux.go
git add	contrib/go/_std_1.22/src/runtime/sys_arm64.go
git add	contrib/go/_std_1.22/src/runtime/sys_darwin.go
git add	contrib/go/_std_1.22/src/runtime/sys_darwin_amd64.s
git add	contrib/go/_std_1.22/src/runtime/sys_darwin_arm64.go
git add	contrib/go/_std_1.22/src/runtime/sys_darwin_arm64.s
git add	contrib/go/_std_1.22/src/runtime/sys_libc.go
git add	contrib/go/_std_1.22/src/runtime/test_stubs.go
git add	contrib/go/_std_1.22/src/runtime/timestub.go
git add	contrib/go/_std_1.22/src/runtime/tls_arm64.h
git add	contrib/go/_std_1.22/src/runtime/tls_arm64.s
git add	contrib/go/_std_1.22/src/runtime/vdso_in_none.go
git add	contrib/go/_std_1.22/src/syscall/asm_darwin_amd64.s
git add	contrib/go/_std_1.22/src/syscall/asm_darwin_arm64.s
git add	contrib/go/_std_1.22/src/syscall/bpf_bsd.go
git add	contrib/go/_std_1.22/src/syscall/exec_libc2.go
git add	contrib/go/_std_1.22/src/syscall/flock_bsd.go
git add	contrib/go/_std_1.22/src/syscall/forkpipe.go
git add	contrib/go/_std_1.22/src/syscall/rlimit_darwin.go
git add	contrib/go/_std_1.22/src/syscall/route_bsd.go
git add	contrib/go/_std_1.22/src/syscall/route_darwin.go
git add	contrib/go/_std_1.22/src/syscall/syscall_bsd.go
git add	contrib/go/_std_1.22/src/syscall/syscall_darwin.go
git add	contrib/go/_std_1.22/src/syscall/syscall_darwin_amd64.go
git add	contrib/go/_std_1.22/src/syscall/syscall_darwin_arm64.go
git add	contrib/go/_std_1.22/src/syscall/zerrors_darwin_amd64.go
git add	contrib/go/_std_1.22/src/syscall/zerrors_darwin_arm64.go
git add	contrib/go/_std_1.22/src/syscall/zsyscall_darwin_amd64.go
git add	contrib/go/_std_1.22/src/syscall/zsyscall_darwin_amd64.s
git add	contrib/go/_std_1.22/src/syscall/zsyscall_darwin_arm64.go
git add	contrib/go/_std_1.22/src/syscall/zsyscall_darwin_arm64.s
git add	contrib/go/_std_1.22/src/syscall/zsysnum_darwin_amd64.go
git add	contrib/go/_std_1.22/src/syscall/zsysnum_darwin_arm64.go
git add	contrib/go/_std_1.22/src/syscall/ztypes_darwin_amd64.go
git add	contrib/go/_std_1.22/src/syscall/ztypes_darwin_arm64.go
git add	contrib/go/_std_1.22/src/vendor/golang.org/x/crypto/chacha20/chacha_arm64.go
git add	contrib/go/_std_1.22/src/vendor/golang.org/x/crypto/chacha20/chacha_arm64.s
git add	contrib/go/_std_1.22/src/vendor/golang.org/x/crypto/chacha20poly1305/chacha20poly1305_noasm.go
git add	contrib/go/_std_1.22/src/vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
git add	contrib/go/_std_1.22/src/vendor/golang.org/x/net/route/
git add	contrib/go/_std_1.22/src/vendor/golang.org/x/sys/cpu/cpu_arm64.go
git add	contrib/go/_std_1.22/src/vendor/golang.org/x/sys/cpu/cpu_arm64.s
git add	contrib/go/_std_1.22/src/vendor/golang.org/x/sys/cpu/cpu_gc_arm64.go
git add	contrib/go/_std_1.22/src/vendor/golang.org/x/sys/cpu/cpu_other_arm64.go
git add	contrib/libs/backtrace/macho.c
git add	contrib/libs/cxxsupp/builtins/clear_cache.c
git add	contrib/libs/cxxsupp/builtins/multc3.c
git add	contrib/libs/cxxsupp/builtins/os_version_check.c
git add	contrib/libs/isa-l/erasure_code/ec_multibinary_darwin.asm
git add	contrib/libs/jemalloc/reg_zone.cpp
git add	contrib/libs/jemalloc/src/zone.c
git add	contrib/libs/libc_compat/memrchr.c
git add	contrib/libs/libevent/kqueue.c
git add	contrib/libs/libjpeg-turbo/simd/arm/
git add	contrib/libs/libpng/arm/
git add	contrib/libs/nayuki_md5/md5.c
git add	contrib/libs/openssl/asm/darwin-arm64/
git add	contrib/libs/openssl/asm/darwin/
git add	contrib/libs/openssl/crypto/armcap.c
git add	contrib/libs/openssl/crypto/camellia/camellia.c
git add	contrib/libs/openssl/crypto/camellia/cmll_cbc.c
git add	contrib/libs/openssl/crypto/dso/dso_dlfcn.c
git add	contrib/libs/openssl/crypto/rc4/
git add	contrib/libs/openssl/crypto/whrlpool/wp_block.c
git add	contrib/libs/pybind11/include/pybind11/stl.h
git add	contrib/python/Pillow/py2/PIL/ImageGrab.py
git add	contrib/python/Pillow/py3/PIL/ImageGrab.py
git add	contrib/python/appnope/
git add	contrib/python/beniget/
git add	contrib/python/gast/
git add	contrib/python/ply/
git add	contrib/python/psutil/py2/psutil/_psutil_osx.c
git add	contrib/python/psutil/py2/psutil/arch/osx/
git add	contrib/python/psutil/py3/psutil/_psutil_osx.c
git add	contrib/python/psutil/py3/psutil/_psutil_posix.h
git add	contrib/python/psutil/py3/psutil/arch/osx/
git add	contrib/python/pythran/
git add	contrib/python/scipy/
git add	contrib/restricted/aws/aws-c-cal/source/darwin/
git add	contrib/restricted/aws/aws-c-common/source/arch/arm/
git add	contrib/restricted/aws/aws-c-io/source/bsd/
git add	contrib/restricted/boost/context/src/asm/jump_arm64_aapcs_macho_gas.S
git add	contrib/restricted/boost/context/src/asm/jump_x86_64_sysv_macho_gas.S
git add	contrib/restricted/boost/context/src/asm/make_arm64_aapcs_macho_gas.S
git add	contrib/restricted/boost/context/src/asm/make_x86_64_sysv_macho_gas.S
git add	contrib/restricted/boost/context/src/asm/ontop_arm64_aapcs_macho_gas.S
git add	contrib/restricted/boost/context/src/asm/ontop_x86_64_sysv_macho_gas.S
git add	contrib/restricted/boost/math/include/boost/math/distributions.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/arcsine.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/bernoulli.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/beta.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/binomial.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/cauchy.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/chi_squared.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/detail/generic_mode.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/detail/generic_quantile.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/detail/hypergeometric_cdf.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/detail/hypergeometric_pdf.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/detail/hypergeometric_quantile.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/detail/inv_discrete_quantile.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/exponential.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/extreme_value.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/find_location.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/find_scale.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/gamma.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/geometric.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/hyperexponential.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/hypergeometric.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/inverse_chi_squared.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/inverse_gamma.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/inverse_gaussian.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/kolmogorov_smirnov.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/laplace.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/logistic.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/lognormal.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/negative_binomial.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/non_central_beta.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/non_central_chi_squared.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/non_central_f.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/non_central_t.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/pareto.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/poisson.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/rayleigh.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/skew_normal.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/triangular.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/uniform.hpp
git add	contrib/restricted/boost/math/include/boost/math/distributions/weibull.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/bessel.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/bessel_iterators.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/airy_ai_bi_zero.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_i0.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_i1.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_ik.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_j0.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_j1.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_jn.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_jy.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_jy_asym.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_jy_series.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_jy_zero.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_k0.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_k1.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_kn.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_y0.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_y1.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/bessel_yn.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/hypergeometric_1F1_addition_theorems_on_z.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/hypergeometric_1F1_bessel.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/hypergeometric_1F1_by_ratios.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/hypergeometric_1F1_large_abz.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/hypergeometric_1F1_negative_b_regions.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/hypergeometric_1F1_recurrence.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/hypergeometric_1F1_scaled_series.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/hypergeometric_1F1_small_a_negative_b_by_ratio.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/hypergeometric_asym.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/hypergeometric_pFq_checked_series.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/hypergeometric_pade.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/hypergeometric_rational.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/hypergeometric_series.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/detail/iconv.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/hermite.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/hypergeometric_1F1.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/hypergeometric_2F0.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/hypergeometric_pFq.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/jacobi_theta.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/laguerre.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/modf.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/owens_t.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/prime.hpp
git add	contrib/restricted/boost/math/include/boost/math/special_functions/sinc.hpp
git add	contrib/restricted/boost/math/include/boost/math/tools/minima.hpp
git add	contrib/restricted/boost/math/include/boost/math/tools/recurrence.hpp
git add	contrib/restricted/google/benchmark/tools/compare/
git add	contrib/restricted/libffi/configs/aarch64-apple-macos/
git add	contrib/restricted/libffi/configs/x86_64-apple-macosx/
git add	contrib/restricted/libffi/src/aarch64/
git add	contrib/tools/bison/lib/error.c
git add	contrib/tools/bison/lib/fpending.c
git add	contrib/tools/bison/lib/obstack.c
git add	contrib/tools/bison/lib/obstack_printf.c
git add	contrib/tools/bison/lib/strverscmp.c
git add	contrib/tools/f2c/
git add	contrib/tools/m4/lib/fpending.c
git add	contrib/tools/m4/lib/obstack.c
git add	contrib/tools/m4/lib/obstack_printf.c
git add	contrib/tools/m4/lib/pipe2.c
git add	contrib/tools/m4/lib/strverscmp.c
git add	contrib/tools/python/src/Mac/
git add	contrib/tools/python3/Modules/_scproxy.c
git add	files.sh
git add	library/python/fs/clonefile.pyx
git add	tools/rescompiler/ya.make
git add	util/system/context_aarch64.S
git add	vendor/github.com/cespare/xxhash/v2/xxhash_arm64.s
git add	vendor/github.com/containerd/containerd/content/local/store_bsd.go
git add	vendor/github.com/containerd/containerd/defaults/defaults_darwin.go
git add	vendor/github.com/containerd/containerd/pkg/userns/userns_unsupported.go
git add	vendor/github.com/containerd/containerd/platforms/cpuinfo_other.go
git add	vendor/github.com/containerd/containerd/platforms/defaults_darwin.go
git add	vendor/github.com/containerd/continuity/fs/copy_darwin.go
git add	vendor/github.com/containerd/continuity/fs/copy_unix.go
git add	vendor/github.com/containerd/continuity/fs/stat_darwinbsd.go
git add	vendor/github.com/containerd/continuity/fs/utimesnanoat.go
git add	vendor/github.com/containerd/continuity/sysx/nodata_unix.go
git add	vendor/github.com/creack/pty/ioctl_bsd.go
git add	vendor/github.com/creack/pty/pty_darwin.go
git add	vendor/github.com/creack/pty/ztypes_arm64.go
git add	vendor/github.com/docker/docker/pkg/archive/archive_other.go
git add	vendor/github.com/docker/docker/pkg/archive/changes_other.go
git add	vendor/github.com/docker/docker/pkg/archive/time_unsupported.go
git add	vendor/github.com/docker/docker/pkg/idtools/usergroupadd_unsupported.go
git add	vendor/github.com/docker/docker/pkg/system/stat_darwin.go
git add	vendor/github.com/docker/docker/pkg/system/utimes_unsupported.go
git add	vendor/github.com/docker/docker/pkg/system/xattrs_unsupported.go
git add	vendor/github.com/golang/glog/glog_file_posix.go
git add	vendor/github.com/golang/snappy/decode_arm64.s
git add	vendor/github.com/golang/snappy/encode_arm64.s
git add	vendor/github.com/klauspost/compress/flate/matchlen_generic.go
git add	vendor/github.com/klauspost/compress/flate/regmask_other.go
git add	vendor/github.com/klauspost/compress/huff0/decompress_generic.go
git add	vendor/github.com/klauspost/compress/s2/decode_arm64.s
git add	vendor/github.com/klauspost/compress/s2/encode_go.go
git add	vendor/github.com/klauspost/compress/zstd/fse_decoder_generic.go
git add	vendor/github.com/klauspost/compress/zstd/internal/xxhash/xxhash_arm64.s
git add	vendor/github.com/klauspost/compress/zstd/matchlen_generic.go
git add	vendor/github.com/klauspost/compress/zstd/seqdec_generic.go
git add	vendor/github.com/moby/sys/signal/signal_darwin.go
git add	vendor/github.com/moby/term/termios_bsd.go
git add	vendor/github.com/pierrec/lz4/decode_other.go
git add	vendor/github.com/prometheus/procfs/fs_statfs_notype.go
git add	vendor/github.com/shirou/gopsutil/v3/cpu/cpu_darwin.go
git add	vendor/github.com/shirou/gopsutil/v3/cpu/cpu_darwin_cgo.go
git add	vendor/github.com/shirou/gopsutil/v3/cpu/cpu_darwin_test.go
git add	vendor/github.com/shirou/gopsutil/v3/mem/mem_darwin.go
git add	vendor/github.com/shirou/gopsutil/v3/mem/mem_darwin_cgo.go
git add	vendor/github.com/shirou/gopsutil/v3/mem/mem_darwin_test.go
git add	vendor/github.com/shirou/gopsutil/v3/net/net_darwin.go
git add	vendor/github.com/shirou/gopsutil/v3/net/net_darwin_test.go
git add	vendor/github.com/shirou/gopsutil/v3/net/net_unix.go
git add	vendor/github.com/shoenig/
git add	vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
git add	vendor/github.com/tklauser/go-sysconf/sysconf_bsd.go
git add	vendor/github.com/tklauser/go-sysconf/sysconf_darwin.go
git add	vendor/github.com/tklauser/go-sysconf/zsysconf_defs_darwin.go
git add	vendor/github.com/tklauser/numcpus/numcpus_bsd.go
git add	vendor/github.com/tonistiigi/fsutil/chtimes_nolinux.go
git add	vendor/github.com/twmb/murmur3/murmur128_gen.go
git add	vendor/go.opentelemetry.io/otel/sdk/resource/host_id_darwin.go
git add	vendor/go.opentelemetry.io/otel/sdk/resource/host_id_exec.go
git add	vendor/go.opentelemetry.io/otel/sdk/resource/os_release_darwin.go
git add	vendor/golang.org/x/crypto/chacha20/chacha_arm64.go
git add	vendor/golang.org/x/crypto/chacha20/chacha_arm64.s
git add	vendor/golang.org/x/crypto/chacha20poly1305/chacha20poly1305_noasm.go
git add	vendor/golang.org/x/crypto/curve25519/internal/field/fe_amd64_noasm.go
git add	vendor/golang.org/x/crypto/curve25519/internal/field/fe_arm64.go
git add	vendor/golang.org/x/crypto/curve25519/internal/field/fe_arm64.s
git add	vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
git add	vendor/golang.org/x/sys/cpu/cpu_arm64.go
git add	vendor/golang.org/x/sys/cpu/cpu_arm64.s
git add	vendor/golang.org/x/sys/cpu/cpu_gc_arm64.go
git add	vendor/golang.org/x/sys/cpu/cpu_other_arm64.go
git add	vendor/golang.org/x/term/term_unix_bsd.go
git add	vendor/google.golang.org/grpc/internal/channelz/types_nonlinux.go
git add	vendor/google.golang.org/grpc/internal/channelz/util_nonlinux.go
git add	vendor/google.golang.org/grpc/internal/googlecloud/manufacturer.go
git add	vendor/google.golang.org/grpc/internal/syscall/syscall_nonlinux.go
git add	yt/yt/library/backtrace_introspector/introspect_dummy.cpp
git add	yt/yt/library/profiling/perf/counters_other.cpp
git add	yt/yt/library/ytprof/symbolize_other.cpp
