rootProject.name = "YT"

include("yt:java:annotations")
include("yt:java:skiff")
include("yt:java:type-info")
include("yt:java:yson")
include("yt:java:yson-tree")
include("yt:java:ytsaurus-client")
include("yt:java:ytsaurus-client-core")
include("yt:java:ytsaurus-client-examples:cypress-operations-example")
include("yt:java:ytsaurus-client-examples:dynamic-table-example")
include("yt:java:ytsaurus-client-examples:map-entity-example")
include("yt:java:ytsaurus-client-examples:map-reduce-entity-example")
include("yt:java:ytsaurus-client-examples:map-reduce-ytree-example")
include("yt:java:ytsaurus-client-examples:map-ytree-example")
include("yt:java:ytsaurus-client-examples:read-write-entity-example")
include("yt:java:ytsaurus-client-examples:read-write-ytree-example")
include("yt:java:ytsaurus-client-examples:reduce-entity-example")
include("yt:java:ytsaurus-client-examples:reduce-ytree-example")
include("yt:yt_proto:yt:client")
include("yt:yt_proto:yt:core")
