#pragma once

#define CLICKHOUSE_CPP_VERSION_MAJOR 2
#define CLICKHOUSE_CPP_VERSION_MINOR 6
#define CLICKHOUSE_CPP_VERSION_PATCH 2

#define CLICKHOUSE_CPP_VERSION_BUILD 0

// Expecting each version component to be less than 99
#define CLICKHOUSE_CPP_VERSION \
    CLICKHOUSE_CPP_VERSION_MAJOR *   100 * 100 * 100 \
    + CLICKHOUSE_CPP_VERSION_MINOR * 100 * 100 \
    + CLICKHOUSE_CPP_VERSION_PATCH * 100 \
    + CLICKHOUSE_CPP_VERSION_BUILD
