LIBRARY()

SRCS(
    config_helpers.cpp
    config_helpers.h
    configs_cache.cpp
    configs_cache.h
    configs_config.cpp
    configs_config.h
    configs_dispatcher.cpp
    configs_dispatcher.h
    configs_dispatcher_proxy.h
    configs_dispatcher_proxy.cpp
    console.cpp
    console.h
    console_audit.cpp
    console_audit.h
    console_handshake.cpp
    console_configs_manager.cpp
    console_configs_manager.h
    console_configs_provider.cpp
    console_configs_provider.h
    console_configs_subscriber.cpp
    console_configs_subscriber.h
    console_configuration_info_collector.cpp
    console_configuration_info_collector.h
    console_impl.h
    console_tenants_manager.cpp
    console_tenants_manager.h
    console__add_config_subscription.cpp
    console__alter_tenant.cpp
    console__replace_yaml_config.cpp
    console__cleanup_subscriptions.cpp
    console__configure.cpp
    console__create_tenant.cpp
    console__drop_yaml_config.cpp
    console__init_scheme.cpp
    console__load_state.cpp
    console__get_log_tail.cpp
    console__get_yaml_config.cpp
    console__get_yaml_metadata.cpp
    console__log_cleanup.cpp
    console__remove_computational_units.cpp
    console__remove_config_subscription.cpp
    console__remove_config_subscriptions.cpp
    console__remove_tenant.cpp
    console__remove_tenant_done.cpp
    console__remove_tenant_failed.cpp
    console__replace_config_subscriptions.cpp
    console__revert_pool_state.cpp
    console__scheme.h
    console__set_config.cpp
    console__toggle_config_validator.cpp
    console__update_confirmed_subdomain.cpp
    console__update_last_provided_config.cpp
    console__update_pool_state.cpp
    console__update_subdomain_key.cpp
    console__update_tenant_state.cpp
    console__update_tenant_pool_config.cpp
    defs.h
    feature_flags_configurator.cpp
    feature_flags_configurator.h
    grpc_library_helper.cpp
    http.cpp
    http.h
    immediate_controls_configurator.cpp
    immediate_controls_configurator.h
    jaeger_tracing_configurator.cpp
    jaeger_tracing_configurator.h
    log_settings_configurator.cpp
    log_settings_configurator.h
    logger.cpp
    logger.h
    modifications_validator.cpp
    modifications_validator.h
    net_classifier_updater.cpp
    tx_processor.cpp
    tx_processor.h
    util.cpp
    util.h
)

PEERDIR(
    contrib/ydb/library/actors/core
    contrib/ydb/library/actors/http
    contrib/ydb/core/actorlib_impl
    contrib/ydb/core/base
    contrib/ydb/core/blobstorage
    contrib/ydb/core/blobstorage/base
    contrib/ydb/core/blobstorage/groupinfo
    contrib/ydb/core/cms/console/validators
    contrib/ydb/core/config/init
    contrib/ydb/core/control/lib
    contrib/ydb/core/engine/minikql
    contrib/ydb/core/mind
    contrib/ydb/core/node_whiteboard
    contrib/ydb/core/protos
    contrib/ydb/core/tablet
    contrib/ydb/core/tablet_flat
    contrib/ydb/core/util
    contrib/ydb/library/aclib
    contrib/ydb/library/yaml_config
    contrib/ydb/public/api/protos
    contrib/ydb/public/sdk/cpp/src/library/operation_id
    contrib/ydb/public/sdk/cpp/src/library/operation_id/protos
)

YQL_LAST_ABI_VERSION()

END()

RECURSE(
    util
    validators
)

RECURSE_FOR_TESTS(
    ut
)
