#!/usr/bin/env python

import os
import argparse
from yt.wrapper.cypress_commands import list

parser = argparse.ArgumentParser(description="Spark Submit")
parser.add_argument("--id", required=True)
parser.add_argument("--working-dir", required=False)
parser.add_argument("--auto-auth", required=False, default=True, type=bool)

args, unknown_args = parser.parse_known_args()

id = args.id
user = os.getenv("USER")
working_dir = args.working_dir or "//home/{0}/spark-tmp".format(user)

spark_home = os.getenv("SPARK_HOME")
master = list("{0}/instances/{1}/address".format(working_dir, id))[0]

spark_args = ["spark-shell", "--master", "spark://{0}".format(master)]
spark_env = os.environ.copy()

if args.auto_auth:
    with open("{0}/.yt/token".format(os.getenv("HOME"))) as f:
        token = f.readline().strip()
    spark_args.append("--conf")
    spark_args.append("spark.yt.user={}".format(user))
    spark_args.append("--conf")
    spark_args.append("spark.yt.token={}".format(token))
    spark_env["SPARK_USER"] = user

os.execve("{0}/bin/spark-submit".format(spark_home), spark_args + unknown_args, spark_env)
