# THIS FILE IS AUTOGENERATED, DO NOT EDIT !!!
# Generator: ya tool yamaker ym2; contrib/go/_std_{VER}/.yandex_meta/build.ym; contrib/go/yagogen/gen.py
# Docs: https://a.yandex-team.ru/arcadia/devtools/contrib/docs/toolchain_go.md


GO_LIBRARY()
IF (TRUE)
    SRCS(
        codes.go
        decoder.go
        doc.go
        encoder.go
        flags.go
        reloc.go
        support.go
        sync.go
        syncmarker_string.go
        version.go
    )
ENDIF()
END()
