#!/usr/bin/env python

import yt.wrapper.cypress_fuse as cypress_fuse
from yt.packages.fuse import FUSE

from argparse import ArgumentParser

import sys

def mount_cypress(proxy, mountpoint, disable_cache):
    """Mount a Cypress."""
    if disable_cache:
        yt_client = cypress_fuse.CachedYtClient(proxy=proxy, max_age_seconds=0)
    else:
        yt_client = cypress_fuse.CachedYtClient(proxy=proxy)

    cypress = cypress_fuse.Cypress(yt_client)
    FUSE(
        cypress, mountpoint,
        raw_fi=True, nothreads=True, foreground=True
    )
    return 0


if __name__ == "__main__":
    parser = ArgumentParser(description="Mount a Cypress, an YT cluster metainformation tree")

    parser.add_argument("proxy", help='Proxy alias like "aristotle.yt.yandex.net" or just "aristotle".')
    parser.add_argument("mountpoint", help='Mountpoint directory like "/mnt/aristotle".')
    parser.add_argument("--disable_cache", action="store_true", help="Disable client caching.")

    args = parser.parse_args()

    sys.exit(
        mount_cypress(args.proxy, args.mountpoint, args.disable_cache)
    )
