#!/usr/bin/env python

import yt.wrapper.cypress_fuse as cypress_fuse

import fuse

import sys

def mount_cypress(proxy, mountpoint):
    """Mount a Cypress."""
    cypress = cypress_fuse.Cypress(cypress_fuse.CachedYtClient(proxy=proxy))
    fuse.FUSE(
        cypress, mountpoint,
        raw_fi=True, nothreads=True, foreground=True
    )
    return 0


if __name__ == "__main__":
    arguments = docopt.docopt(__doc__)
    sys.exit(
        mount_cypress(arguments["<proxy>"], arguments["<mountpoint>"])
    )
