#!/usr/bin/env python

import yt.wrapper.cypress_fuse as cypress_fuse
from yt.wrapper import yson
from yt.packages.fuse import FUSE

from argparse import ArgumentParser

import logging

def mount_cypress(
        proxy,
        mount_point,
        caching_period,
        enable_write_access,
        config):
    """Mount a Cypress."""
    yt_client = cypress_fuse.CachedYtClient(
        max_age_seconds=caching_period,
        proxy=proxy,
        config=config)
    cypress = cypress_fuse.Cypress(yt_client, enable_write_access)
    FUSE(
        cypress, mount_point,
        raw_fi=True, nothreads=True, foreground=True
    )

    cypress_fuse.CachedYtClient._statistics.report()
    cypress_fuse.Cypress._statistics.report()


if __name__ == "__main__":
    parser = ArgumentParser(description="Mount a Cypress, an YT cluster metainformation tree")

    parser.add_argument("proxy", help='Proxy alias like "aristotle.yt.yandex.net" or just "aristotle".')
    parser.add_argument("mount_point", help='Mountpoint directory like "/mnt/aristotle".')
    parser.add_argument(
        "--caching-period",
        action="store",
        type=int,
        default=2,
        help="Cache expiration time.")
    parser.add_argument(
        "--enable-write-access",
        action="store_true",
        default=False,
        help="Enable write access to cypress.")
    parser.add_argument(
        "--enable-logging",
        action="store_true",
        default=False,
        help="Enable logging.")
    parser.add_argument(
        "--log-file",
        action="store",
        type=str,
        help="File for logging. If empty - write to stderr.")
    parser.add_argument(
        "--config",
        type=yson.loads,
        help="Custom configuration for YtClient.")

    args = parser.parse_args()

    if args.enable_logging:
        if args.log_file:
            handler = logging.FileHandler(args.log_file)
        else:
            handler = logging.StreamHandler()
        handler.setFormatter(cypress_fuse.BASIC_FORMATTER)
        logging.getLogger(cypress_fuse.LOGGER_NAME).handlers = [handler]
    else:
        logging.disable(logging.CRITICAL)

    mount_cypress(
        args.proxy,
        args.mount_point,
        args.caching_period,
        args.enable_write_access,
        args.config)
