LIBRARY()

INCLUDE(${ARCADIA_ROOT}/yt/ya_cpp.make.inc)

PROTO_NAMESPACE(yt)

SRCS(
    cell_master/alert_manager.cpp
    cell_master/automaton.cpp
    cell_master/bootstrap.cpp
    cell_master/cell_statistics.cpp
    cell_master/config_manager.cpp
    cell_master/config.cpp
    cell_master/epoch_history_manager.cpp
    cell_master/helpers.cpp
    cell_master/hydra_facade.cpp
    cell_master/master_hydra_service.cpp
    cell_master/multi_phase_cell_sync_session.cpp
    cell_master/multicell_manager.cpp
    cell_master/proto/alert_manager.proto
    cell_master/proto/epoch_history_manager.proto
    cell_master/proto/multicell_manager.proto
    cell_master/proto/response_keeper_manager.proto
    cell_master/response_keeper_manager.cpp
    cell_master/serialize.cpp
    cell_master/snapshot_exporter.cpp
    cell_master/world_initializer.cpp

    cell_server/area_proxy.cpp
    cell_server/area_type_handler.cpp
    cell_server/area.cpp
    cell_server/bundle_node_tracker.cpp
    cell_server/cell_balancer.cpp
    cell_server/cell_base.cpp
    cell_server/cell_bundle_proxy.cpp
    cell_server/cell_bundle_type_handler.cpp
    cell_server/cell_bundle.cpp
    cell_server/cell_hydra_janitor.cpp
    cell_server/cell_hydra_persistence_synchronizer.cpp
    cell_server/cell_map_proxy.cpp
    cell_server/cell_map_type_handler.cpp
    cell_server/cell_proxy_base.cpp
    cell_server/cell_tracker_impl.cpp
    cell_server/cell_tracker_service.cpp
    cell_server/cell_tracker.cpp
    cell_server/cell_type_handler_base.cpp
    cell_server/cellar_node_tracker_service.cpp
    cell_server/cellar_node_tracker.cpp
    cell_server/config.cpp
    cell_server/cypress_integration.cpp
    cell_server/helpers.cpp
    cell_server/public.cpp
    cell_server/tamed_cell_manager.cpp

    chaos_server/alien_cell_synchronizer.cpp
    chaos_server/alien_cell.cpp
    chaos_server/alien_cluster_registry.cpp
    chaos_server/chaos_cell_bundle_proxy.cpp
    chaos_server/chaos_cell_bundle_type_handler.cpp
    chaos_server/chaos_cell_bundle.cpp
    chaos_server/chaos_cell_proxy.cpp
    chaos_server/chaos_cell_type_handler.cpp
    chaos_server/chaos_cell.cpp
    chaos_server/chaos_manager.cpp
    chaos_server/chaos_replicated_table_node_proxy.cpp
    chaos_server/chaos_replicated_table_node_type_handler.cpp
    chaos_server/chaos_replicated_table_node.cpp
    chaos_server/chaos_service.cpp
    chaos_server/config.cpp

    chaos_server/proto/alien_cell.proto
    chaos_server/proto/chaos_manager.proto

    chunk_server/chunk_autotomizer.cpp
    chunk_server/chunk_creation_time_histogram_builder.cpp
    chunk_server/chunk_list_proxy.cpp
    chunk_server/chunk_list_type_handler.cpp
    chunk_server/chunk_list.cpp
    chunk_server/chunk_location_proxy.cpp
    chunk_server/chunk_location_type_handler.cpp
    chunk_server/chunk_location.cpp
    chunk_server/chunk_manager.cpp
    chunk_server/chunk_merger_traversal_info.cpp
    chunk_server/chunk_merger.cpp
    chunk_server/chunk_owner_base.cpp
    chunk_server/chunk_owner_node_proxy.cpp
    chunk_server/chunk_owner_type_handler.cpp
    chunk_server/chunk_placement.cpp
    chunk_server/chunk_proxy.cpp
    chunk_server/chunk_reincarnator.cpp
    chunk_server/chunk_replacer.cpp
    chunk_server/chunk_replica.cpp
    chunk_server/chunk_replicator.cpp
    chunk_server/chunk_replication_queue.cpp
    chunk_server/chunk_requisition.cpp
    chunk_server/chunk_scanner.cpp
    chunk_server/chunk_sealer.cpp
    chunk_server/chunk_service.cpp
    chunk_server/chunk_tree_balancer.cpp
    chunk_server/chunk_tree_statistics.cpp
    chunk_server/chunk_tree_traverser.cpp
    chunk_server/chunk_tree.cpp
    chunk_server/chunk_type_handler.cpp
    chunk_server/chunk_view_proxy.cpp
    chunk_server/chunk_view_type_handler.cpp
    chunk_server/chunk_view.cpp
    chunk_server/chunk_visitor.cpp
    chunk_server/chunk.cpp
    chunk_server/config.cpp
    chunk_server/consistent_chunk_placement.cpp
    chunk_server/cumulative_statistics.cpp
    chunk_server/cypress_integration.cpp
    chunk_server/data_node_tracker_service.cpp
    chunk_server/data_node_tracker.cpp
    chunk_server/domestic_medium_proxy.cpp
    chunk_server/domestic_medium_type_handler.cpp
    chunk_server/domestic_medium.cpp
    chunk_server/dynamic_store_proxy.cpp
    chunk_server/dynamic_store_type_handler.cpp
    chunk_server/dynamic_store.cpp
    chunk_server/helpers.cpp
    chunk_server/job_controller.cpp
    chunk_server/job_registry.cpp
    chunk_server/job_tracker_service.cpp
    chunk_server/job.cpp
    chunk_server/master_cell_chunk_statistics_collector.cpp
    chunk_server/medium_base.cpp
    chunk_server/medium_proxy_base.cpp
    chunk_server/medium_type_handler_base.cpp
    chunk_server/proto/chunk_autotomizer.proto
    chunk_server/proto/chunk_manager.proto
    chunk_server/proto/chunk_merger.proto
    chunk_server/proto/chunk_reincarnator.proto
    chunk_server/proto/master_cell_chunk_statistics_collector.proto
    chunk_server/public.cpp
    chunk_server/refresh_epoch.cpp
    chunk_server/s3_medium_proxy.cpp
    chunk_server/s3_medium_type_handler.cpp
    chunk_server/s3_medium.cpp

    cypress_server/access_control_object_namespace_type_handler.cpp
    cypress_server/access_control_object_namespace.cpp
    cypress_server/access_control_object_proxy.cpp
    cypress_server/access_control_object_type_handler.cpp
    cypress_server/access_control_object.cpp
    cypress_server/access_tracker.cpp
    cypress_server/config.cpp
    cypress_server/cypress_integration.cpp
    cypress_server/cypress_manager.cpp
    cypress_server/cypress_traverser.cpp
    cypress_server/document_node_proxy.cpp
    cypress_server/document_node_type_handler.cpp
    cypress_server/document_node.cpp
    cypress_server/expiration_tracker.cpp
    cypress_server/grafting_manager.cpp
    cypress_server/helpers.cpp
    cypress_server/link_node_proxy.cpp
    cypress_server/link_node_type_handler.cpp
    cypress_server/link_node.cpp
    cypress_server/lock_proxy.cpp
    cypress_server/lock.cpp
    cypress_server/node_detail.cpp
    cypress_server/node_proxy_detail.cpp
    cypress_server/node_proxy.cpp
    cypress_server/node.cpp
    cypress_server/portal_entrance_node.cpp
    cypress_server/portal_entrance_proxy.cpp
    cypress_server/portal_entrance_type_handler.cpp
    cypress_server/portal_exit_node.cpp
    cypress_server/portal_exit_proxy.cpp
    cypress_server/portal_exit_type_handler.cpp
    cypress_server/portal_manager.cpp
    cypress_server/portal_node_map_type_handler.cpp
    cypress_server/proto/cypress_manager.proto
    cypress_server/proto/grafting_manager.proto
    cypress_server/proto/portal_manager.proto
    cypress_server/resolve_cache.cpp
    cypress_server/rootstock_map_type_handler.cpp
    cypress_server/rootstock_node.cpp
    cypress_server/rootstock_proxy.cpp
    cypress_server/rootstock_type_handler.cpp
    cypress_server/scion_map_type_handler.cpp
    cypress_server/scion_node.cpp
    cypress_server/scion_proxy.cpp
    cypress_server/scion_type_handler.cpp
    cypress_server/sequoia_actions_executor.cpp
    cypress_server/serialize.cpp
    cypress_server/shard_map_type_handler.cpp
    cypress_server/shard_proxy.cpp
    cypress_server/shard_type_handler.cpp
    cypress_server/shard.cpp
    cypress_server/virtual.cpp

    file_server/file_node_proxy.cpp
    file_server/file_node_type_handler.cpp
    file_server/file_node.cpp
    file_server/public.cpp

    hive/cell_directory_synchronizer.cpp
    hive/cluster_directory_synchronizer.cpp

    incumbent_server/config.cpp
    incumbent_server/incumbent_detail.cpp
    incumbent_server/incumbent_manager.cpp
    incumbent_server/incumbent_service.cpp
    incumbent_server/scheduler.cpp

    journal_server/journal_manager.cpp
    journal_server/journal_node_proxy.cpp
    journal_server/journal_node_type_handler.cpp
    journal_server/journal_node.cpp
    journal_server/public.cpp

    maintenance_tracker_server/cluster_proxy_node.cpp
    maintenance_tracker_server/cluster_proxy_node_proxy.cpp
    maintenance_tracker_server/cluster_proxy_node_type_handler.cpp
    maintenance_tracker_server/helpers.cpp
    maintenance_tracker_server/maintenance_request.cpp
    maintenance_tracker_server/maintenance_target.cpp
    maintenance_tracker_server/maintenance_tracker.cpp
    maintenance_tracker_server/proto/maintenance_tracker.proto

    node_tracker_server/config.cpp
    node_tracker_server/cypress_integration.cpp
    node_tracker_server/data_center_proxy.cpp
    node_tracker_server/data_center_type_handler.cpp
    node_tracker_server/data_center.cpp
    node_tracker_server/exec_node_tracker_service.cpp
    node_tracker_server/exec_node_tracker.cpp
    node_tracker_server/host_proxy.cpp
    node_tracker_server/host_type_handler.cpp
    node_tracker_server/host.cpp
    node_tracker_server/node_directory_builder.cpp
    node_tracker_server/node_discovery_manager.cpp
    node_tracker_server/node_disposal_manager.cpp
    node_tracker_server/node_proxy.cpp
    node_tracker_server/node_statistics_helpers.cpp
    node_tracker_server/node_tracker_log.cpp
    node_tracker_server/node_tracker_service.cpp
    node_tracker_server/node_tracker.cpp
    node_tracker_server/node_type_handler.cpp
    node_tracker_server/node.cpp
    node_tracker_server/proto/node_tracker.proto
    node_tracker_server/public.cpp
    node_tracker_server/rack_proxy.cpp
    node_tracker_server/rack_type_handler.cpp
    node_tracker_server/rack.cpp

    object_server/attribute_set.cpp
    object_server/config.cpp
    object_server/cypress_integration.cpp
    object_server/features.cpp
    object_server/garbage_collector.cpp
    object_server/helpers.cpp
    object_server/map_object_proxy.cpp
    object_server/map_object_type_handler.cpp
    object_server/map_object.cpp
    object_server/master_proxy.cpp
    object_server/master_type_handler.cpp
    object_server/master.cpp
    object_server/mutation_idempotizer.cpp
    object_server/object_detail.cpp
    object_server/object_manager.cpp
    object_server/object_service.cpp
    object_server/object.cpp
    object_server/path_resolver.cpp
    object_server/proto/object_manager.proto
    object_server/request_profiling_manager.cpp
    object_server/schema_proxy.cpp
    object_server/schema.cpp
    object_server/staged_object.cpp
    object_server/sys_node_proxy.cpp
    object_server/sys_node_type_handler.cpp
    object_server/type_handler.cpp
    object_server/yson_intern_registry.cpp

    orchid_server/cypress_integration.cpp

    scheduler_pool_server/config.cpp
    scheduler_pool_server/cypress_integration.cpp
    scheduler_pool_server/pool_resources.cpp
    scheduler_pool_server/scheduler_pool_manager.cpp
    scheduler_pool_server/scheduler_pool_proxy.cpp
    scheduler_pool_server/scheduler_pool.cpp

    security_server/access_log.cpp
    security_server/account_proxy.cpp
    security_server/account_resource_usage_lease_proxy.cpp
    security_server/account_resource_usage_lease.cpp
    security_server/account.cpp
    security_server/ace_iterator.cpp
    security_server/acl.cpp
    security_server/cluster_resource_limits.cpp
    security_server/cluster_resources.cpp
    security_server/config.cpp
    security_server/cypress_integration.cpp
    security_server/detailed_master_memory.cpp
    security_server/group_proxy.cpp
    security_server/group.cpp
    security_server/helpers.cpp
    security_server/master_memory_limits.cpp
    security_server/network_project_proxy.cpp
    security_server/network_project.cpp
    security_server/proxy_role_proxy.cpp
    security_server/proxy_role.cpp
    security_server/request_tracker.cpp
    security_server/security_manager.cpp
    security_server/proto/security_manager.proto
    security_server/security_tags.cpp
    security_server/subject_proxy_detail.cpp
    security_server/subject.cpp
    security_server/user_proxy.cpp
    security_server/user.cpp
    security_server/user_activity_tracker.cpp

    sequoia_server/config.cpp
    sequoia_server/context.cpp
    sequoia_server/public.cpp
    sequoia_server/sequoia_manager.cpp
    sequoia_server/sequoia_transaction_service.cpp

    table_server/config.cpp
    table_server/cypress_integration.cpp
    table_server/helpers.cpp
    table_server/master_table_schema_proxy.cpp
    table_server/master_table_schema.cpp
    table_server/mount_config_attributes.cpp
    table_server/public.cpp
    table_server/replicated_table_node_proxy.cpp
    table_server/replicated_table_node_type_handler.cpp
    table_server/replicated_table_node.cpp
    table_server/schemaful_node_type_handler.cpp
    table_server/schemaful_node.cpp
    table_server/secondary_index_proxy.cpp
    table_server/secondary_index_type_handler.cpp
    table_server/secondary_index.cpp
    table_server/table_collocation_proxy.cpp
    table_server/table_collocation_type_handler.cpp
    table_server/table_collocation.cpp
    table_server/table_manager.cpp
    table_server/table_node_proxy_detail.cpp
    table_server/table_node_proxy.cpp
    table_server/table_node_type_handler_detail.cpp
    table_server/table_node_type_handler.cpp
    table_server/table_node.cpp

    tablet_server/backup_manager.cpp
    tablet_server/balancing_helpers.cpp
    tablet_server/chaos_helpers.cpp
    tablet_server/config.cpp
    tablet_server/cypress_integration.cpp
    tablet_server/helpers.cpp
    tablet_server/hunk_storage_node_proxy.cpp
    tablet_server/hunk_storage_node_type_handler.cpp
    tablet_server/hunk_storage_node.cpp
    tablet_server/hunk_tablet_proxy.cpp
    tablet_server/hunk_tablet_type_handler.cpp
    tablet_server/hunk_tablet.cpp
    tablet_server/mount_config_storage.cpp
    tablet_server/public.cpp
    tablet_server/replicated_table_tracker.cpp
    tablet_server/replicated_table_tracker_service.cpp
    tablet_server/table_replica_proxy.cpp
    tablet_server/table_replica_type_handler.cpp
    tablet_server/table_replica.cpp
    tablet_server/table_settings.cpp
    tablet_server/tablet_action_manager.cpp
    tablet_server/tablet_action_proxy.cpp
    tablet_server/tablet_action_type_handler.cpp
    tablet_server/tablet_action.cpp
    tablet_server/tablet_balancer.cpp
    tablet_server/tablet_base.cpp
    tablet_server/tablet_cell_bundle_proxy.cpp
    tablet_server/tablet_cell_bundle_type_handler.cpp
    tablet_server/tablet_cell_bundle.cpp
    tablet_server/tablet_cell_decommissioner.cpp
    tablet_server/tablet_cell_proxy.cpp
    tablet_server/tablet_cell_type_handler.cpp
    tablet_server/tablet_cell.cpp
    tablet_server/tablet_chunk_manager.cpp
    tablet_server/tablet_hydra_service.cpp
    tablet_server/tablet_manager.cpp
    tablet_server/tablet_node_tracker_service.cpp
    tablet_server/tablet_node_tracker.cpp
    tablet_server/tablet_owner_base.cpp
    tablet_server/tablet_owner_proxy_base.cpp
    tablet_server/tablet_owner_type_handler_base.cpp
    tablet_server/tablet_proxy_base.cpp
    tablet_server/tablet_proxy.cpp
    tablet_server/tablet_resources.cpp
    tablet_server/tablet_service.cpp
    tablet_server/tablet_statistics.cpp
    tablet_server/tablet_type_handler_base.cpp
    tablet_server/tablet_type_handler.cpp
    tablet_server/tablet.cpp

    transaction_server/boomerang_tracker.cpp
    transaction_server/config.cpp
    transaction_server/cypress_integration.cpp
    transaction_server/cypress_transaction_service.cpp
    transaction_server/proto/transaction_manager.proto
    transaction_server/transaction_manager.cpp
    transaction_server/transaction_presence_cache.cpp
    transaction_server/transaction_proxy.cpp
    transaction_server/transaction_replication_session.cpp
    transaction_server/transaction_rotator.cpp
    transaction_server/transaction_service.cpp
    transaction_server/transaction_type_handler.cpp
    transaction_server/transaction.cpp

    zookeeper_server/bootstrap_proxy.cpp
    zookeeper_server/cypress_integration.cpp
    zookeeper_server/zookeeper_manager.cpp
    zookeeper_server/zookeeper_shard_proxy.cpp
    zookeeper_server/zookeeper_shard_type_handler.cpp
    zookeeper_server/zookeeper_shard.cpp
)

PEERDIR(
    library/cpp/getopt
    yt/yt/ytlib/distributed_throttler
    yt/yt/server/lib
    yt/yt/server/lib/cell_server
    yt/yt/server/lib/cellar_agent
    yt/yt/server/lib/chunk_server
    yt/yt/server/lib/discovery_server
    yt/yt/server/lib/hive
    yt/yt/server/lib/hydra/dry_run
    yt/yt/server/lib/hydra
    yt/yt/server/lib/incumbent_client
    yt/yt/server/lib/node_tracker_server
    yt/yt/server/lib/security_server
    yt/yt/server/lib/table_server
    yt/yt/server/lib/tablet_balancer
    yt/yt/server/lib/tablet_server
    yt/yt/server/lib/timestamp_server
    yt/yt/server/lib/transaction_supervisor
    yt/yt/server/lib/zookeeper_master

    library/cpp/yt/phdr_cache

    # TODO(max42): eliminate.
    yt/yt/server/lib/scheduler
    yt/yt/server/lib/controller_agent
)

END()

RECURSE_FOR_TESTS(
    unittests
)
