DOCS()

SUBSCRIBER(
    andozer
    arivkin
    ogorbacheva
)

DOCS_DIR(yt/docs/)

DOCS_COPY_FILES(
    FROM ${ARCADIA_ROOT}/yt/docs/flow-public-check NAMESPACE ru toc.yaml
)

DOCS_COPY_FILES(
    FROM ${ARCADIA_ROOT}/yt/docs/ru NAMESPACE ru/_flow_check_base toc.yaml
)

DOCS_INCLUDE_SOURCES(
    yt/cpp/mapreduce/examples/tutorial/batch_request/main.cpp
    yt/cpp/mapreduce/examples/tutorial/dyntable_get_insert/main.cpp
    yt/cpp/mapreduce/examples/tutorial/job_statistics/main.cpp
    yt/cpp/mapreduce/examples/tutorial/join_reduce_tnode/main.cpp
    yt/cpp/mapreduce/examples/tutorial/map_tnode_with_file/main.cpp
    yt/cpp/mapreduce/examples/tutorial/mapreduce_lambda/main.cpp
    yt/cpp/mapreduce/examples/tutorial/mapreduce_protobuf/main.cpp
    yt/cpp/mapreduce/examples/tutorial/multiple_input_multiple_output_reduce_protobuf/data.proto
    yt/cpp/mapreduce/examples/tutorial/multiple_input_multiple_output_reduce_protobuf/main.cpp
    yt/cpp/mapreduce/examples/tutorial/multiple_input_multiple_output_reduce_tnode/main.cpp
    yt/cpp/mapreduce/examples/tutorial/multiple_input_reduce_tnode/main.cpp
    yt/cpp/mapreduce/examples/tutorial/operation_tracker/main.cpp
    yt/cpp/mapreduce/examples/tutorial/pass_table_as_file/main.cpp
    yt/cpp/mapreduce/examples/tutorial/prepare_operation/grepper.proto
    yt/cpp/mapreduce/examples/tutorial/prepare_operation/main.cpp
    yt/cpp/mapreduce/examples/tutorial/protobuf_complex_types/data.proto
    yt/cpp/mapreduce/examples/tutorial/protobuf_complex_types/main.cpp
    yt/cpp/mapreduce/examples/tutorial/simple_map_lambda/main.cpp
    yt/cpp/mapreduce/examples/tutorial/simple_map_protobuf/data.proto
    yt/cpp/mapreduce/examples/tutorial/simple_map_protobuf/main.cpp
    yt/cpp/mapreduce/examples/tutorial/simple_map_tnode/main.cpp
    yt/cpp/mapreduce/examples/tutorial/simple_reduce_tnode/main.cpp
    yt/cpp/mapreduce/examples/tutorial/stateful_map_tnode/main.cpp
    yt/cpp/mapreduce/examples/tutorial/table_read_write_tnode/main.cpp
    yt/java/ytsaurus-client-examples/cypress-operations-example/src/main/java/tech/ytsaurus/example/ExampleCypressOperations.java
    yt/java/ytsaurus-client-examples/dynamic-table-example/src/main/java/tech/ytsaurus/example/ExampleDynamicTable.java
    yt/java/ytsaurus-client-examples/map-entity-example/src/main/java/tech/ytsaurus/example/ExampleMapEntity.java
    yt/java/ytsaurus-client-examples/map-reduce-entity-example/src/main/java/tech/ytsaurus/example/ExampleMapReduceEntity.java
    yt/java/ytsaurus-client-examples/map-reduce-ytree-example/src/main/java/tech/ytsaurus/example/ExampleMapReduceYTree.java
    yt/java/ytsaurus-client-examples/map-ytree-example/src/main/java/tech/ytsaurus/example/ExampleMapYTree.java
    yt/java/ytsaurus-client-examples/read-write-entity-example/src/main/java/tech/ytsaurus/example/ExampleReadWriteEntity.java
    yt/java/ytsaurus-client-examples/read-write-ytree-example/src/main/java/tech/ytsaurus/example/ExampleReadWriteYTree.java
    yt/java/ytsaurus-client-examples/reduce-entity-example/src/main/java/tech/ytsaurus/example/ExampleReduceEntity.java
    yt/java/ytsaurus-client-examples/reduce-ytree-example/src/main/java/tech/ytsaurus/example/ExampleReduceYTree.java
    yt/python/examples/batch_client/example.py
    yt/python/examples/dataclass_typed/example.py
    yt/python/examples/dynamic_tables_rpc/example.py
    yt/python/examples/files/example.py
    yt/python/examples/files_typed/example.py
    yt/python/examples/gevent/example.py
    yt/python/examples/grep_typed/example.py
    yt/python/examples/job_decorators/example.py
    yt/python/examples/job_decorators_typed/example.py
    yt/python/examples/map_reduce/example.py
    yt/python/examples/map_reduce_multiple_intermediate_streams_typed/example.py
    yt/python/examples/map_reduce_typed/example.py
    yt/python/examples/multiple_input_multiple_output_reduce/example.py
    yt/python/examples/multiple_input_multiple_output_reduce_typed/example.py
    yt/python/examples/multiple_input_reduce/example.py
    yt/python/examples/multiple_input_reduce_typed/example.py
    yt/python/examples/prepare_operation_typed/example.py
    yt/python/examples/simple_map/example.py
    yt/python/examples/simple_map_typed/example.py
    yt/python/examples/simple_reduce/example.py
    yt/python/examples/simple_reduce_typed/example.py
    yt/python/examples/simple_rpc/example.py
    yt/python/examples/spec_builder_typed/example.py
    yt/python/examples/table_read_write/example.py
    yt/python/examples/table_read_write_typed/example.py
    yt/python/examples/table_schema_typed/example.py
    yt/python/examples/table_switches/example.py
    yt/python/examples/table_switches_typed/example.py
    yt/python/examples/yson_string_proxy/example.py
    yt/spark/spark-over-yt/examples/java/src/main/java/tech/ytsaurus/spyt/example/GroupingExample.java
    yt/spark/spark-over-yt/examples/java/src/main/java/tech/ytsaurus/spyt/example/SmokeTest.java
    yt/spark/spark-over-yt/examples/java/src/main/java/tech/ytsaurus/spyt/example/UdfExample.java
    yt/yt/flow/examples/cpp/async_request/main.cpp
    yt/yt/flow/examples/cpp/retryable_async_request/main.cpp
    yt/yt/flow/examples/cpp/shuffle/main.cpp
    yt/yt/flow/examples/cpp/url_downloader/main.cpp
    yt/yt/flow/examples/cpp/wait_click_join/lib/wait_click_join_functions.cpp
    yt/yt/flow/examples/cpp/word_count/lib/word_count_functions.cpp
    yt/yt/flow/examples/cpp/word_count/main.cpp
    yt/yt/flow/examples/java/async_request/async_request/src/main/java/tech/ytsaurus/flow/examples/asyncrequest/AsyncRequestComputationContext.java
    yt/yt/flow/examples/java/async_request/async_request/src/main/java/tech/ytsaurus/flow/examples/asyncrequest/NodeCompanionMain.java
    yt/yt/flow/examples/java/async_request/async_request/src/main/java/tech/ytsaurus/flow/examples/asyncrequest/RequestProcessorFunction.java
    yt/yt/flow/examples/java/async_request/async_request/src/main/java/tech/ytsaurus/flow/examples/asyncrequest/StateKeeperFunction.java
    yt/yt/flow/examples/java/retryable_async_request/retryable_async_request/src/main/java/tech/ytsaurus/flow/examples/retryableasyncrequest/NodeCompanionMain.java
    yt/yt/flow/examples/java/retryable_async_request/retryable_async_request/src/main/java/tech/ytsaurus/flow/examples/retryableasyncrequest/RequestProcessorFunction.java
    yt/yt/flow/examples/java/retryable_async_request/retryable_async_request/src/main/java/tech/ytsaurus/flow/examples/retryableasyncrequest/RetryableAsyncRequestComputationContext.java
    yt/yt/flow/examples/java/retryable_async_request/retryable_async_request/src/main/java/tech/ytsaurus/flow/examples/retryableasyncrequest/StateKeeperFunction.java
    yt/yt/flow/examples/java/retryable_async_request/retryable_async_request/src/main/java/tech/ytsaurus/flow/examples/retryableasyncrequest/model/RequestState.java
    yt/yt/flow/examples/java/shuffle/shuffle/src/main/java/tech/ytsaurus/flow/examples/shuffle/EventMapper.java
    yt/yt/flow/examples/java/shuffle/shuffle/src/main/java/tech/ytsaurus/flow/examples/shuffle/EventReducer.java
    yt/yt/flow/examples/java/shuffle/shuffle/src/main/java/tech/ytsaurus/flow/examples/shuffle/NodeCompanionMain.java
    yt/yt/flow/examples/java/shuffle/shuffle/src/main/java/tech/ytsaurus/flow/examples/shuffle/ShuffleComputationContext.java
    yt/yt/flow/examples/java/url_downloader/url_downloader/src/main/java/tech/ytsaurus/flow/examples/urldownloader/NodeCompanionMain.java
    yt/yt/flow/examples/java/url_downloader/url_downloader/src/main/java/tech/ytsaurus/flow/examples/urldownloader/UrlDownloadFunction.java
    yt/yt/flow/examples/java/url_downloader/url_downloader/src/main/java/tech/ytsaurus/flow/examples/urldownloader/UrlDownloaderComputationContext.java
    yt/yt/flow/examples/java/url_downloader/url_downloader/src/main/java/tech/ytsaurus/flow/examples/urldownloader/model/HostState.java
    yt/yt/flow/examples/java/wait_click_join/wait_click_join/src/main/java/tech/ytsaurus/flow/examples/waitclickjoin/JoinProcessFunction.java
    yt/yt/flow/examples/java/wait_click_join/wait_click_join/src/main/java/tech/ytsaurus/flow/examples/waitclickjoin/NodeCompanionMain.java
    yt/yt/flow/examples/java/wait_click_join/wait_click_join/src/main/java/tech/ytsaurus/flow/examples/waitclickjoin/PipelineConfiguration.java
    yt/yt/flow/examples/java/wait_click_join/wait_click_join/src/main/java/tech/ytsaurus/flow/examples/waitclickjoin/RunnerMain.java
    yt/yt/flow/examples/java/wait_click_join/wait_click_join/src/main/java/tech/ytsaurus/flow/examples/waitclickjoin/model/Action.java
    yt/yt/flow/examples/java/wait_click_join/wait_click_join/src/main/java/tech/ytsaurus/flow/examples/waitclickjoin/model/Hit.java
    yt/yt/flow/examples/java/wait_click_join/wait_click_join/src/main/java/tech/ytsaurus/flow/examples/waitclickjoin/model/JoinedAction.java
    yt/yt/flow/examples/java/wait_click_join/wait_click_join/src/test/java/tech/ytsaurus/flow/examples/waitclickjoin/JoinProcessFunctionTest.java
    yt/yt/flow/examples/java/word_count/wordcount/src/main/java/tech/ytsaurus/flow/examples/wordcount/RunnerMain.java
    yt/yt/flow/examples/java/word_count/wordcount/src/main/java/tech/ytsaurus/flow/examples/wordcount/WordCountApplication.java
    yt/yt/flow/examples/java/word_count/wordcount/src/main/java/tech/ytsaurus/flow/examples/wordcount/WordCountContext.java
    yt/yt/flow/examples/java/word_count/wordcount/src/main/java/tech/ytsaurus/flow/examples/wordcount/WordCountMapper.java
    yt/yt/flow/examples/kotlin/async_request/async_request/src/main/kotlin/tech/ytsaurus/flow/examples/asyncrequest/AsyncRequestComputationContext.kt
    yt/yt/flow/examples/kotlin/async_request/async_request/src/main/kotlin/tech/ytsaurus/flow/examples/asyncrequest/NodeCompanionMain.kt
    yt/yt/flow/examples/kotlin/async_request/async_request/src/main/kotlin/tech/ytsaurus/flow/examples/asyncrequest/RequestProcessorFunction.kt
    yt/yt/flow/examples/kotlin/async_request/async_request/src/main/kotlin/tech/ytsaurus/flow/examples/asyncrequest/StateKeeperFunction.kt
    yt/yt/flow/examples/kotlin/retryable_async_request/retryable_async_request/src/main/kotlin/tech/ytsaurus/flow/examples/retryableasyncrequest/NodeCompanionMain.kt
    yt/yt/flow/examples/kotlin/retryable_async_request/retryable_async_request/src/main/kotlin/tech/ytsaurus/flow/examples/retryableasyncrequest/RequestProcessorFunction.kt
    yt/yt/flow/examples/kotlin/retryable_async_request/retryable_async_request/src/main/kotlin/tech/ytsaurus/flow/examples/retryableasyncrequest/RetryableAsyncRequestComputationContext.kt
    yt/yt/flow/examples/kotlin/retryable_async_request/retryable_async_request/src/main/kotlin/tech/ytsaurus/flow/examples/retryableasyncrequest/StateKeeperFunction.kt
    yt/yt/flow/examples/kotlin/retryable_async_request/retryable_async_request/src/main/kotlin/tech/ytsaurus/flow/examples/retryableasyncrequest/model/RequestState.kt
    yt/yt/flow/examples/kotlin/shuffle/shuffle/src/main/kotlin/tech/ytsaurus/flow/examples/shuffle/EventMapper.kt
    yt/yt/flow/examples/kotlin/shuffle/shuffle/src/main/kotlin/tech/ytsaurus/flow/examples/shuffle/EventReducer.kt
    yt/yt/flow/examples/kotlin/shuffle/shuffle/src/main/kotlin/tech/ytsaurus/flow/examples/shuffle/NodeCompanionMain.kt
    yt/yt/flow/examples/kotlin/shuffle/shuffle/src/main/kotlin/tech/ytsaurus/flow/examples/shuffle/ShuffleComputationContext.kt
    yt/yt/flow/examples/kotlin/url_downloader/url_downloader/src/main/kotlin/tech/ytsaurus/flow/examples/urldownloader/NodeCompanionMain.kt
    yt/yt/flow/examples/kotlin/url_downloader/url_downloader/src/main/kotlin/tech/ytsaurus/flow/examples/urldownloader/UrlDownloadFunction.kt
    yt/yt/flow/examples/kotlin/url_downloader/url_downloader/src/main/kotlin/tech/ytsaurus/flow/examples/urldownloader/UrlDownloaderComputationContext.kt
    yt/yt/flow/examples/kotlin/url_downloader/url_downloader/src/main/kotlin/tech/ytsaurus/flow/examples/urldownloader/model/HostState.kt
    yt/yt/flow/examples/kotlin/wait_click_join/wait_click_join/src/main/kotlin/tech/ytsaurus/flow/examples/waitclickjoin/JoinProcessFunction.kt
    yt/yt/flow/examples/kotlin/wait_click_join/wait_click_join/src/main/kotlin/tech/ytsaurus/flow/examples/waitclickjoin/NodeCompanionMain.kt
    yt/yt/flow/examples/kotlin/wait_click_join/wait_click_join/src/main/kotlin/tech/ytsaurus/flow/examples/waitclickjoin/PipelineConfiguration.kt
    yt/yt/flow/examples/kotlin/wait_click_join/wait_click_join/src/main/kotlin/tech/ytsaurus/flow/examples/waitclickjoin/RunnerMain.kt
    yt/yt/flow/examples/kotlin/wait_click_join/wait_click_join/src/main/kotlin/tech/ytsaurus/flow/examples/waitclickjoin/model/Action.kt
    yt/yt/flow/examples/kotlin/wait_click_join/wait_click_join/src/main/kotlin/tech/ytsaurus/flow/examples/waitclickjoin/model/Hit.kt
    yt/yt/flow/examples/kotlin/wait_click_join/wait_click_join/src/main/kotlin/tech/ytsaurus/flow/examples/waitclickjoin/model/JoinedAction.kt
    yt/yt/flow/examples/kotlin/wait_click_join/wait_click_join/src/test/kotlin/tech/ytsaurus/flow/examples/waitclickjoin/JoinProcessFunctionTest.kt
    yt/yt/flow/examples/kotlin/word_count/wordcount/src/main/kotlin/tech/ytsaurus/flow/examples/wordcount/RunnerMain.kt
    yt/yt/flow/examples/kotlin/word_count/wordcount/src/main/kotlin/tech/ytsaurus/flow/examples/wordcount/WordCountApplication.kt
    yt/yt/flow/examples/kotlin/word_count/wordcount/src/main/kotlin/tech/ytsaurus/flow/examples/wordcount/WordCountContext.kt
    yt/yt/flow/examples/kotlin/word_count/wordcount/src/main/kotlin/tech/ytsaurus/flow/examples/wordcount/WordCountMapper.kt
    yt/yt/flow/examples/python/async_request/__main__.py
    yt/yt/flow/examples/python/async_request/request_processor_function.py
    yt/yt/flow/examples/python/async_request/state_keeper_function.py
    yt/yt/flow/examples/python/retryable_async_request/__main__.py
    yt/yt/flow/examples/python/retryable_async_request/request_processor_function.py
    yt/yt/flow/examples/python/retryable_async_request/state_keeper_function.py
    yt/yt/flow/examples/python/shuffle/__main__.py
    yt/yt/flow/examples/python/shuffle/event_mapper.py
    yt/yt/flow/examples/python/shuffle/event_reducer.py
    yt/yt/flow/examples/python/url_downloader/__main__.py
    yt/yt/flow/examples/python/url_downloader/url_download_function.py
    yt/yt/flow/examples/python/wait_click_join/__main__.py
    yt/yt/flow/examples/python/wait_click_join/join_process_function.py
    yt/yt/flow/examples/python/word_count/__main__.py
    yt/yt/flow/examples/python/word_count/test/pipeline.yson
    yt/yt/flow/examples/python/word_count/test/test_wordcount.py
    yt/yt/flow/examples/python/word_count/test/ya.make
    yt/yt/flow/examples/python/word_count/word_count_mapper.py
)

END()
