# Generated by devtools/yamaker (pypi).

PY23_LIBRARY()

VERSION(0.46)

LICENSE(BSD-3-Clause AND PIL)

NO_LINT()

PY_SRCS(
    TOP_LEVEL
    olefile/__init__.py
    olefile/olefile.py
)

RESOURCE_FILES(
    PREFIX contrib/python/olefile/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
