echo "EXTRA_CONFIG_GENERATOR_OPTIONS = $EXTRA_CONFIG_GENERATOR_OPTIONS"
echo "EXTRA_PUBLISH_CLUSTER_OPTIONS = $EXTRA_PUBLISH_CLUSTER_OPTIONS"

python3.7 /scripts/config_generator.py /data $EXTRA_CONFIG_GENERATOR_OPTIONS
python3.7 /scripts/publish_cluster.py /data $EXTRA_PUBLISH_CLUSTER_OPTIONS
