# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

VERSION(0.4.0)

NO_LINT()

PY_SRCS(
    NAMESPACE yt.packages
    dill/__diff.py
    dill/__info__.py
    dill/__init__.py
    dill/_dill.py
    dill/_objects.py
    dill/_shims.py
    dill/detect.py
    dill/logger.py
    dill/objtypes.py
    dill/pointers.py
    dill/session.py
    dill/settings.py
    dill/source.py
    dill/temp.py
)

RESOURCE_FILES(
    PREFIX yt/python/contrib/python-dill/py3/
    .dist-info/METADATA
    .dist-info/top_level.txt
)

END()
