# Generated by devtools/yamaker.

LIBRARY()

VERSION(18.1.8)

LICENSE(Apache-2.0 WITH LLVM-exception)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

PEERDIR(
    contrib/libs/llvm18
)

ADDINCL(
    contrib/libs/llvm18/lib/Demangle
)

NO_COMPILER_WARNINGS()

NO_UTIL()

SRCS(
    DLangDemangle.cpp
    Demangle.cpp
    ItaniumDemangle.cpp
    MicrosoftDemangle.cpp
    MicrosoftDemangleNodes.cpp
    RustDemangle.cpp
)

END()
