# flake8: noqa
# I'd like to disable only E124 and E128 but flake cannot ignore specific
# warnings for the entire file at the moment.
# [E124] closing bracket does not match visual indentation
# [E128] continuation line under-indented for visual indent

from .common.sensors import ClusterWorkloads

from yt_dashboard_generator.backends.monitoring import MonitoringLabelDashboardParameter
from yt_dashboard_generator.backends.monitoring.sensors import MonitoringExpr
from yt_dashboard_generator.dashboard import Dashboard, Rowset
from yt_dashboard_generator.sensor import MultiSensor
from yt_dashboard_generator.specific_sensors.monitoring import (
    DownsamplingAggregation,
    MonitoringSystemFields,
)
from yt_dashboard_generator.specific_tags.tags import TemplateTag

##################################################################

# Constant terminal nodes for arithmetic.
_K = MonitoringExpr(MonitoringExpr.NodeType.Terminal, 1000)


# Note: YT's SolomonExporter publishes every Counter as a single DGAUGE-rate
# metric named `<sensor>.rate`; the cumulative form is not registered as a
# queryable selector, and the `.rate` series already encodes per-second
# throughput (with restart-aware semantics handled by the exporter). So we
# query the `.rate` form directly and combine the rates arithmetically.
def _cycles_rate(type_val=None):
    s = MonitoringExpr(ClusterWorkloads("yt.cluster_workloads.measurements.cycles_count.rate"))
    return s.value("type", type_val) if type_val else s


def _duration_rate(type_val=None):
    s = MonitoringExpr(ClusterWorkloads("yt.cluster_workloads.measurements.duration_ms.rate"))
    return s.value("type", type_val) if type_val else s


def _iterations_rate(type_val=None):
    s = MonitoringExpr(ClusterWorkloads("yt.cluster_workloads.measurements.iterations.rate"))
    return s.value("type", type_val) if type_val else s


def _bytes_written_rate(type_val=None):
    s = MonitoringExpr(ClusterWorkloads("yt.cluster_workloads.measurements.bytes_written.rate"))
    return s.value("type", type_val) if type_val else s


def _files_written_rate(type_val=None):
    s = MonitoringExpr(ClusterWorkloads("yt.cluster_workloads.measurements.files_written.rate"))
    return s.value("type", type_val) if type_val else s


def build_cluster_reference_workload_performance():
    d = Dashboard()
    d.set_title("Cluster reference workload performance [Autogenerated]")

    # The probe runs once per `period` (typically several minutes), so each
    # underlying counter rate is sparse: zero between cycles, a single
    # spike at cycle completion. Per-bucket AVG-downsampling over a window
    # of `period × 2` smooths each rate inside one bucket so the resulting
    # throughput line is continuous instead of a sequence of disconnected
    # spikes. The window is fixed in milliseconds; 10 minutes covers
    # production probe periods up to ~5 minutes.
    _DOWNSAMPLING_GRID_INTERVAL_MS = 10 * 60 * 1000

    def _smoothed(rowset):
        return (rowset
            .value(MonitoringSystemFields.DownsamplingAggregation, DownsamplingAggregation.Avg)
            .value(MonitoringSystemFields.DownsamplingGridInterval, _DOWNSAMPLING_GRID_INTERVAL_MS))

    # cpu_model lives only on the CPU sensors, so the selector is bound here,
    # per sensor, rather than dashboard-wide: a global cpu_model selector would
    # match nothing on the disk panels (they have no such label) and blank them.
    #
    # The dashboard parameter is named probe_cpu_model, not cpu_model: the CPU
    # panels alias each line as "{{cpu_model}}" to interpolate the series
    # label, and a parameter with the same name would be substituted into that
    # alias first (naming every line "*" when the dropdown is at its default).
    def _by_cpu_model(expr):
        return expr.value("cpu_model", TemplateTag("probe_cpu_model"))

    # The probe's counters are scraped continuously, so the per-model .rate
    # series are dense: zero between that model's cycles, a spike when a cycle
    # lands on it. A per-bucket iterations/duration ratio is therefore
    # 0/0 = NaN in every bucket without a measurement, and the renderer breaks
    # the line at each NaN — the per-model lines degrade into dots. Summing
    # both operands over a trailing window first keeps the denominator nonzero
    # everywhere the model was measured within the last |window|, so the ratio
    # is defined at every bucket and the line is continuous. The window must
    # exceed the per-model measurement interval (probe period × number of CPU
    # models in the cluster), else the gaps come back; it also sets how much
    # history one point averages.
    #
    # Without a window the ratio is the raw per-bucket value: mostly dots, one
    # per actual measurement at its exact time — deliberately kept as the
    # unsmoothed view.
    #
    # The alias names each line by its CPU model so the legend stays readable.
    def _cpu_ops_expr(window=None):
        iterations = _by_cpu_model(_iterations_rate("cpu"))
        duration = _by_cpu_model(_duration_rate("cpu"))
        if window is not None:
            iterations = iterations.moving_sum(window)
            duration = duration.moving_sum(window)
        return ((iterations / duration) * _K).drop_nan().alias("{{cpu_model}}")

    _cpu_ops_description = (
        "What op/s means: "
        "https://a.yandex-team.ru/arcadia/yt/internal/cluster_workloads/"
        "benchmark_probe/job/lib/README.md"
    )

    # Row 1: CPU throughput — smoothed trend, sensitive window, raw samples.
    d.add(_smoothed(Rowset()
        .stack(False)
        .min(0))
        .row()
            .cell(
                "CPU op/s (2h window)",
                _cpu_ops_expr("2h"),
                yaxis_label="op/s",
                display_legend=True,
                description=_cpu_ops_description,
            )
            .cell(
                "CPU op/s (1h window)",
                _cpu_ops_expr("1h"),
                yaxis_label="op/s",
                display_legend=True,
                description=_cpu_ops_description,
            )
            .cell(
                "CPU op/s (raw samples)",
                _cpu_ops_expr(),
                yaxis_label="op/s",
                display_legend=True,
                description=_cpu_ops_description,
            )
    )

    # Row 2: disk throughput (big-file and many-files).
    d.add(_smoothed(Rowset()
        .stack(False)
        .min(0))
        .row()
            .cell(
                "Big-file disk write",
                (
                    (
                        _bytes_written_rate("big_file_disk_io")
                        / _duration_rate("big_file_disk_io")
                    ) * _K
                ).unit("UNIT_BYTES_SI_PER_SECOND"),
                display_legend=False,
            )
            .cell(
                "Many-files files/s",
                (
                    _files_written_rate("many_files_disk_io")
                    / _duration_rate("many_files_disk_io")
                ) * _K,
                yaxis_label="files/s",
                display_legend=False,
            )
            .cell(
                "Many-files disk write",
                (
                    (
                        _bytes_written_rate("many_files_disk_io")
                        / _duration_rate("many_files_disk_io")
                    ) * _K
                ).unit("UNIT_BYTES_SI_PER_SECOND"),
                display_legend=False,
            )
    )

    # Row 3: Liveness and average cycle time.
    d.add(_smoothed(Rowset()
        .stack(False)
        .min(0))
        .row()
            .cell(
                "Liveness — cycles per second",
                MultiSensor(
                    # series_sum("type") collapses the per-cpu_model CPU series
                    # back into a single line per workload type.
                    _cycles_rate().all("type").series_sum("type").alias("{{type}}"),
                ),
                yaxis_label="cycles/s",
                display_legend=True,
            )
            .cell(
                "Avg cycle time",
                (
                    _duration_rate().all("type").series_sum("type")
                    / _cycles_rate().all("type").series_sum("type")
                ).alias("{{type}}"),
                yaxis_label="ms/cycle",
                display_legend=True,
            )
    )

    # First arg of MonitoringLabelDashboardParameter is the Monium project id
    # (not the Solomon `service` tag); for any YT metric that's "yt".
    # `selectors` restricts the parameter dropdown to label values seen on
    # cluster_workloads sensors only — without it the dropdown enumerates
    # the entire `yt` project's labels (e.g. `pool_tree=default` from the
    # scheduler), which produces empty queries for our dashboard.
    _service_selector = "{service='cluster_workloads'}"
    d.add_parameter(
        "yt_cluster",
        "yt_cluster",
        MonitoringLabelDashboardParameter("yt", "yt_cluster", "*", selectors=_service_selector),
        backends=["monitoring"],
    )
    d.add_parameter(
        "pool_tree",
        "pool_tree",
        MonitoringLabelDashboardParameter("yt", "pool_tree", "*", selectors=_service_selector),
        backends=["monitoring"],
    )
    d.add_parameter(
        "workload",
        "workload",
        MonitoringLabelDashboardParameter("yt", "workload", "*", selectors=_service_selector),
        backends=["monitoring"],
    )
    # cpu_model exists only on the CPU sensors; the dropdown enumerates the
    # models seen there. It is bound per-sensor (see _by_cpu_model), not via a
    # dashboard-wide d.value, so the disk panels stay unaffected. The parameter
    # name deliberately differs from the label name — see _by_cpu_model.
    d.add_parameter(
        "probe_cpu_model",
        "cpu_model",
        MonitoringLabelDashboardParameter("yt", "cpu_model", "*", selectors=_service_selector),
        backends=["monitoring"],
    )

    d.value("yt_cluster", TemplateTag("yt_cluster"))
    d.value("pool_tree",  TemplateTag("pool_tree"))
    d.value("workload",   TemplateTag("workload"))
    # The Solomon-side `cluster` tag is the launcher binary's deploy cluster
    # (e.g. `benchmark_probe`), distinct from the YT cluster being
    # benchmarked (carried in the per-sensor `yt_cluster` tag). The Monium
    # YtTagPostprocessor unconditionally injects `cluster=...` into every
    # query via setdefault — pinning it to "*" here suppresses the
    # `{{cluster}}` template substitution and avoids a redundant dashboard
    # parameter.
    d.value("cluster", "*")
    # YT's SolomonExporter tags every point with `host=<host>` and
    # `yt_aggr=1` (the host-aggregated time series). Selectors that don't
    # mention these tags return empty even when matching points exist,
    # so we pin them on the dashboard.
    d.value("host", "*")
    d.value("yt_aggr", "1")

    d.set_monitoring_serializer_options(dict(default_row_height=9))

    return d
