# Generated by devtools/yamaker from nixpkgs 24.05.

LIBRARY()

LICENSE(BSD-3-Clause)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(2026-05-01)

ORIGINAL_SOURCE(https://github.com/mreineck/pocketfft/archive/5f27d5a8f51c5c25030cb22abf434decc9faf0ff.tar.gz)

END()
