SELECT *
FROM `$nomenclature`
SAMPLE 0.5; -- take random sample from given input, in this case half of the table;
            -- does not guarantee that random is completely fair, but tries to be
            -- close to that

SELECT *
FROM `$nomenclature`
TABLESAMPLE BERNOULLI(50.0) REPEATABLE(1); -- this syntax is SQL compliant and
                                           -- optional REPEATABLE clause allows
                                           -- to make the result stable from run
                                           -- to run

SELECT *
FROM `$nomenclature`
WHERE Digest::MurMurHash(name) % 100 < 50; -- allows to keep only the rows
                                           -- with half of values of "name" column;
                                           -- result is stable as it is based on hash;

SELECT *
FROM `$nomenclature`
WHERE RANDOM(TableRecordIndex()) < 0.5; -- This basically does the same as SAMPLE clause
                                   -- and works a bit slower, but it demonstrates
                                   -- important builtins and concepts:
                                   --
                                   -- RANDOM builtin returns [0.0;1.0) so this
                                   -- chooses 50% of rows giving
                                   -- each one a fair chance. The downsides are that
                                   -- the scan of the whole table is performed and
                                   -- results will vary from run to run.
                                   -- Therefore it is a good idea to run this once,
                                   -- save the result to a temporary table and
                                   -- test the query against it.
                                   --
                                   -- To avoid caching of a value generated by RANDOM
                                   -- it should be supplied with some non-constant
                                   -- argument. The argument's value is ignored.
                                   --
                                   -- TableRecordIndex() builtin returns current
                                   -- row number in source table (starting with 1)
                                   -- if it is provided by backend or 0 otherwise.
