LIBRARY()

SRCS(
    actor_persqueue_client_iface.h
    blob.cpp
    cluster_tracker.cpp
    event_helpers.cpp
    fetch_request_actor.cpp
    header.cpp
    heartbeat.cpp
    metering_sink.cpp
    mirrorer.cpp
    mirrorer.h
    ownerinfo.cpp
    partition_init.cpp
    partition_monitoring.cpp
    partition_read.cpp
    partition_sourcemanager.cpp
    partition_write.cpp
    partition.cpp
    percentile_counter.cpp
    pq.cpp
    pq_database.cpp
    pq_impl.cpp
    pq_l2_cache.cpp
    pq_rl_helpers.cpp
    quota_tracker.cpp
    read_balancer.cpp
    account_read_quoter.cpp
    read_quoter.cpp
    sourceid.cpp
    subscriber.cpp
    transaction.cpp
    type_codecs_defs.cpp
    user_info.cpp
    utils.cpp
    write_meta.cpp
    microseconds_sliding_window.cpp
)

GENERATE_ENUM_SERIALIZATION(sourceid.h)

PEERDIR(
    library/cpp/actors/core
    library/cpp/html/pcdata
    library/cpp/json
    contrib/ydb/core/base
    contrib/ydb/core/engine/minikql
    contrib/ydb/core/keyvalue
    contrib/ydb/core/kqp/common
    contrib/ydb/core/metering
    contrib/ydb/core/persqueue/codecs
    contrib/ydb/core/persqueue/config
    contrib/ydb/core/persqueue/events
    contrib/ydb/core/persqueue/partition_key_range
    contrib/ydb/core/persqueue/writer
    contrib/ydb/core/protos
    contrib/ydb/library/logger
    contrib/ydb/library/persqueue/counter_time_keeper
    contrib/ydb/library/persqueue/topic_parser
    contrib/ydb/public/lib/base
    contrib/ydb/public/sdk/cpp/client/ydb_persqueue_core
)

END()

RECURSE_FOR_TESTS(
    ut
    ut/slow
)
