SET(CODEGEN yt/yt/orm/example/codegen)

SET(CLIENT_OBJECTS_DIR yt/yt/orm/example/client/objects)
SET(CLIENT_OBJECTS_OUTDIR ${CLIENT_OBJECTS_DIR}/autogen)
SET(CLIENT_PROTO_DIR yt/yt/orm/example/client/proto)
SET(CLIENT_DATAMODEL_DIR yt/yt/orm/example/client/proto/data_model)
SET(CLIENT_DATAMODEL_OUTDIR ${CLIENT_DATAMODEL_DIR}/autogen)
SET(CLIENT_DATAMODEL_FILENAME schema)
SET(PROTO_API_DIR ${CLIENT_PROTO_DIR}/api)
