# Generated by devtools/yamaker.

LIBRARY()

LICENSE(
    Apache-2.0 AND
    BSL-1.0 AND
    CC0-1.0 AND
    MIT
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(24.8.14.39)

PEERDIR(
    contrib/clickhouse/base/poco/JSON
    contrib/clickhouse/base/poco/XML
)

ADDINCL(
    GLOBAL contrib/clickhouse/base/poco/Util/include
    contrib/clickhouse/base/poco/Foundation/include
    contrib/clickhouse/base/poco/JSON/include
    contrib/clickhouse/base/poco/XML/include
)

NO_COMPILER_WARNINGS()

NO_UTIL()

IF (OS_DARWIN)
    CFLAGS(
        GLOBAL -DOS_DARWIN
    )
ELSEIF (OS_LINUX)
    CFLAGS(
        GLOBAL -DOS_LINUX
    )
ENDIF()

CFLAGS(
    -DPOCO_ENABLE_CPP11
    -DPOCO_OS_FAMILY_UNIX
    -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS
    -D_LIBUNWIND_IS_NATIVE_ONLY
)

SRCS(
    src/AbstractConfiguration.cpp
    src/Application.cpp
    src/ConfigurationView.cpp
    src/FilesystemConfiguration.cpp
    src/HelpFormatter.cpp
    src/IniFileConfiguration.cpp
    src/IntValidator.cpp
    src/JSONConfiguration.cpp
    src/LayeredConfiguration.cpp
    src/LoggingConfigurator.cpp
    src/LoggingSubsystem.cpp
    src/MapConfiguration.cpp
    src/Option.cpp
    src/OptionCallback.cpp
    src/OptionException.cpp
    src/OptionProcessor.cpp
    src/OptionSet.cpp
    src/PropertyFileConfiguration.cpp
    src/RegExpValidator.cpp
    src/ServerApplication.cpp
    src/Subsystem.cpp
    src/SystemConfiguration.cpp
    src/Timer.cpp
    src/TimerTask.cpp
    src/Validator.cpp
    src/XMLConfiguration.cpp
)

END()
