from enum import StrEnum


class JobStatus(StrEnum):
    ABORTED = "TASK_STATUS_ABORTED"
    FINISHED = "TASK_STATUS_FINISHED"
    NEW = "TASK_STATUS_NEW"
    PENDING = "TASK_STATUS_PENDING"
    FAULT = "TASK_STATUS_FAULT"
    UNSPECIFIED = "TASK_STATUS_UNSPECIFIED"


class TaskPriority(StrEnum):
    NORMAL = "TASK_PRIORITY_NORMAL"
    HIGH = "TASK_PRIORITY_HIGH"
    CRITICAL = "TASK_PRIORITY_CRITICAL"
