# Console appender
appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{YYYY-MM-ddTHH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n

# Rolling file appender.
appender.rolling.type = RollingFile
appender.rolling.name = File
appender.rolling.fileName = ${env:YT_FLOW_COMPANION_LOG_FILE:-./logs/companion.log}
appender.rolling.filePattern = ${env:YT_FLOW_COMPANION_LOG_FILE:-./logs/companion.log}.%d{yyyy-MM-dd}-%i.log.gz
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{YYYY-MM-ddTHH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
appender.rolling.policies.type = Policies
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.time.interval = 1
appender.rolling.policies.time.modulate = true
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.delete.type = Delete
appender.rolling.strategy.delete.basePath = ${env:YT_FLOW_COMPANION_LOG_DIR:-./logs}
appender.rolling.strategy.delete.maxDepth = 1
appender.rolling.strategy.delete.ifLastModified.type = IfLastModified
appender.rolling.strategy.delete.ifLastModified.age = 2d

# Configuration of `debug` logger, turn on logs of `tech.ytsaurus` package
logger.ytsaurus.name = tech.ytsaurus
logger.ytsaurus.level = debug
logger.ytsaurus.appenderRef.appender.ref = ${env:YT_FLOW_COMPANION_LOGGER_TYPE:-Console}

# Spring logging.
logger.spring.name = org.springframework
logger.spring.level = info
logger.spring.appenderRef.appender.ref = ${env:YT_FLOW_COMPANION_LOGGER_TYPE:-Console}

# Turn off additional logging ytsaurus events via rootLogger
logger.ytsaurus.additivity = false

# Also read official documentation of log4j2:
# https://logging.apache.org/log4j/2.x/manual/configuration.html
