RECURSE(
    all
    exec
    tools
    lib
    log_tailer
    master
    master_cache
    multidaemon
    node
    clock_server
    discovery_server
    controller_agent
    http_proxy
    job_proxy
    kafka_proxy
    queue_agent
    query_tracker
    rpc_proxy
    scheduler
    sequoia_reconstructor
    timestamp_provider
    cell_balancer
    tablet_balancer
    cypress_proxy
    tcp_proxy
    replicated_table_tracker
    offshore_data_gateway
)
