PROGRAM(@UT_PRJNAME@${UT_SUFFIX})
SRCS(
    #${ARCADIA_ROOT}/unittest/lib/utmain.cpp
    @UT_SRCS@
)

PEERDIR(
    library/unittest
)

SET(USE_J_ALLOCATOR no)
SET(USE_GOOGLE_ALLOCATOR no)
SET(USE_LF_ALLOCATOR no)

DEBUGMESSAGE(3 "-- unittest: [@UT_PRJNAME @${UT_SUFFIX}], srcs: ${SRCS}")

CFLAGS(@CFLAGS@)
CXXFLAGS(@CXXFLAGS@)
SET(DTMK_I @DTMK_I@)
@UT_PERDIR_PEERDIR@
@UT_DEPENDS@

IF (UT_EXCLUDE_FROM_ALL)
    EXCLUDE_FROM_ALL()
ENDIF (UT_EXCLUDE_FROM_ALL)

ADD_DEPENDENCIES(all_ut @UT_PRJNAME@${UT_SUFFIX})

END()
