// WARNING: This file was auto-generated.
// Please, consider incorporating any changes into the generator.

// Generated on Wed Dec  9 14:20:20 2015.


#pragma once

/*!
  \internal
*/

#ifndef PREPROCESSOR_GEN_H_
#error "Direct inclusion of this file is not allowed, include preprocessor.h"
// For the sake of sane code completion.
#include "preprocessor.h"
#endif
#undef PREPROCESSOR_GEN_H_

////////////////////////////////////////////////////////////////////////////////
#define PP_COUNT_IMPL(...) PP_CONCAT(PP_COUNT_CONST_, \
    PP_COUNT_IMPL_0 __VA_ARGS__)
#define PP_COUNT_CONST_PP_COUNT_IMPL_0 0
#define PP_COUNT_CONST_PP_COUNT_IMPL_1 1
#define PP_COUNT_CONST_PP_COUNT_IMPL_2 2
#define PP_COUNT_CONST_PP_COUNT_IMPL_3 3
#define PP_COUNT_CONST_PP_COUNT_IMPL_4 4
#define PP_COUNT_CONST_PP_COUNT_IMPL_5 5
#define PP_COUNT_CONST_PP_COUNT_IMPL_6 6
#define PP_COUNT_CONST_PP_COUNT_IMPL_7 7
#define PP_COUNT_CONST_PP_COUNT_IMPL_8 8
#define PP_COUNT_CONST_PP_COUNT_IMPL_9 9
#define PP_COUNT_CONST_PP_COUNT_IMPL_10 10
#define PP_COUNT_CONST_PP_COUNT_IMPL_11 11
#define PP_COUNT_CONST_PP_COUNT_IMPL_12 12
#define PP_COUNT_CONST_PP_COUNT_IMPL_13 13
#define PP_COUNT_CONST_PP_COUNT_IMPL_14 14
#define PP_COUNT_CONST_PP_COUNT_IMPL_15 15
#define PP_COUNT_CONST_PP_COUNT_IMPL_16 16
#define PP_COUNT_CONST_PP_COUNT_IMPL_17 17
#define PP_COUNT_CONST_PP_COUNT_IMPL_18 18
#define PP_COUNT_CONST_PP_COUNT_IMPL_19 19
#define PP_COUNT_CONST_PP_COUNT_IMPL_20 20
#define PP_COUNT_CONST_PP_COUNT_IMPL_21 21
#define PP_COUNT_CONST_PP_COUNT_IMPL_22 22
#define PP_COUNT_CONST_PP_COUNT_IMPL_23 23
#define PP_COUNT_CONST_PP_COUNT_IMPL_24 24
#define PP_COUNT_CONST_PP_COUNT_IMPL_25 25
#define PP_COUNT_CONST_PP_COUNT_IMPL_26 26
#define PP_COUNT_CONST_PP_COUNT_IMPL_27 27
#define PP_COUNT_CONST_PP_COUNT_IMPL_28 28
#define PP_COUNT_CONST_PP_COUNT_IMPL_29 29
#define PP_COUNT_CONST_PP_COUNT_IMPL_30 30
#define PP_COUNT_CONST_PP_COUNT_IMPL_31 31
#define PP_COUNT_CONST_PP_COUNT_IMPL_32 32
#define PP_COUNT_CONST_PP_COUNT_IMPL_33 33
#define PP_COUNT_CONST_PP_COUNT_IMPL_34 34
#define PP_COUNT_CONST_PP_COUNT_IMPL_35 35
#define PP_COUNT_CONST_PP_COUNT_IMPL_36 36
#define PP_COUNT_CONST_PP_COUNT_IMPL_37 37
#define PP_COUNT_CONST_PP_COUNT_IMPL_38 38
#define PP_COUNT_CONST_PP_COUNT_IMPL_39 39
#define PP_COUNT_CONST_PP_COUNT_IMPL_40 40
#define PP_COUNT_CONST_PP_COUNT_IMPL_41 41
#define PP_COUNT_CONST_PP_COUNT_IMPL_42 42
#define PP_COUNT_CONST_PP_COUNT_IMPL_43 43
#define PP_COUNT_CONST_PP_COUNT_IMPL_44 44
#define PP_COUNT_CONST_PP_COUNT_IMPL_45 45
#define PP_COUNT_CONST_PP_COUNT_IMPL_46 46
#define PP_COUNT_CONST_PP_COUNT_IMPL_47 47
#define PP_COUNT_CONST_PP_COUNT_IMPL_48 48
#define PP_COUNT_CONST_PP_COUNT_IMPL_49 49
#define PP_COUNT_CONST_PP_COUNT_IMPL_50 50
#define PP_COUNT_CONST_PP_COUNT_IMPL_51 51
#define PP_COUNT_CONST_PP_COUNT_IMPL_52 52
#define PP_COUNT_CONST_PP_COUNT_IMPL_53 53
#define PP_COUNT_CONST_PP_COUNT_IMPL_54 54
#define PP_COUNT_CONST_PP_COUNT_IMPL_55 55
#define PP_COUNT_CONST_PP_COUNT_IMPL_56 56
#define PP_COUNT_CONST_PP_COUNT_IMPL_57 57
#define PP_COUNT_CONST_PP_COUNT_IMPL_58 58
#define PP_COUNT_CONST_PP_COUNT_IMPL_59 59
#define PP_COUNT_CONST_PP_COUNT_IMPL_60 60
#define PP_COUNT_CONST_PP_COUNT_IMPL_61 61
#define PP_COUNT_CONST_PP_COUNT_IMPL_62 62
#define PP_COUNT_CONST_PP_COUNT_IMPL_63 63
#define PP_COUNT_CONST_PP_COUNT_IMPL_64 64
#define PP_COUNT_CONST_PP_COUNT_IMPL_65 65
#define PP_COUNT_CONST_PP_COUNT_IMPL_66 66
#define PP_COUNT_CONST_PP_COUNT_IMPL_67 67
#define PP_COUNT_CONST_PP_COUNT_IMPL_68 68
#define PP_COUNT_CONST_PP_COUNT_IMPL_69 69
#define PP_COUNT_CONST_PP_COUNT_IMPL_70 70
#define PP_COUNT_CONST_PP_COUNT_IMPL_71 71
#define PP_COUNT_CONST_PP_COUNT_IMPL_72 72
#define PP_COUNT_CONST_PP_COUNT_IMPL_73 73
#define PP_COUNT_CONST_PP_COUNT_IMPL_74 74
#define PP_COUNT_CONST_PP_COUNT_IMPL_75 75
#define PP_COUNT_CONST_PP_COUNT_IMPL_76 76
#define PP_COUNT_CONST_PP_COUNT_IMPL_77 77
#define PP_COUNT_CONST_PP_COUNT_IMPL_78 78
#define PP_COUNT_CONST_PP_COUNT_IMPL_79 79
#define PP_COUNT_CONST_PP_COUNT_IMPL_80 80
#define PP_COUNT_CONST_PP_COUNT_IMPL_81 81
#define PP_COUNT_CONST_PP_COUNT_IMPL_82 82
#define PP_COUNT_CONST_PP_COUNT_IMPL_83 83
#define PP_COUNT_CONST_PP_COUNT_IMPL_84 84
#define PP_COUNT_CONST_PP_COUNT_IMPL_85 85
#define PP_COUNT_CONST_PP_COUNT_IMPL_86 86
#define PP_COUNT_CONST_PP_COUNT_IMPL_87 87
#define PP_COUNT_CONST_PP_COUNT_IMPL_88 88
#define PP_COUNT_CONST_PP_COUNT_IMPL_89 89
#define PP_COUNT_CONST_PP_COUNT_IMPL_90 90
#define PP_COUNT_CONST_PP_COUNT_IMPL_91 91
#define PP_COUNT_CONST_PP_COUNT_IMPL_92 92
#define PP_COUNT_CONST_PP_COUNT_IMPL_93 93
#define PP_COUNT_CONST_PP_COUNT_IMPL_94 94
#define PP_COUNT_CONST_PP_COUNT_IMPL_95 95
#define PP_COUNT_CONST_PP_COUNT_IMPL_96 96
#define PP_COUNT_CONST_PP_COUNT_IMPL_97 97
#define PP_COUNT_CONST_PP_COUNT_IMPL_98 98
#define PP_COUNT_CONST_PP_COUNT_IMPL_99 99
#define PP_COUNT_IMPL_0(_) PP_COUNT_IMPL_1
#define PP_COUNT_IMPL_1(_) PP_COUNT_IMPL_2
#define PP_COUNT_IMPL_2(_) PP_COUNT_IMPL_3
#define PP_COUNT_IMPL_3(_) PP_COUNT_IMPL_4
#define PP_COUNT_IMPL_4(_) PP_COUNT_IMPL_5
#define PP_COUNT_IMPL_5(_) PP_COUNT_IMPL_6
#define PP_COUNT_IMPL_6(_) PP_COUNT_IMPL_7
#define PP_COUNT_IMPL_7(_) PP_COUNT_IMPL_8
#define PP_COUNT_IMPL_8(_) PP_COUNT_IMPL_9
#define PP_COUNT_IMPL_9(_) PP_COUNT_IMPL_10
#define PP_COUNT_IMPL_10(_) PP_COUNT_IMPL_11
#define PP_COUNT_IMPL_11(_) PP_COUNT_IMPL_12
#define PP_COUNT_IMPL_12(_) PP_COUNT_IMPL_13
#define PP_COUNT_IMPL_13(_) PP_COUNT_IMPL_14
#define PP_COUNT_IMPL_14(_) PP_COUNT_IMPL_15
#define PP_COUNT_IMPL_15(_) PP_COUNT_IMPL_16
#define PP_COUNT_IMPL_16(_) PP_COUNT_IMPL_17
#define PP_COUNT_IMPL_17(_) PP_COUNT_IMPL_18
#define PP_COUNT_IMPL_18(_) PP_COUNT_IMPL_19
#define PP_COUNT_IMPL_19(_) PP_COUNT_IMPL_20
#define PP_COUNT_IMPL_20(_) PP_COUNT_IMPL_21
#define PP_COUNT_IMPL_21(_) PP_COUNT_IMPL_22
#define PP_COUNT_IMPL_22(_) PP_COUNT_IMPL_23
#define PP_COUNT_IMPL_23(_) PP_COUNT_IMPL_24
#define PP_COUNT_IMPL_24(_) PP_COUNT_IMPL_25
#define PP_COUNT_IMPL_25(_) PP_COUNT_IMPL_26
#define PP_COUNT_IMPL_26(_) PP_COUNT_IMPL_27
#define PP_COUNT_IMPL_27(_) PP_COUNT_IMPL_28
#define PP_COUNT_IMPL_28(_) PP_COUNT_IMPL_29
#define PP_COUNT_IMPL_29(_) PP_COUNT_IMPL_30
#define PP_COUNT_IMPL_30(_) PP_COUNT_IMPL_31
#define PP_COUNT_IMPL_31(_) PP_COUNT_IMPL_32
#define PP_COUNT_IMPL_32(_) PP_COUNT_IMPL_33
#define PP_COUNT_IMPL_33(_) PP_COUNT_IMPL_34
#define PP_COUNT_IMPL_34(_) PP_COUNT_IMPL_35
#define PP_COUNT_IMPL_35(_) PP_COUNT_IMPL_36
#define PP_COUNT_IMPL_36(_) PP_COUNT_IMPL_37
#define PP_COUNT_IMPL_37(_) PP_COUNT_IMPL_38
#define PP_COUNT_IMPL_38(_) PP_COUNT_IMPL_39
#define PP_COUNT_IMPL_39(_) PP_COUNT_IMPL_40
#define PP_COUNT_IMPL_40(_) PP_COUNT_IMPL_41
#define PP_COUNT_IMPL_41(_) PP_COUNT_IMPL_42
#define PP_COUNT_IMPL_42(_) PP_COUNT_IMPL_43
#define PP_COUNT_IMPL_43(_) PP_COUNT_IMPL_44
#define PP_COUNT_IMPL_44(_) PP_COUNT_IMPL_45
#define PP_COUNT_IMPL_45(_) PP_COUNT_IMPL_46
#define PP_COUNT_IMPL_46(_) PP_COUNT_IMPL_47
#define PP_COUNT_IMPL_47(_) PP_COUNT_IMPL_48
#define PP_COUNT_IMPL_48(_) PP_COUNT_IMPL_49
#define PP_COUNT_IMPL_49(_) PP_COUNT_IMPL_50
#define PP_COUNT_IMPL_50(_) PP_COUNT_IMPL_51
#define PP_COUNT_IMPL_51(_) PP_COUNT_IMPL_52
#define PP_COUNT_IMPL_52(_) PP_COUNT_IMPL_53
#define PP_COUNT_IMPL_53(_) PP_COUNT_IMPL_54
#define PP_COUNT_IMPL_54(_) PP_COUNT_IMPL_55
#define PP_COUNT_IMPL_55(_) PP_COUNT_IMPL_56
#define PP_COUNT_IMPL_56(_) PP_COUNT_IMPL_57
#define PP_COUNT_IMPL_57(_) PP_COUNT_IMPL_58
#define PP_COUNT_IMPL_58(_) PP_COUNT_IMPL_59
#define PP_COUNT_IMPL_59(_) PP_COUNT_IMPL_60
#define PP_COUNT_IMPL_60(_) PP_COUNT_IMPL_61
#define PP_COUNT_IMPL_61(_) PP_COUNT_IMPL_62
#define PP_COUNT_IMPL_62(_) PP_COUNT_IMPL_63
#define PP_COUNT_IMPL_63(_) PP_COUNT_IMPL_64
#define PP_COUNT_IMPL_64(_) PP_COUNT_IMPL_65
#define PP_COUNT_IMPL_65(_) PP_COUNT_IMPL_66
#define PP_COUNT_IMPL_66(_) PP_COUNT_IMPL_67
#define PP_COUNT_IMPL_67(_) PP_COUNT_IMPL_68
#define PP_COUNT_IMPL_68(_) PP_COUNT_IMPL_69
#define PP_COUNT_IMPL_69(_) PP_COUNT_IMPL_70
#define PP_COUNT_IMPL_70(_) PP_COUNT_IMPL_71
#define PP_COUNT_IMPL_71(_) PP_COUNT_IMPL_72
#define PP_COUNT_IMPL_72(_) PP_COUNT_IMPL_73
#define PP_COUNT_IMPL_73(_) PP_COUNT_IMPL_74
#define PP_COUNT_IMPL_74(_) PP_COUNT_IMPL_75
#define PP_COUNT_IMPL_75(_) PP_COUNT_IMPL_76
#define PP_COUNT_IMPL_76(_) PP_COUNT_IMPL_77
#define PP_COUNT_IMPL_77(_) PP_COUNT_IMPL_78
#define PP_COUNT_IMPL_78(_) PP_COUNT_IMPL_79
#define PP_COUNT_IMPL_79(_) PP_COUNT_IMPL_80
#define PP_COUNT_IMPL_80(_) PP_COUNT_IMPL_81
#define PP_COUNT_IMPL_81(_) PP_COUNT_IMPL_82
#define PP_COUNT_IMPL_82(_) PP_COUNT_IMPL_83
#define PP_COUNT_IMPL_83(_) PP_COUNT_IMPL_84
#define PP_COUNT_IMPL_84(_) PP_COUNT_IMPL_85
#define PP_COUNT_IMPL_85(_) PP_COUNT_IMPL_86
#define PP_COUNT_IMPL_86(_) PP_COUNT_IMPL_87
#define PP_COUNT_IMPL_87(_) PP_COUNT_IMPL_88
#define PP_COUNT_IMPL_88(_) PP_COUNT_IMPL_89
#define PP_COUNT_IMPL_89(_) PP_COUNT_IMPL_90
#define PP_COUNT_IMPL_90(_) PP_COUNT_IMPL_91
#define PP_COUNT_IMPL_91(_) PP_COUNT_IMPL_92
#define PP_COUNT_IMPL_92(_) PP_COUNT_IMPL_93
#define PP_COUNT_IMPL_93(_) PP_COUNT_IMPL_94
#define PP_COUNT_IMPL_94(_) PP_COUNT_IMPL_95
#define PP_COUNT_IMPL_95(_) PP_COUNT_IMPL_96
#define PP_COUNT_IMPL_96(_) PP_COUNT_IMPL_97
#define PP_COUNT_IMPL_97(_) PP_COUNT_IMPL_98
#define PP_COUNT_IMPL_98(_) PP_COUNT_IMPL_99
#define PP_COUNT_IMPL_99(_) PP_COUNT_IMPL_100

////////////////////////////////////////////////////////////////////////////////
#define PP_KILL_IMPL(seq, index) PP_CONCAT(PP_KILL_IMPL_, index) seq
#define PP_KILL_IMPL_0
#define PP_KILL_IMPL_1(_) PP_KILL_IMPL_0
#define PP_KILL_IMPL_2(_) PP_KILL_IMPL_1
#define PP_KILL_IMPL_3(_) PP_KILL_IMPL_2
#define PP_KILL_IMPL_4(_) PP_KILL_IMPL_3
#define PP_KILL_IMPL_5(_) PP_KILL_IMPL_4
#define PP_KILL_IMPL_6(_) PP_KILL_IMPL_5
#define PP_KILL_IMPL_7(_) PP_KILL_IMPL_6
#define PP_KILL_IMPL_8(_) PP_KILL_IMPL_7
#define PP_KILL_IMPL_9(_) PP_KILL_IMPL_8
#define PP_KILL_IMPL_10(_) PP_KILL_IMPL_9
#define PP_KILL_IMPL_11(_) PP_KILL_IMPL_10
#define PP_KILL_IMPL_12(_) PP_KILL_IMPL_11
#define PP_KILL_IMPL_13(_) PP_KILL_IMPL_12
#define PP_KILL_IMPL_14(_) PP_KILL_IMPL_13
#define PP_KILL_IMPL_15(_) PP_KILL_IMPL_14
#define PP_KILL_IMPL_16(_) PP_KILL_IMPL_15
#define PP_KILL_IMPL_17(_) PP_KILL_IMPL_16
#define PP_KILL_IMPL_18(_) PP_KILL_IMPL_17
#define PP_KILL_IMPL_19(_) PP_KILL_IMPL_18
#define PP_KILL_IMPL_20(_) PP_KILL_IMPL_19
#define PP_KILL_IMPL_21(_) PP_KILL_IMPL_20
#define PP_KILL_IMPL_22(_) PP_KILL_IMPL_21
#define PP_KILL_IMPL_23(_) PP_KILL_IMPL_22
#define PP_KILL_IMPL_24(_) PP_KILL_IMPL_23
#define PP_KILL_IMPL_25(_) PP_KILL_IMPL_24
#define PP_KILL_IMPL_26(_) PP_KILL_IMPL_25
#define PP_KILL_IMPL_27(_) PP_KILL_IMPL_26
#define PP_KILL_IMPL_28(_) PP_KILL_IMPL_27
#define PP_KILL_IMPL_29(_) PP_KILL_IMPL_28
#define PP_KILL_IMPL_30(_) PP_KILL_IMPL_29
#define PP_KILL_IMPL_31(_) PP_KILL_IMPL_30
#define PP_KILL_IMPL_32(_) PP_KILL_IMPL_31
#define PP_KILL_IMPL_33(_) PP_KILL_IMPL_32
#define PP_KILL_IMPL_34(_) PP_KILL_IMPL_33
#define PP_KILL_IMPL_35(_) PP_KILL_IMPL_34
#define PP_KILL_IMPL_36(_) PP_KILL_IMPL_35
#define PP_KILL_IMPL_37(_) PP_KILL_IMPL_36
#define PP_KILL_IMPL_38(_) PP_KILL_IMPL_37
#define PP_KILL_IMPL_39(_) PP_KILL_IMPL_38
#define PP_KILL_IMPL_40(_) PP_KILL_IMPL_39
#define PP_KILL_IMPL_41(_) PP_KILL_IMPL_40
#define PP_KILL_IMPL_42(_) PP_KILL_IMPL_41
#define PP_KILL_IMPL_43(_) PP_KILL_IMPL_42
#define PP_KILL_IMPL_44(_) PP_KILL_IMPL_43
#define PP_KILL_IMPL_45(_) PP_KILL_IMPL_44
#define PP_KILL_IMPL_46(_) PP_KILL_IMPL_45
#define PP_KILL_IMPL_47(_) PP_KILL_IMPL_46
#define PP_KILL_IMPL_48(_) PP_KILL_IMPL_47
#define PP_KILL_IMPL_49(_) PP_KILL_IMPL_48
#define PP_KILL_IMPL_50(_) PP_KILL_IMPL_49
#define PP_KILL_IMPL_51(_) PP_KILL_IMPL_50
#define PP_KILL_IMPL_52(_) PP_KILL_IMPL_51
#define PP_KILL_IMPL_53(_) PP_KILL_IMPL_52
#define PP_KILL_IMPL_54(_) PP_KILL_IMPL_53
#define PP_KILL_IMPL_55(_) PP_KILL_IMPL_54
#define PP_KILL_IMPL_56(_) PP_KILL_IMPL_55
#define PP_KILL_IMPL_57(_) PP_KILL_IMPL_56
#define PP_KILL_IMPL_58(_) PP_KILL_IMPL_57
#define PP_KILL_IMPL_59(_) PP_KILL_IMPL_58
#define PP_KILL_IMPL_60(_) PP_KILL_IMPL_59
#define PP_KILL_IMPL_61(_) PP_KILL_IMPL_60
#define PP_KILL_IMPL_62(_) PP_KILL_IMPL_61
#define PP_KILL_IMPL_63(_) PP_KILL_IMPL_62
#define PP_KILL_IMPL_64(_) PP_KILL_IMPL_63
#define PP_KILL_IMPL_65(_) PP_KILL_IMPL_64
#define PP_KILL_IMPL_66(_) PP_KILL_IMPL_65
#define PP_KILL_IMPL_67(_) PP_KILL_IMPL_66
#define PP_KILL_IMPL_68(_) PP_KILL_IMPL_67
#define PP_KILL_IMPL_69(_) PP_KILL_IMPL_68
#define PP_KILL_IMPL_70(_) PP_KILL_IMPL_69
#define PP_KILL_IMPL_71(_) PP_KILL_IMPL_70
#define PP_KILL_IMPL_72(_) PP_KILL_IMPL_71
#define PP_KILL_IMPL_73(_) PP_KILL_IMPL_72
#define PP_KILL_IMPL_74(_) PP_KILL_IMPL_73
#define PP_KILL_IMPL_75(_) PP_KILL_IMPL_74
#define PP_KILL_IMPL_76(_) PP_KILL_IMPL_75
#define PP_KILL_IMPL_77(_) PP_KILL_IMPL_76
#define PP_KILL_IMPL_78(_) PP_KILL_IMPL_77
#define PP_KILL_IMPL_79(_) PP_KILL_IMPL_78
#define PP_KILL_IMPL_80(_) PP_KILL_IMPL_79
#define PP_KILL_IMPL_81(_) PP_KILL_IMPL_80
#define PP_KILL_IMPL_82(_) PP_KILL_IMPL_81
#define PP_KILL_IMPL_83(_) PP_KILL_IMPL_82
#define PP_KILL_IMPL_84(_) PP_KILL_IMPL_83
#define PP_KILL_IMPL_85(_) PP_KILL_IMPL_84
#define PP_KILL_IMPL_86(_) PP_KILL_IMPL_85
#define PP_KILL_IMPL_87(_) PP_KILL_IMPL_86
#define PP_KILL_IMPL_88(_) PP_KILL_IMPL_87
#define PP_KILL_IMPL_89(_) PP_KILL_IMPL_88
#define PP_KILL_IMPL_90(_) PP_KILL_IMPL_89
#define PP_KILL_IMPL_91(_) PP_KILL_IMPL_90
#define PP_KILL_IMPL_92(_) PP_KILL_IMPL_91
#define PP_KILL_IMPL_93(_) PP_KILL_IMPL_92
#define PP_KILL_IMPL_94(_) PP_KILL_IMPL_93
#define PP_KILL_IMPL_95(_) PP_KILL_IMPL_94
#define PP_KILL_IMPL_96(_) PP_KILL_IMPL_95
#define PP_KILL_IMPL_97(_) PP_KILL_IMPL_96
#define PP_KILL_IMPL_98(_) PP_KILL_IMPL_97
#define PP_KILL_IMPL_99(_) PP_KILL_IMPL_98
#define PP_KILL_IMPL_100(_) PP_KILL_IMPL_99

////////////////////////////////////////////////////////////////////////////////
#define PP_ELEMENT_IMPL(seq, \
    index) PP_ELEMENT_IMPL_A((PP_CONCAT(PP_ELEMENT_IMPL_, index) seq))
#define PP_ELEMENT_IMPL_A(x) PP_ELEMENT_IMPL_C(PP_ELEMENT_IMPL_B x)
#define PP_ELEMENT_IMPL_B(x, _) x
#define PP_ELEMENT_IMPL_C(x) x
#define PP_ELEMENT_IMPL_0(x) x, PP_NIL
#define PP_ELEMENT_IMPL_1(_) PP_ELEMENT_IMPL_0
#define PP_ELEMENT_IMPL_2(_) PP_ELEMENT_IMPL_1
#define PP_ELEMENT_IMPL_3(_) PP_ELEMENT_IMPL_2
#define PP_ELEMENT_IMPL_4(_) PP_ELEMENT_IMPL_3
#define PP_ELEMENT_IMPL_5(_) PP_ELEMENT_IMPL_4
#define PP_ELEMENT_IMPL_6(_) PP_ELEMENT_IMPL_5
#define PP_ELEMENT_IMPL_7(_) PP_ELEMENT_IMPL_6
#define PP_ELEMENT_IMPL_8(_) PP_ELEMENT_IMPL_7
#define PP_ELEMENT_IMPL_9(_) PP_ELEMENT_IMPL_8
#define PP_ELEMENT_IMPL_10(_) PP_ELEMENT_IMPL_9
#define PP_ELEMENT_IMPL_11(_) PP_ELEMENT_IMPL_10
#define PP_ELEMENT_IMPL_12(_) PP_ELEMENT_IMPL_11
#define PP_ELEMENT_IMPL_13(_) PP_ELEMENT_IMPL_12
#define PP_ELEMENT_IMPL_14(_) PP_ELEMENT_IMPL_13
#define PP_ELEMENT_IMPL_15(_) PP_ELEMENT_IMPL_14
#define PP_ELEMENT_IMPL_16(_) PP_ELEMENT_IMPL_15
#define PP_ELEMENT_IMPL_17(_) PP_ELEMENT_IMPL_16
#define PP_ELEMENT_IMPL_18(_) PP_ELEMENT_IMPL_17
#define PP_ELEMENT_IMPL_19(_) PP_ELEMENT_IMPL_18
#define PP_ELEMENT_IMPL_20(_) PP_ELEMENT_IMPL_19
#define PP_ELEMENT_IMPL_21(_) PP_ELEMENT_IMPL_20
#define PP_ELEMENT_IMPL_22(_) PP_ELEMENT_IMPL_21
#define PP_ELEMENT_IMPL_23(_) PP_ELEMENT_IMPL_22
#define PP_ELEMENT_IMPL_24(_) PP_ELEMENT_IMPL_23
#define PP_ELEMENT_IMPL_25(_) PP_ELEMENT_IMPL_24
#define PP_ELEMENT_IMPL_26(_) PP_ELEMENT_IMPL_25
#define PP_ELEMENT_IMPL_27(_) PP_ELEMENT_IMPL_26
#define PP_ELEMENT_IMPL_28(_) PP_ELEMENT_IMPL_27
#define PP_ELEMENT_IMPL_29(_) PP_ELEMENT_IMPL_28
#define PP_ELEMENT_IMPL_30(_) PP_ELEMENT_IMPL_29
#define PP_ELEMENT_IMPL_31(_) PP_ELEMENT_IMPL_30
#define PP_ELEMENT_IMPL_32(_) PP_ELEMENT_IMPL_31
#define PP_ELEMENT_IMPL_33(_) PP_ELEMENT_IMPL_32
#define PP_ELEMENT_IMPL_34(_) PP_ELEMENT_IMPL_33
#define PP_ELEMENT_IMPL_35(_) PP_ELEMENT_IMPL_34
#define PP_ELEMENT_IMPL_36(_) PP_ELEMENT_IMPL_35
#define PP_ELEMENT_IMPL_37(_) PP_ELEMENT_IMPL_36
#define PP_ELEMENT_IMPL_38(_) PP_ELEMENT_IMPL_37
#define PP_ELEMENT_IMPL_39(_) PP_ELEMENT_IMPL_38
#define PP_ELEMENT_IMPL_40(_) PP_ELEMENT_IMPL_39
#define PP_ELEMENT_IMPL_41(_) PP_ELEMENT_IMPL_40
#define PP_ELEMENT_IMPL_42(_) PP_ELEMENT_IMPL_41
#define PP_ELEMENT_IMPL_43(_) PP_ELEMENT_IMPL_42
#define PP_ELEMENT_IMPL_44(_) PP_ELEMENT_IMPL_43
#define PP_ELEMENT_IMPL_45(_) PP_ELEMENT_IMPL_44
#define PP_ELEMENT_IMPL_46(_) PP_ELEMENT_IMPL_45
#define PP_ELEMENT_IMPL_47(_) PP_ELEMENT_IMPL_46
#define PP_ELEMENT_IMPL_48(_) PP_ELEMENT_IMPL_47
#define PP_ELEMENT_IMPL_49(_) PP_ELEMENT_IMPL_48
#define PP_ELEMENT_IMPL_50(_) PP_ELEMENT_IMPL_49
#define PP_ELEMENT_IMPL_51(_) PP_ELEMENT_IMPL_50
#define PP_ELEMENT_IMPL_52(_) PP_ELEMENT_IMPL_51
#define PP_ELEMENT_IMPL_53(_) PP_ELEMENT_IMPL_52
#define PP_ELEMENT_IMPL_54(_) PP_ELEMENT_IMPL_53
#define PP_ELEMENT_IMPL_55(_) PP_ELEMENT_IMPL_54
#define PP_ELEMENT_IMPL_56(_) PP_ELEMENT_IMPL_55
#define PP_ELEMENT_IMPL_57(_) PP_ELEMENT_IMPL_56
#define PP_ELEMENT_IMPL_58(_) PP_ELEMENT_IMPL_57
#define PP_ELEMENT_IMPL_59(_) PP_ELEMENT_IMPL_58
#define PP_ELEMENT_IMPL_60(_) PP_ELEMENT_IMPL_59
#define PP_ELEMENT_IMPL_61(_) PP_ELEMENT_IMPL_60
#define PP_ELEMENT_IMPL_62(_) PP_ELEMENT_IMPL_61
#define PP_ELEMENT_IMPL_63(_) PP_ELEMENT_IMPL_62
#define PP_ELEMENT_IMPL_64(_) PP_ELEMENT_IMPL_63
#define PP_ELEMENT_IMPL_65(_) PP_ELEMENT_IMPL_64
#define PP_ELEMENT_IMPL_66(_) PP_ELEMENT_IMPL_65
#define PP_ELEMENT_IMPL_67(_) PP_ELEMENT_IMPL_66
#define PP_ELEMENT_IMPL_68(_) PP_ELEMENT_IMPL_67
#define PP_ELEMENT_IMPL_69(_) PP_ELEMENT_IMPL_68
#define PP_ELEMENT_IMPL_70(_) PP_ELEMENT_IMPL_69
#define PP_ELEMENT_IMPL_71(_) PP_ELEMENT_IMPL_70
#define PP_ELEMENT_IMPL_72(_) PP_ELEMENT_IMPL_71
#define PP_ELEMENT_IMPL_73(_) PP_ELEMENT_IMPL_72
#define PP_ELEMENT_IMPL_74(_) PP_ELEMENT_IMPL_73
#define PP_ELEMENT_IMPL_75(_) PP_ELEMENT_IMPL_74
#define PP_ELEMENT_IMPL_76(_) PP_ELEMENT_IMPL_75
#define PP_ELEMENT_IMPL_77(_) PP_ELEMENT_IMPL_76
#define PP_ELEMENT_IMPL_78(_) PP_ELEMENT_IMPL_77
#define PP_ELEMENT_IMPL_79(_) PP_ELEMENT_IMPL_78
#define PP_ELEMENT_IMPL_80(_) PP_ELEMENT_IMPL_79
#define PP_ELEMENT_IMPL_81(_) PP_ELEMENT_IMPL_80
#define PP_ELEMENT_IMPL_82(_) PP_ELEMENT_IMPL_81
#define PP_ELEMENT_IMPL_83(_) PP_ELEMENT_IMPL_82
#define PP_ELEMENT_IMPL_84(_) PP_ELEMENT_IMPL_83
#define PP_ELEMENT_IMPL_85(_) PP_ELEMENT_IMPL_84
#define PP_ELEMENT_IMPL_86(_) PP_ELEMENT_IMPL_85
#define PP_ELEMENT_IMPL_87(_) PP_ELEMENT_IMPL_86
#define PP_ELEMENT_IMPL_88(_) PP_ELEMENT_IMPL_87
#define PP_ELEMENT_IMPL_89(_) PP_ELEMENT_IMPL_88
#define PP_ELEMENT_IMPL_90(_) PP_ELEMENT_IMPL_89
#define PP_ELEMENT_IMPL_91(_) PP_ELEMENT_IMPL_90
#define PP_ELEMENT_IMPL_92(_) PP_ELEMENT_IMPL_91
#define PP_ELEMENT_IMPL_93(_) PP_ELEMENT_IMPL_92
#define PP_ELEMENT_IMPL_94(_) PP_ELEMENT_IMPL_93
#define PP_ELEMENT_IMPL_95(_) PP_ELEMENT_IMPL_94
#define PP_ELEMENT_IMPL_96(_) PP_ELEMENT_IMPL_95
#define PP_ELEMENT_IMPL_97(_) PP_ELEMENT_IMPL_96
#define PP_ELEMENT_IMPL_98(_) PP_ELEMENT_IMPL_97
#define PP_ELEMENT_IMPL_99(_) PP_ELEMENT_IMPL_98
#define PP_ELEMENT_IMPL_100(_) PP_ELEMENT_IMPL_99

////////////////////////////////////////////////////////////////////////////////
#define PP_HEAD_IMPL(seq) PP_ELEMENT_IMPL(seq, 0)

////////////////////////////////////////////////////////////////////////////////
#define PP_TAIL_IMPL(seq) PP_KILL_IMPL(seq, 1)

////////////////////////////////////////////////////////////////////////////////
#define PP_FOR_EACH_IMPL(what, seq) PP_CONCAT(PP_FOR_EACH_IMPL_, \
    PP_COUNT(seq))(what, seq)
#define PP_FOR_EACH_IMPL_0(what, seq)
#define PP_FOR_EACH_IMPL_1(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_0(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_2(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_1(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_3(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_2(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_4(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_3(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_5(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_4(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_6(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_5(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_7(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_6(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_8(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_7(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_9(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_8(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_10(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_9(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_11(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_10(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_12(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_11(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_13(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_12(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_14(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_13(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_15(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_14(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_16(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_15(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_17(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_16(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_18(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_17(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_19(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_18(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_20(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_19(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_21(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_20(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_22(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_21(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_23(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_22(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_24(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_23(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_25(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_24(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_26(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_25(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_27(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_26(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_28(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_27(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_29(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_28(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_30(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_29(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_31(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_30(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_32(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_31(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_33(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_32(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_34(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_33(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_35(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_34(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_36(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_35(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_37(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_36(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_38(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_37(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_39(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_38(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_40(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_39(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_41(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_40(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_42(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_41(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_43(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_42(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_44(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_43(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_45(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_44(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_46(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_45(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_47(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_46(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_48(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_47(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_49(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_48(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_50(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_49(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_51(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_50(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_52(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_51(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_53(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_52(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_54(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_53(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_55(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_54(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_56(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_55(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_57(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_56(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_58(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_57(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_59(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_58(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_60(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_59(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_61(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_60(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_62(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_61(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_63(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_62(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_64(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_63(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_65(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_64(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_66(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_65(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_67(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_66(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_68(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_67(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_69(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_68(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_70(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_69(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_71(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_70(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_72(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_71(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_73(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_72(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_74(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_73(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_75(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_74(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_76(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_75(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_77(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_76(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_78(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_77(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_79(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_78(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_80(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_79(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_81(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_80(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_82(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_81(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_83(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_82(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_84(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_83(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_85(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_84(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_86(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_85(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_87(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_86(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_88(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_87(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_89(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_88(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_90(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_89(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_91(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_90(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_92(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_91(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_93(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_92(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_94(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_93(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_95(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_94(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_96(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_95(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_97(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_96(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_98(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_97(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_99(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_98(what, PP_TAIL(seq))
#define PP_FOR_EACH_IMPL_100(what, \
    seq) what(PP_HEAD(seq)) PP_FOR_EACH_IMPL_99(what, PP_TAIL(seq))
////////////////////////////////////////////////////////////////////////////////
/*!
  \endinternal
*/
