#pragma once

// .h autogenerated by cmake!

#define USE_CPUID 1
#define USE_BASE64 1
#define USE_SSL 0
#define USE_HDFS 0
#define USE_AWS_S3 0
#define USE_AZURE_BLOB_STORAGE 0
#define USE_BROTLI 0
#define USE_UNWIND 1
#define USE_CASSANDRA 0
#define USE_SENTRY 0
#define USE_GRPC 0
#define USE_SIMDJSON 0
#define USE_RAPIDJSON 1

#define USE_DATASKETCHES 0
#define USE_YAML_CPP 0
#define USE_BZIP2 0
#define USE_MINIZIP 0
#define USE_SNAPPY 1
#define USE_HIVE 0
#define USE_ODBC 0
#define USE_REPLXX 1
#define USE_JEMALLOC 0
