#pragma once

// .h autogenerated by cmake!

#define USE_BASE64 1
#define USE_SIMDJSON 0
#define USE_RAPIDJSON 1
#define USE_H3 1
#define USE_S2_GEOMETRY 0
#define USE_FASTOPS 1
#define USE_NLP 0
#define USE_VECTORSCAN 0
