// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_helpers.proto

package protocol;

public final class ProtobufHelpers {
  private ProtobufHelpers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TSerializedMessageEnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NYT.NProto.TSerializedMessageEnvelope)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 codec = 1 [default = 0];</code>
     */
    boolean hasCodec();
    /**
     * <code>optional int32 codec = 1 [default = 0];</code>
     */
    int getCodec();
  }
  /**
   * Protobuf type {@code NYT.NProto.TSerializedMessageEnvelope}
   */
  public  static final class TSerializedMessageEnvelope extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NYT.NProto.TSerializedMessageEnvelope)
      TSerializedMessageEnvelopeOrBuilder {
    // Use TSerializedMessageEnvelope.newBuilder() to construct.
    private TSerializedMessageEnvelope(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TSerializedMessageEnvelope() {
      codec_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TSerializedMessageEnvelope(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              codec_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.ProtobufHelpers.internal_static_NYT_NProto_TSerializedMessageEnvelope_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.ProtobufHelpers.internal_static_NYT_NProto_TSerializedMessageEnvelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.ProtobufHelpers.TSerializedMessageEnvelope.class, protocol.ProtobufHelpers.TSerializedMessageEnvelope.Builder.class);
    }

    private int bitField0_;
    public static final int CODEC_FIELD_NUMBER = 1;
    private int codec_;
    /**
     * <code>optional int32 codec = 1 [default = 0];</code>
     */
    public boolean hasCodec() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 codec = 1 [default = 0];</code>
     */
    public int getCodec() {
      return codec_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, codec_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, codec_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.ProtobufHelpers.TSerializedMessageEnvelope)) {
        return super.equals(obj);
      }
      protocol.ProtobufHelpers.TSerializedMessageEnvelope other = (protocol.ProtobufHelpers.TSerializedMessageEnvelope) obj;

      boolean result = true;
      result = result && (hasCodec() == other.hasCodec());
      if (hasCodec()) {
        result = result && (getCodec()
            == other.getCodec());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCodec()) {
        hash = (37 * hash) + CODEC_FIELD_NUMBER;
        hash = (53 * hash) + getCodec();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.ProtobufHelpers.TSerializedMessageEnvelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ProtobufHelpers.TSerializedMessageEnvelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ProtobufHelpers.TSerializedMessageEnvelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ProtobufHelpers.TSerializedMessageEnvelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ProtobufHelpers.TSerializedMessageEnvelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ProtobufHelpers.TSerializedMessageEnvelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ProtobufHelpers.TSerializedMessageEnvelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.ProtobufHelpers.TSerializedMessageEnvelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ProtobufHelpers.TSerializedMessageEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ProtobufHelpers.TSerializedMessageEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.ProtobufHelpers.TSerializedMessageEnvelope prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NYT.NProto.TSerializedMessageEnvelope}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NYT.NProto.TSerializedMessageEnvelope)
        protocol.ProtobufHelpers.TSerializedMessageEnvelopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.ProtobufHelpers.internal_static_NYT_NProto_TSerializedMessageEnvelope_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.ProtobufHelpers.internal_static_NYT_NProto_TSerializedMessageEnvelope_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.ProtobufHelpers.TSerializedMessageEnvelope.class, protocol.ProtobufHelpers.TSerializedMessageEnvelope.Builder.class);
      }

      // Construct using protocol.ProtobufHelpers.TSerializedMessageEnvelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        codec_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.ProtobufHelpers.internal_static_NYT_NProto_TSerializedMessageEnvelope_descriptor;
      }

      public protocol.ProtobufHelpers.TSerializedMessageEnvelope getDefaultInstanceForType() {
        return protocol.ProtobufHelpers.TSerializedMessageEnvelope.getDefaultInstance();
      }

      public protocol.ProtobufHelpers.TSerializedMessageEnvelope build() {
        protocol.ProtobufHelpers.TSerializedMessageEnvelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.ProtobufHelpers.TSerializedMessageEnvelope buildPartial() {
        protocol.ProtobufHelpers.TSerializedMessageEnvelope result = new protocol.ProtobufHelpers.TSerializedMessageEnvelope(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.codec_ = codec_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.ProtobufHelpers.TSerializedMessageEnvelope) {
          return mergeFrom((protocol.ProtobufHelpers.TSerializedMessageEnvelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.ProtobufHelpers.TSerializedMessageEnvelope other) {
        if (other == protocol.ProtobufHelpers.TSerializedMessageEnvelope.getDefaultInstance()) return this;
        if (other.hasCodec()) {
          setCodec(other.getCodec());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.ProtobufHelpers.TSerializedMessageEnvelope parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.ProtobufHelpers.TSerializedMessageEnvelope) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int codec_ ;
      /**
       * <code>optional int32 codec = 1 [default = 0];</code>
       */
      public boolean hasCodec() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 codec = 1 [default = 0];</code>
       */
      public int getCodec() {
        return codec_;
      }
      /**
       * <code>optional int32 codec = 1 [default = 0];</code>
       */
      public Builder setCodec(int value) {
        bitField0_ |= 0x00000001;
        codec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 codec = 1 [default = 0];</code>
       */
      public Builder clearCodec() {
        bitField0_ = (bitField0_ & ~0x00000001);
        codec_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NYT.NProto.TSerializedMessageEnvelope)
    }

    // @@protoc_insertion_point(class_scope:NYT.NProto.TSerializedMessageEnvelope)
    private static final protocol.ProtobufHelpers.TSerializedMessageEnvelope DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.ProtobufHelpers.TSerializedMessageEnvelope();
    }

    public static protocol.ProtobufHelpers.TSerializedMessageEnvelope getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TSerializedMessageEnvelope>
        PARSER = new com.google.protobuf.AbstractParser<TSerializedMessageEnvelope>() {
      public TSerializedMessageEnvelope parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TSerializedMessageEnvelope(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TSerializedMessageEnvelope> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TSerializedMessageEnvelope> getParserForType() {
      return PARSER;
    }

    public protocol.ProtobufHelpers.TSerializedMessageEnvelope getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TExtensionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NYT.NProto.TExtension)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 tag = 1;</code>
     */
    boolean hasTag();
    /**
     * <code>required int32 tag = 1;</code>
     */
    int getTag();

    /**
     * <code>required bytes data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code NYT.NProto.TExtension}
   */
  public  static final class TExtension extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NYT.NProto.TExtension)
      TExtensionOrBuilder {
    // Use TExtension.newBuilder() to construct.
    private TExtension(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TExtension() {
      tag_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TExtension(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              tag_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.ProtobufHelpers.internal_static_NYT_NProto_TExtension_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.ProtobufHelpers.internal_static_NYT_NProto_TExtension_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.ProtobufHelpers.TExtension.class, protocol.ProtobufHelpers.TExtension.Builder.class);
    }

    private int bitField0_;
    public static final int TAG_FIELD_NUMBER = 1;
    private int tag_;
    /**
     * <code>required int32 tag = 1;</code>
     */
    public boolean hasTag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 tag = 1;</code>
     */
    public int getTag() {
      return tag_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, tag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, tag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.ProtobufHelpers.TExtension)) {
        return super.equals(obj);
      }
      protocol.ProtobufHelpers.TExtension other = (protocol.ProtobufHelpers.TExtension) obj;

      boolean result = true;
      result = result && (hasTag() == other.hasTag());
      if (hasTag()) {
        result = result && (getTag()
            == other.getTag());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTag()) {
        hash = (37 * hash) + TAG_FIELD_NUMBER;
        hash = (53 * hash) + getTag();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.ProtobufHelpers.TExtension parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ProtobufHelpers.TExtension parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ProtobufHelpers.TExtension parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ProtobufHelpers.TExtension parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ProtobufHelpers.TExtension parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ProtobufHelpers.TExtension parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ProtobufHelpers.TExtension parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.ProtobufHelpers.TExtension parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ProtobufHelpers.TExtension parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ProtobufHelpers.TExtension parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.ProtobufHelpers.TExtension prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NYT.NProto.TExtension}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NYT.NProto.TExtension)
        protocol.ProtobufHelpers.TExtensionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.ProtobufHelpers.internal_static_NYT_NProto_TExtension_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.ProtobufHelpers.internal_static_NYT_NProto_TExtension_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.ProtobufHelpers.TExtension.class, protocol.ProtobufHelpers.TExtension.Builder.class);
      }

      // Construct using protocol.ProtobufHelpers.TExtension.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.ProtobufHelpers.internal_static_NYT_NProto_TExtension_descriptor;
      }

      public protocol.ProtobufHelpers.TExtension getDefaultInstanceForType() {
        return protocol.ProtobufHelpers.TExtension.getDefaultInstance();
      }

      public protocol.ProtobufHelpers.TExtension build() {
        protocol.ProtobufHelpers.TExtension result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.ProtobufHelpers.TExtension buildPartial() {
        protocol.ProtobufHelpers.TExtension result = new protocol.ProtobufHelpers.TExtension(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tag_ = tag_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.ProtobufHelpers.TExtension) {
          return mergeFrom((protocol.ProtobufHelpers.TExtension)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.ProtobufHelpers.TExtension other) {
        if (other == protocol.ProtobufHelpers.TExtension.getDefaultInstance()) return this;
        if (other.hasTag()) {
          setTag(other.getTag());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTag()) {
          return false;
        }
        if (!hasData()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.ProtobufHelpers.TExtension parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.ProtobufHelpers.TExtension) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int tag_ ;
      /**
       * <code>required int32 tag = 1;</code>
       */
      public boolean hasTag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 tag = 1;</code>
       */
      public int getTag() {
        return tag_;
      }
      /**
       * <code>required int32 tag = 1;</code>
       */
      public Builder setTag(int value) {
        bitField0_ |= 0x00000001;
        tag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 tag = 1;</code>
       */
      public Builder clearTag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tag_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NYT.NProto.TExtension)
    }

    // @@protoc_insertion_point(class_scope:NYT.NProto.TExtension)
    private static final protocol.ProtobufHelpers.TExtension DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.ProtobufHelpers.TExtension();
    }

    public static protocol.ProtobufHelpers.TExtension getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TExtension>
        PARSER = new com.google.protobuf.AbstractParser<TExtension>() {
      public TExtension parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TExtension(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TExtension> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TExtension> getParserForType() {
      return PARSER;
    }

    public protocol.ProtobufHelpers.TExtension getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TExtensionSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NYT.NProto.TExtensionSet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
     */
    java.util.List<protocol.ProtobufHelpers.TExtension> 
        getExtensionsList();
    /**
     * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
     */
    protocol.ProtobufHelpers.TExtension getExtensions(int index);
    /**
     * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
     */
    int getExtensionsCount();
    /**
     * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
     */
    java.util.List<? extends protocol.ProtobufHelpers.TExtensionOrBuilder> 
        getExtensionsOrBuilderList();
    /**
     * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
     */
    protocol.ProtobufHelpers.TExtensionOrBuilder getExtensionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code NYT.NProto.TExtensionSet}
   */
  public  static final class TExtensionSet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NYT.NProto.TExtensionSet)
      TExtensionSetOrBuilder {
    // Use TExtensionSet.newBuilder() to construct.
    private TExtensionSet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TExtensionSet() {
      extensions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TExtensionSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                extensions_ = new java.util.ArrayList<protocol.ProtobufHelpers.TExtension>();
                mutable_bitField0_ |= 0x00000001;
              }
              extensions_.add(
                  input.readMessage(protocol.ProtobufHelpers.TExtension.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          extensions_ = java.util.Collections.unmodifiableList(extensions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.ProtobufHelpers.internal_static_NYT_NProto_TExtensionSet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.ProtobufHelpers.internal_static_NYT_NProto_TExtensionSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.ProtobufHelpers.TExtensionSet.class, protocol.ProtobufHelpers.TExtensionSet.Builder.class);
    }

    public static final int EXTENSIONS_FIELD_NUMBER = 1;
    private java.util.List<protocol.ProtobufHelpers.TExtension> extensions_;
    /**
     * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
     */
    public java.util.List<protocol.ProtobufHelpers.TExtension> getExtensionsList() {
      return extensions_;
    }
    /**
     * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
     */
    public java.util.List<? extends protocol.ProtobufHelpers.TExtensionOrBuilder> 
        getExtensionsOrBuilderList() {
      return extensions_;
    }
    /**
     * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
     */
    public int getExtensionsCount() {
      return extensions_.size();
    }
    /**
     * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
     */
    public protocol.ProtobufHelpers.TExtension getExtensions(int index) {
      return extensions_.get(index);
    }
    /**
     * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
     */
    public protocol.ProtobufHelpers.TExtensionOrBuilder getExtensionsOrBuilder(
        int index) {
      return extensions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getExtensionsCount(); i++) {
        if (!getExtensions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < extensions_.size(); i++) {
        output.writeMessage(1, extensions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < extensions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, extensions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.ProtobufHelpers.TExtensionSet)) {
        return super.equals(obj);
      }
      protocol.ProtobufHelpers.TExtensionSet other = (protocol.ProtobufHelpers.TExtensionSet) obj;

      boolean result = true;
      result = result && getExtensionsList()
          .equals(other.getExtensionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getExtensionsCount() > 0) {
        hash = (37 * hash) + EXTENSIONS_FIELD_NUMBER;
        hash = (53 * hash) + getExtensionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.ProtobufHelpers.TExtensionSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ProtobufHelpers.TExtensionSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ProtobufHelpers.TExtensionSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ProtobufHelpers.TExtensionSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ProtobufHelpers.TExtensionSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ProtobufHelpers.TExtensionSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ProtobufHelpers.TExtensionSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.ProtobufHelpers.TExtensionSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ProtobufHelpers.TExtensionSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ProtobufHelpers.TExtensionSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.ProtobufHelpers.TExtensionSet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NYT.NProto.TExtensionSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NYT.NProto.TExtensionSet)
        protocol.ProtobufHelpers.TExtensionSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.ProtobufHelpers.internal_static_NYT_NProto_TExtensionSet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.ProtobufHelpers.internal_static_NYT_NProto_TExtensionSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.ProtobufHelpers.TExtensionSet.class, protocol.ProtobufHelpers.TExtensionSet.Builder.class);
      }

      // Construct using protocol.ProtobufHelpers.TExtensionSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getExtensionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (extensionsBuilder_ == null) {
          extensions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          extensionsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.ProtobufHelpers.internal_static_NYT_NProto_TExtensionSet_descriptor;
      }

      public protocol.ProtobufHelpers.TExtensionSet getDefaultInstanceForType() {
        return protocol.ProtobufHelpers.TExtensionSet.getDefaultInstance();
      }

      public protocol.ProtobufHelpers.TExtensionSet build() {
        protocol.ProtobufHelpers.TExtensionSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.ProtobufHelpers.TExtensionSet buildPartial() {
        protocol.ProtobufHelpers.TExtensionSet result = new protocol.ProtobufHelpers.TExtensionSet(this);
        int from_bitField0_ = bitField0_;
        if (extensionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            extensions_ = java.util.Collections.unmodifiableList(extensions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.extensions_ = extensions_;
        } else {
          result.extensions_ = extensionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.ProtobufHelpers.TExtensionSet) {
          return mergeFrom((protocol.ProtobufHelpers.TExtensionSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.ProtobufHelpers.TExtensionSet other) {
        if (other == protocol.ProtobufHelpers.TExtensionSet.getDefaultInstance()) return this;
        if (extensionsBuilder_ == null) {
          if (!other.extensions_.isEmpty()) {
            if (extensions_.isEmpty()) {
              extensions_ = other.extensions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureExtensionsIsMutable();
              extensions_.addAll(other.extensions_);
            }
            onChanged();
          }
        } else {
          if (!other.extensions_.isEmpty()) {
            if (extensionsBuilder_.isEmpty()) {
              extensionsBuilder_.dispose();
              extensionsBuilder_ = null;
              extensions_ = other.extensions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              extensionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getExtensionsFieldBuilder() : null;
            } else {
              extensionsBuilder_.addAllMessages(other.extensions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getExtensionsCount(); i++) {
          if (!getExtensions(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.ProtobufHelpers.TExtensionSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.ProtobufHelpers.TExtensionSet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<protocol.ProtobufHelpers.TExtension> extensions_ =
        java.util.Collections.emptyList();
      private void ensureExtensionsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          extensions_ = new java.util.ArrayList<protocol.ProtobufHelpers.TExtension>(extensions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.ProtobufHelpers.TExtension, protocol.ProtobufHelpers.TExtension.Builder, protocol.ProtobufHelpers.TExtensionOrBuilder> extensionsBuilder_;

      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public java.util.List<protocol.ProtobufHelpers.TExtension> getExtensionsList() {
        if (extensionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(extensions_);
        } else {
          return extensionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public int getExtensionsCount() {
        if (extensionsBuilder_ == null) {
          return extensions_.size();
        } else {
          return extensionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public protocol.ProtobufHelpers.TExtension getExtensions(int index) {
        if (extensionsBuilder_ == null) {
          return extensions_.get(index);
        } else {
          return extensionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public Builder setExtensions(
          int index, protocol.ProtobufHelpers.TExtension value) {
        if (extensionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtensionsIsMutable();
          extensions_.set(index, value);
          onChanged();
        } else {
          extensionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public Builder setExtensions(
          int index, protocol.ProtobufHelpers.TExtension.Builder builderForValue) {
        if (extensionsBuilder_ == null) {
          ensureExtensionsIsMutable();
          extensions_.set(index, builderForValue.build());
          onChanged();
        } else {
          extensionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public Builder addExtensions(protocol.ProtobufHelpers.TExtension value) {
        if (extensionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtensionsIsMutable();
          extensions_.add(value);
          onChanged();
        } else {
          extensionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public Builder addExtensions(
          int index, protocol.ProtobufHelpers.TExtension value) {
        if (extensionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExtensionsIsMutable();
          extensions_.add(index, value);
          onChanged();
        } else {
          extensionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public Builder addExtensions(
          protocol.ProtobufHelpers.TExtension.Builder builderForValue) {
        if (extensionsBuilder_ == null) {
          ensureExtensionsIsMutable();
          extensions_.add(builderForValue.build());
          onChanged();
        } else {
          extensionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public Builder addExtensions(
          int index, protocol.ProtobufHelpers.TExtension.Builder builderForValue) {
        if (extensionsBuilder_ == null) {
          ensureExtensionsIsMutable();
          extensions_.add(index, builderForValue.build());
          onChanged();
        } else {
          extensionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public Builder addAllExtensions(
          java.lang.Iterable<? extends protocol.ProtobufHelpers.TExtension> values) {
        if (extensionsBuilder_ == null) {
          ensureExtensionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, extensions_);
          onChanged();
        } else {
          extensionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public Builder clearExtensions() {
        if (extensionsBuilder_ == null) {
          extensions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          extensionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public Builder removeExtensions(int index) {
        if (extensionsBuilder_ == null) {
          ensureExtensionsIsMutable();
          extensions_.remove(index);
          onChanged();
        } else {
          extensionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public protocol.ProtobufHelpers.TExtension.Builder getExtensionsBuilder(
          int index) {
        return getExtensionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public protocol.ProtobufHelpers.TExtensionOrBuilder getExtensionsOrBuilder(
          int index) {
        if (extensionsBuilder_ == null) {
          return extensions_.get(index);  } else {
          return extensionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public java.util.List<? extends protocol.ProtobufHelpers.TExtensionOrBuilder> 
           getExtensionsOrBuilderList() {
        if (extensionsBuilder_ != null) {
          return extensionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(extensions_);
        }
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public protocol.ProtobufHelpers.TExtension.Builder addExtensionsBuilder() {
        return getExtensionsFieldBuilder().addBuilder(
            protocol.ProtobufHelpers.TExtension.getDefaultInstance());
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public protocol.ProtobufHelpers.TExtension.Builder addExtensionsBuilder(
          int index) {
        return getExtensionsFieldBuilder().addBuilder(
            index, protocol.ProtobufHelpers.TExtension.getDefaultInstance());
      }
      /**
       * <code>repeated .NYT.NProto.TExtension extensions = 1;</code>
       */
      public java.util.List<protocol.ProtobufHelpers.TExtension.Builder> 
           getExtensionsBuilderList() {
        return getExtensionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.ProtobufHelpers.TExtension, protocol.ProtobufHelpers.TExtension.Builder, protocol.ProtobufHelpers.TExtensionOrBuilder> 
          getExtensionsFieldBuilder() {
        if (extensionsBuilder_ == null) {
          extensionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocol.ProtobufHelpers.TExtension, protocol.ProtobufHelpers.TExtension.Builder, protocol.ProtobufHelpers.TExtensionOrBuilder>(
                  extensions_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          extensions_ = null;
        }
        return extensionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NYT.NProto.TExtensionSet)
    }

    // @@protoc_insertion_point(class_scope:NYT.NProto.TExtensionSet)
    private static final protocol.ProtobufHelpers.TExtensionSet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.ProtobufHelpers.TExtensionSet();
    }

    public static protocol.ProtobufHelpers.TExtensionSet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TExtensionSet>
        PARSER = new com.google.protobuf.AbstractParser<TExtensionSet>() {
      public TExtensionSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TExtensionSet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TExtensionSet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TExtensionSet> getParserForType() {
      return PARSER;
    }

    public protocol.ProtobufHelpers.TExtensionSet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NYT_NProto_TSerializedMessageEnvelope_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NYT_NProto_TSerializedMessageEnvelope_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NYT_NProto_TExtension_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NYT_NProto_TExtension_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NYT_NProto_TExtensionSet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NYT_NProto_TExtensionSet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026protobuf_helpers.proto\022\nNYT.NProto\".\n\032" +
      "TSerializedMessageEnvelope\022\020\n\005codec\030\001 \001(" +
      "\005:\0010\"\'\n\nTExtension\022\013\n\003tag\030\001 \002(\005\022\014\n\004data\030" +
      "\002 \002(\014\";\n\rTExtensionSet\022*\n\nextensions\030\001 \003" +
      "(\0132\026.NYT.NProto.TExtensionB\n\n\010protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NYT_NProto_TSerializedMessageEnvelope_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NYT_NProto_TSerializedMessageEnvelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NYT_NProto_TSerializedMessageEnvelope_descriptor,
        new java.lang.String[] { "Codec", });
    internal_static_NYT_NProto_TExtension_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NYT_NProto_TExtension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NYT_NProto_TExtension_descriptor,
        new java.lang.String[] { "Tag", "Data", });
    internal_static_NYT_NProto_TExtensionSet_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_NYT_NProto_TExtensionSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NYT_NProto_TExtensionSet_descriptor,
        new java.lang.String[] { "Extensions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
