apiVersion: cluster.ytsaurus.tech/v1
kind: Ytsaurus
metadata:
  name: {{ cluster_name }}
spec:
  adminCredentials:
    name: ytadminsec
  coreImage: {{ images.ytsaurus }}
  dataNodes:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: yt_component
              operator: In
              values:
              - ytbench-yt-data-node
          topologyKey: kubernetes.io/hostname
    instanceCount: 5
    locations:
    - locationType: Logs
      medium: default
      path: /yt/data-node-logs
    - locationType: ChunkStore
      medium: default
      path: /yt/node-data/chunk-store
    loggers:
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: zstd
      format: plain_text
      minLogLevel: debug
      name: debug
      rotationPolicy:
        maxSegmentCountToKeep: 1000
        maxTotalSizeToKeep: 1073741824
        rotationPeriodMilliseconds: 900000
      useTimestampSuffix: false
      writerType: file
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: none
      format: plain_text
      minLogLevel: info
      name: info
      rotationPolicy:
        maxSegmentCountToKeep: 1000
        maxTotalSizeToKeep: 1073741824
        rotationPeriodMilliseconds: 900000
      useTimestampSuffix: false
      writerType: file
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: none
      format: plain_text
      minLogLevel: info
      name: info-stderr
      useTimestampSuffix: false
      writerType: stderr
    name: default
    setHostnameAsFqdn: true
    volumeClaimTemplates:
    - metadata:
        name: node-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 536870912000
        storageClassName: yc-network-ssd
    - metadata:
        name: data-node-logs
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    volumeMounts:
    - mountPath: /yt/data-node-logs
      name: data-node-logs
    - mountPath: /yt/node-data
      name: node-data
  discovery:
    instanceCount: 1
    locations:
    - locationType: Logs
      medium: default
      path: /yt/discovery-logs
    loggers:
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: zstd
      format: plain_text
      minLogLevel: debug
      name: debug
      rotationPolicy:
        maxSegmentCountToKeep: 1000
        maxTotalSizeToKeep: 1073741824
        rotationPeriodMilliseconds: 900000
      useTimestampSuffix: false
      writerType: file
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: none
      format: plain_text
      minLogLevel: info
      name: info
      rotationPolicy:
        maxSegmentCountToKeep: 1000
        maxTotalSizeToKeep: 1073741824
        rotationPeriodMilliseconds: 900000
      useTimestampSuffix: false
      writerType: file
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: none
      format: plain_text
      minLogLevel: info
      name: info-stderr
      useTimestampSuffix: false
      writerType: stderr
    setHostnameAsFqdn: true
    volumeClaimTemplates:
    - metadata:
        name: discovery-logs
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    volumeMounts:
    - mountPath: /yt/discovery-logs
      name: discovery-logs
  enableFullUpdate: true
  ephemeralCluster: false
  execNodes:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: yt_component
              operator: In
              values:
              - ytbench-yt-exec-node
          topologyKey: kubernetes.io/hostname
    instanceCount: 7
    jobEnvironment:
      cri:
        apiRetryTimeoutSeconds: 180
    jobProxyLoggers:
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Concurrency
      compression: zstd
      format: plain_text
      minLogLevel: debug
      name: debug
      rotationPolicy:
        maxTotalSizeToKeep: 10485760
        rotationPeriodMilliseconds: 900000
      useTimestampSuffix: true
      writerType: file
    - compression: none
      format: plain_text
      minLogLevel: info
      name: info
      rotationPolicy:
        maxTotalSizeToKeep: 10485760
        rotationPeriodMilliseconds: 900000
      useTimestampSuffix: false
      writerType: file
    - compression: none
      format: plain_text
      minLogLevel: error
      name: error
      useTimestampSuffix: false
      writerType: stderr
    jobResources:
      requests:
        cpu: 16
        memory: 67072Mi
    locations:
    - locationType: ChunkCache
      medium: default
      path: /yt/node-data/chunk-cache
    - locationType: Slots
      medium: default
      path: /yt/node-data/slots
    - locationType: Logs
      medium: default
      path: /yt/exec-node-logs
    - locationType: ImageCache
      medium: default
      path: /yt/node-data/image-cache
    loggers:
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: zstd
      format: plain_text
      minLogLevel: debug
      name: debug
      rotationPolicy:
        maxSegmentCountToKeep: 1000
        maxTotalSizeToKeep: 1073741824
        rotationPeriodMilliseconds: 900000
      useTimestampSuffix: false
      writerType: file
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: none
      format: plain_text
      minLogLevel: info
      name: info
      rotationPolicy:
        maxSegmentCountToKeep: 1000
        maxTotalSizeToKeep: 1073741824
        rotationPeriodMilliseconds: 900000
      useTimestampSuffix: false
      writerType: file
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: none
      format: plain_text
      minLogLevel: info
      name: info-stderr
      useTimestampSuffix: false
      writerType: stderr
    name: default
    privileged: true
    setHostnameAsFqdn: true
    volumeClaimTemplates:
    - metadata:
        name: exec-node-logs
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    volumeMounts:
    - mountPath: /yt/node-data
      name: node-data
    - mountPath: /yt/exec-node-logs
      name: exec-node-logs
    volumes:
    - emptyDir:
        sizeLimit: 299573968896
      name: node-data
  hostNetwork: false
  httpProxies:
  - httpPort: 80
    httpsPort: 443
    instanceCount: 1
    locations:
    - locationType: Logs
      medium: default
      path: /yt/http-proxy-logs
    loggers:
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: zstd
      format: plain_text
      minLogLevel: debug
      name: debug
      rotationPolicy:
        maxSegmentCountToKeep: 1000
        maxTotalSizeToKeep: 1073741824
        rotationPeriodMilliseconds: 900000
      useTimestampSuffix: false
      writerType: file
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: none
      format: plain_text
      minLogLevel: info
      name: info
      rotationPolicy:
        maxSegmentCountToKeep: 1000
        maxTotalSizeToKeep: 1073741824
        rotationPeriodMilliseconds: 900000
      useTimestampSuffix: false
      writerType: file
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: none
      format: plain_text
      minLogLevel: info
      name: info-stderr
      useTimestampSuffix: false
      writerType: stderr
    role: default
    serviceType: NodePort
    setHostnameAsFqdn: true
    volumeClaimTemplates:
    - metadata:
        name: http-proxy-logs
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    volumeMounts:
    - mountPath: /yt/http-proxy-logs
      name: http-proxy-logs
  isManaged: true
  jobImage: ghcr.io/ytsaurus/job-environment:0.0.1
  primaryMasters:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: yt_component
              operator: In
              values:
              - ytdemo-yt-master
          topologyKey: kubernetes.io/hostname
    cellTag: 1
    instanceCount: 3
    locations:
    - locationType: Logs
      medium: default
      path: /yt/master-logs
    - locationType: MasterChangelogs
      medium: default
      path: /yt/master-data/master-changelogs
    - locationType: MasterSnapshots
      medium: default
      path: /yt/master-data/master-snapshots
    loggers:
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: zstd
      format: plain_text
      minLogLevel: debug
      name: debug
      rotationPolicy:
        maxSegmentCountToKeep: 1000
        maxTotalSizeToKeep: 1073741824
        rotationPeriodMilliseconds: 900000
      useTimestampSuffix: false
      writerType: file
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: none
      format: plain_text
      minLogLevel: info
      name: info
      rotationPolicy:
        maxSegmentCountToKeep: 1000
        maxTotalSizeToKeep: 1073741824
        rotationPeriodMilliseconds: 900000
      useTimestampSuffix: false
      writerType: file
    - categoriesFilter:
        type: exclude
        values:
        - Bus
        - Logging
      compression: none
      format: plain_text
      minLogLevel: info
      name: info-stderr
      useTimestampSuffix: false
      writerType: stderr
    setHostnameAsFqdn: true
    volumeClaimTemplates:
    - metadata:
        name: master-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 99857989632
        storageClassName: yc-network-ssd
    - metadata:
        name: master-logs
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    volumeMounts:
    - mountPath: /yt/master-logs
      name: master-logs
    - mountPath: /yt/master-data
      name: master-data
  queryTrackers:
    image:  {{ images.query_tracker }}
    instanceCount: 1
    setHostnameAsFqdn: true
  rpcProxies:
  - instanceCount: 1
    role: default
    setHostnameAsFqdn: true
  schedulers:
    instanceCount: 1
    setHostnameAsFqdn: true
  controllerAgents:
    instanceCount: 1
    image:  {{ images.ytsaurus }}
  strawberry:
    image:  {{ images.strawberry }}
  tabletNodes:
  - instanceCount: 1
    name: default
    setHostnameAsFqdn: true
  useIpv4: false
  useIpv6: false
  usePorto: false
  useShortNames: true
  yqlAgents:
    image:  {{ images.query_tracker }}
    instanceCount: 1
    setHostnameAsFqdn: true
