SUBSCRIBER(g:contrib hiddenpath)
RECURSE(
    src
    src/archive
    src/archive/tar
    src/archive/zip
    src/arena
    src/bufio
    src/bytes
    src/cmp
    src/compress
    src/compress/bzip2
    src/compress/flate
    src/compress/gzip
    src/compress/lzw
    src/compress/zlib
    src/container
    src/container/heap
    src/container/list
    src/container/ring
    src/context
    src/crypto
    src/crypto/aes
    src/crypto/boring
    src/crypto/cipher
    src/crypto/des
    src/crypto/dsa
    src/crypto/ecdh
    src/crypto/ecdsa
    src/crypto/ed25519
    src/crypto/elliptic
    src/crypto/hmac
    src/crypto/internal
    src/crypto/internal/alias
    src/crypto/internal/bigmod
    src/crypto/internal/boring
    src/crypto/internal/boring/bbig
    src/crypto/internal/boring/bcache
    src/crypto/internal/boring/fipstls
    src/crypto/internal/boring/sig
    src/crypto/internal/boring/syso
    src/crypto/internal/cryptotest
    src/crypto/internal/edwards25519
    src/crypto/internal/edwards25519/field
    src/crypto/internal/hpke
    src/crypto/internal/mlkem768
    src/crypto/internal/nistec
    src/crypto/internal/nistec/fiat
    src/crypto/internal/randutil
    src/crypto/md5
    src/crypto/rand
    src/crypto/rc4
    src/crypto/rsa
    src/crypto/sha1
    src/crypto/sha256
    src/crypto/sha512
    src/crypto/subtle
    src/crypto/tls
    src/crypto/tls/fipsonly
    src/crypto/x509
    src/crypto/x509/internal
    src/crypto/x509/internal/macos
    src/crypto/x509/pkix
    src/database
    src/database/sql
    src/database/sql/driver
    src/debug
    src/debug/buildinfo
    src/debug/dwarf
    src/debug/elf
    src/debug/gosym
    src/debug/macho
    src/debug/pe
    src/debug/plan9obj
    src/embed
    src/embed/internal
    src/embed/internal/embedtest
    src/encoding
    src/encoding/ascii85
    src/encoding/asn1
    src/encoding/base32
    src/encoding/base64
    src/encoding/binary
    src/encoding/csv
    src/encoding/gob
    src/encoding/hex
    src/encoding/json
    src/encoding/pem
    src/encoding/xml
    src/errors
    src/expvar
    src/flag
    src/fmt
    src/go
    src/go/ast
    src/go/build
    src/go/build/constraint
    src/go/constant
    src/go/doc
    src/go/doc/comment
    src/go/format
    src/go/importer
    src/go/internal
    src/go/internal/gccgoimporter
    src/go/internal/gcimporter
    src/go/internal/srcimporter
    src/go/internal/typeparams
    src/go/parser
    src/go/printer
    src/go/scanner
    src/go/token
    src/go/types
    src/go/version
    src/hash
    src/hash/adler32
    src/hash/crc32
    src/hash/crc64
    src/hash/fnv
    src/hash/maphash
    src/html
    src/html/template
    src/image
    src/image/color
    src/image/color/palette
    src/image/draw
    src/image/gif
    src/image/internal
    src/image/internal/imageutil
    src/image/jpeg
    src/image/png
    src/index
    src/index/suffixarray
    src/internal
    src/internal/abi
    src/internal/asan
    src/internal/bisect
    src/internal/buildcfg
    src/internal/bytealg
    src/internal/byteorder
    src/internal/cfg
    src/internal/chacha8rand
    src/internal/concurrent
    src/internal/coverage
    src/internal/coverage/calloc
    src/internal/coverage/cfile
    src/internal/coverage/cformat
    src/internal/coverage/cmerge
    src/internal/coverage/decodecounter
    src/internal/coverage/decodemeta
    src/internal/coverage/encodecounter
    src/internal/coverage/encodemeta
    src/internal/coverage/pods
    src/internal/coverage/rtcov
    src/internal/coverage/slicereader
    src/internal/coverage/slicewriter
    src/internal/coverage/stringtab
    src/internal/coverage/test
    src/internal/coverage/uleb128
    src/internal/cpu
    src/internal/dag
    src/internal/diff
    src/internal/filepathlite
    src/internal/fmtsort
    src/internal/fuzz
    src/internal/goarch
    src/internal/godebug
    src/internal/godebugs
    src/internal/goexperiment
    src/internal/goos
    src/internal/goroot
    src/internal/gover
    src/internal/goversion
    src/internal/itoa
    src/internal/lazyregexp
    src/internal/lazytemplate
    src/internal/msan
    src/internal/nettrace
    src/internal/obscuretestdata
    src/internal/oserror
    src/internal/pkgbits
    src/internal/platform
    src/internal/poll
    src/internal/profile
    src/internal/profilerecord
    src/internal/race
    src/internal/reflectlite
    src/internal/runtime
    src/internal/runtime/atomic
    src/internal/runtime/exithook
    src/internal/runtime/syscall
    src/internal/saferio
    src/internal/singleflight
    src/internal/stringslite
    src/internal/syscall
    src/internal/syscall/execenv
    src/internal/syscall/unix
    src/internal/syscall/windows
    src/internal/syscall/windows/registry
    src/internal/syscall/windows/sysdll
    src/internal/sysinfo
    src/internal/testenv
    src/internal/testlog
    src/internal/testpty
    src/internal/trace
    src/internal/trace/event
    src/internal/trace/event/go122
    src/internal/trace/internal
    src/internal/trace/internal/oldtrace
    src/internal/trace/internal/testgen
    src/internal/trace/internal/testgen/go122
    src/internal/trace/raw
    src/internal/trace/testtrace
    src/internal/trace/traceviewer
    src/internal/trace/traceviewer/format
    src/internal/trace/traceviewer/static
    src/internal/trace/version
    src/internal/txtar
    src/internal/types
    src/internal/types/errors
    src/internal/unsafeheader
    src/internal/weak
    src/internal/xcoff
    src/internal/zstd
    src/io
    src/io/fs
    src/io/ioutil
    src/iter
    src/log
    src/log/internal
    src/log/slog
    src/log/slog/internal
    src/log/slog/internal/benchmarks
    src/log/slog/internal/buffer
    src/log/slog/internal/slogtest
    src/log/syslog
    src/maps
    src/math
    src/math/big
    src/math/bits
    src/math/cmplx
    src/math/rand
    src/math/rand/v2
    src/mime
    src/mime/multipart
    src/mime/quotedprintable
    src/net
    src/net/http
    src/net/http/cgi
    src/net/http/cookiejar
    src/net/http/fcgi
    src/net/http/httptest
    src/net/http/httptrace
    src/net/http/httputil
    src/net/http/internal
    src/net/http/internal/ascii
    src/net/http/internal/testcert
    src/net/http/pprof
    src/net/internal
    src/net/internal/socktest
    src/net/mail
    src/net/netip
    src/net/rpc
    src/net/rpc/jsonrpc
    src/net/smtp
    src/net/textproto
    src/net/url
    src/os
    src/os/exec
    src/os/exec/internal
    src/os/exec/internal/fdtest
    src/os/signal
    src/os/user
    src/path
    src/path/filepath
    src/plugin
    src/reflect
    src/reflect/internal
    src/reflect/internal/example1
    src/reflect/internal/example2
    src/regexp
    src/regexp/syntax
    src/runtime
    src/runtime/asan
    src/runtime/cgo
    src/runtime/coverage
    src/runtime/debug
    src/runtime/internal
    src/runtime/internal/math
    src/runtime/internal/startlinetest
    src/runtime/internal/sys
    src/runtime/internal/wasitest
    src/runtime/metrics
    src/runtime/msan
    src/runtime/pprof
    src/runtime/race
    src/runtime/race/internal
    src/runtime/race/internal/amd64v1
    src/runtime/race/internal/amd64v3
    src/runtime/trace
    src/slices
    src/sort
    src/strconv
    src/strings
    src/structs
    src/sync
    src/sync/atomic
    src/syscall
    src/syscall/js
    src/testing
    src/testing/fstest
    src/testing/internal
    src/testing/internal/testdeps
    src/testing/iotest
    src/testing/quick
    src/testing/slogtest
    src/text
    src/text/scanner
    src/text/tabwriter
    src/text/template
    src/text/template/parse
    src/time
    src/time/tzdata
    src/unicode
    src/unicode/utf16
    src/unicode/utf8
    src/unique
    src/unsafe
    src/vendor
    src/vendor/golang.org
    src/vendor/golang.org/x
    src/vendor/golang.org/x/crypto
    src/vendor/golang.org/x/crypto/chacha20
    src/vendor/golang.org/x/crypto/chacha20poly1305
    src/vendor/golang.org/x/crypto/cryptobyte
    src/vendor/golang.org/x/crypto/cryptobyte/asn1
    src/vendor/golang.org/x/crypto/hkdf
    src/vendor/golang.org/x/crypto/internal
    src/vendor/golang.org/x/crypto/internal/alias
    src/vendor/golang.org/x/crypto/internal/poly1305
    src/vendor/golang.org/x/crypto/sha3
    src/vendor/golang.org/x/net
    src/vendor/golang.org/x/net/dns
    src/vendor/golang.org/x/net/dns/dnsmessage
    src/vendor/golang.org/x/net/http
    src/vendor/golang.org/x/net/http2
    src/vendor/golang.org/x/net/http2/hpack
    src/vendor/golang.org/x/net/http/httpguts
    src/vendor/golang.org/x/net/http/httpproxy
    src/vendor/golang.org/x/net/idna
    src/vendor/golang.org/x/net/lif
    src/vendor/golang.org/x/net/nettest
    src/vendor/golang.org/x/net/route
    src/vendor/golang.org/x/sys
    src/vendor/golang.org/x/sys/cpu
    src/vendor/golang.org/x/text
    src/vendor/golang.org/x/text/secure
    src/vendor/golang.org/x/text/secure/bidirule
    src/vendor/golang.org/x/text/transform
    src/vendor/golang.org/x/text/unicode
    src/vendor/golang.org/x/text/unicode/bidi
    src/vendor/golang.org/x/text/unicode/norm
)
