# AUTOMATICALLY GENERATED. DO NOT EDIT!
DB_VERSION = 2

TABLES = {
    "authors": {
        "schema": [
            {'name': 'meta.id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.name', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.age', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'author'},
    },
    "books": {
        "schema": [
            {'name': 'hash', 'type': 'uint64', 'sort_order': 'ascending', 'expression': 'farm_hash([meta.publisher_id])', 'group': 'primary'},
            {'name': 'meta.publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.isbn', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.name', 'type': 'utf8', 'lock': 'web', 'group': 'default'},
            {'name': 'spec.year', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.font', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.genres', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.keywords', 'type': 'any', 'lock': 'search', 'group': 'default'},
            {'name': 'spec.editor_id', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.digital_data', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.author_ids', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.illustrator_id', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.alternative_publisher_ids', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.chapter_descriptions', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.cover_illustrator_id', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.api_revision', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.peer_review.reviewer_ids', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.peer_review.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc$warehouse', 'type': 'any', 'lock': 'warehouse', 'group': 'default'},
            {'name': 'status.released', 'type': 'boolean', 'lock': 'status', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'book'},
    },
    "books_to_publishers": {
        "schema": [
            {'name': 'hash', 'type': 'uint64', 'sort_order': 'ascending', 'expression': 'farm_hash([meta.id], [meta.id2])', 'group': 'default'},
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'meta.id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'meta.publisher_id', 'type': 'int64', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'objects_to_parents', 'type': 'book'},
    },
    "buffered_timestamp_ids": {
        "schema": [
            {'name': 'meta.i64_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.ui64_id', 'type': 'uint64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.i64_value', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'buffered_timestamp_id'},
    },
    "cats": {
        "schema": [
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.breed', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.last_sleep_duration', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.favourite_food', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.favourite_toy', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.revision', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.mood_state', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.health_condition', 'type': 'string', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.eye_color_with_default_yson_storage_type', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.friend_cats_count', 'type': 'int64', 'lock': 'api', 'group': 'default', 'aggregate': 'sum'},
            {'name': 'spec.statistics_for_days_of_year', 'type': 'any', 'lock': 'api', 'group': 'default', 'aggregate': 'first'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.updatable_nested.inner_first', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'status.updatable_nested.inner_second', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'status.updatable_nested.inner_third', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'status.updatable_nested.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.read_only_nested.inner_first', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'status.read_only_nested.inner_second', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'status.read_only_nested.inner_third', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'status.read_only_nested.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.opaque_ro_nested.inner_first', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'status.opaque_ro_nested.inner_second', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'status.opaque_ro_nested.inner_third', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'status.opaque_ro_nested.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.opaque_nested.inner_first', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'status.opaque_nested.inner_second', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'status.opaque_nested.inner_third', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'status.opaque_nested.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'cat'},
    },
    "editors": {
        "schema": [
            {'name': 'meta.id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.achievements', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.phone_number', 'type': 'string', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'editor'},
    },
    "employers": {
        "schema": [
            {'name': 'meta.id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.email', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.salary', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'status', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'employer'},
    },
    "executors": {
        "schema": [
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'executor'},
    },
    "genres": {
        "schema": [
            {'name': 'meta.id', 'type': 'string', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'genre'},
    },
    "groups": {
        "schema": [
            {'name': 'meta.id', 'type': 'string', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'group'},
    },
    "hitchhikers": {
        "schema": [
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.formative_book_id', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.formative_book_id2', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.hated_books', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'hitchhiker'},
    },
    "illustrators": {
        "schema": [
            {'name': 'meta.publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.uid', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.part_time_job', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'illustrator'},
    },
    "illustrators_to_publishers": {
        "schema": [
            {'name': 'meta.uid', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'meta.publisher_id', 'type': 'int64', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'objects_to_parents', 'type': 'illustrator'},
    },
    "indexed_increment_ids": {
        "schema": [
            {'name': 'meta.i64_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'indexed_increment_id'},
    },
    "interceptors": {
        "schema": [
            {'name': 'meta.mother_ship_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.nexus_id', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'interceptor'},
    },
    "interceptors_to_mother_ships": {
        "schema": [
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'meta.mother_ship_id', 'type': 'int64', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'objects_to_parents', 'type': 'interceptor'},
    },
    "manual_ids": {
        "schema": [
            {'name': 'meta.str_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.i64_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.ui64_id', 'type': 'uint64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.str_value', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.i32_value', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.ui32_value', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'manual_id'},
    },
    "mother_ships": {
        "schema": [
            {'name': 'meta.nexus_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.revision', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.release_year', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.executor_id', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.revision', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.sector_names', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.price', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'mother_ship'},
    },
    "mother_ships_to_nexus": {
        "schema": [
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'meta.nexus_id', 'type': 'int64', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'objects_to_parents', 'type': 'mother_ship'},
    },
    "multipolicy_ids": {
        "schema": [
            {'name': 'meta.str_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.i64_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.ui64_id', 'type': 'uint64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.another_ui64_id', 'type': 'uint64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.str_value', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.i64_value', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.ui64_value', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.another_ui64_value', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'multipolicy_id'},
    },
    "nested_columns": {
        "schema": [
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.column_singular', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.column_repeated', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.column_map', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.composite_singular.column_singular', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.composite_singular.column_repeated', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.composite_singular.column_map', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.composite_singular.deprecated_column_singular', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.composite_singular', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.deprecated_column_singular', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'nested_columns'},
    },
    "nexus": {
        "schema": [
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.some_map_to_message_column', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.column_semaphore', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'nexus'},
    },
    "nirvana_dm_process_instances": {
        "schema": [
            {'name': 'meta.id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'nirvana_dm_process_instance'},
    },
    "publishers": {
        "schema": [
            {'name': 'hash', 'type': 'uint64', 'sort_order': 'ascending', 'expression': 'farm_hash([meta.id])', 'group': 'primary'},
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.name', 'type': 'utf8', 'lock': 'web', 'group': 'default'},
            {'name': 'spec.editor_in_chief', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.illustrator_in_chief', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.publisher_group', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.column_field', 'type': 'int64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.featured_illustrators', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.column_field', 'type': 'int64', 'lock': 'worker', 'group': 'default'},
            {'name': 'status.column_list', 'type': 'any', 'lock': 'worker', 'group': 'default'},
            {'name': 'status.featured_illustrators', 'type': 'any', 'lock': 'worker', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'worker', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'publisher'},
    },
    "random_ids": {
        "schema": [
            {'name': 'meta.str_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.i64_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.ui64_id', 'type': 'uint64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.str_value', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'random_id'},
    },
    "schemas": {
        "schema": [
            {'name': 'meta.id', 'type': 'string', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'schema'},
    },
    "semaphores": {
        "schema": [
            {'name': 'meta.semaphore_set_id', 'type': 'string', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.id', 'type': 'string', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'semaphore'},
    },
    "semaphores_to_semaphore_sets": {
        "schema": [
            {'name': 'meta.id', 'type': 'string', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'meta.semaphore_set_id', 'type': 'string', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'objects_to_parents', 'type': 'semaphore'},
    },
    "semaphore_sets": {
        "schema": [
            {'name': 'meta.id', 'type': 'string', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'semaphore_set'},
    },
    "timestamp_ids": {
        "schema": [
            {'name': 'meta.i64_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.ui64_id', 'type': 'uint64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.ui64_value', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'timestamp_id'},
    },
    "typographers": {
        "schema": [
            {'name': 'meta.publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.login', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.test_mandatory_column_field', 'type': 'utf8', 'lock': 'api', 'group': 'default'},
            {'name': 'spec.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'typographer'},
    },
    "typographers_to_publishers": {
        "schema": [
            {'name': 'meta.id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'meta.publisher_id', 'type': 'int64', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'objects_to_parents', 'type': 'typographer'},
    },
    "users": {
        "schema": [
            {'name': 'meta.id', 'type': 'string', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'user'},
    },
    "watch_log_consumers": {
        "schema": [
            {'name': 'meta.id', 'type': 'string', 'sort_order': 'ascending', 'group': 'primary'},
            {'name': 'meta.etc', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'existence_lock', 'type': 'boolean', 'lock': 'existence_lock', 'group': 'default'},
            {'name': 'meta.history_snapshot_timestamp', 'type': 'uint64', 'lock': 'history_lock', 'group': 'default'},
            {'name': 'meta.removal_time', 'type': 'uint64', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.acl', 'type': 'any', 'lock': 'api', 'group': 'primary'},
            {'name': 'meta.creation_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.inherit_acl', 'type': 'boolean', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalization_start_time', 'type': 'uint64', 'lock': 'api', 'group': 'default'},
            {'name': 'meta.finalizers', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'spec', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'status', 'type': 'any', 'lock': 'api', 'group': 'default'},
            {'name': 'labels', 'type': 'any', 'lock': 'api', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'object', 'type': 'watch_log_consumer'},
    },
    "editor_to_books": {
        "schema": [
            {'name': 'hash', 'type': 'uint64', 'sort_order': 'ascending', 'expression': 'farm_hash([editor_id])', 'group': 'default'},
            {'name': 'editor_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'reference'},
    },
    "illustrator_to_books": {
        "schema": [
            {'name': 'illustrator_uid', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'reference'},
    },
    "publishers_to_books": {
        "schema": [
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'reference'},
    },
    "illustrator_to_books_for_cover_illustrator": {
        "schema": [
            {'name': 'illustrator_uid', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'reference'},
    },
    "authors_to_books_for_peer_reviewers": {
        "schema": [
            {'name': 'author_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'reference'},
    },
    "publisher_to_illustrators": {
        "schema": [
            {'name': 'target_publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'source_publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'source_illustrator_uid', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'reference'},
    },
    "executor_to_mother_ships": {
        "schema": [
            {'name': 'executor_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'mother_ship_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'reference'},
    },
    "editor_to_publishers": {
        "schema": [
            {'name': 'editor_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'reference'},
    },
    "illustrator_to_publishers": {
        "schema": [
            {'name': 'illustrator_uid', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'reference'},
    },
    "publisher_to_publishers": {
        "schema": [
            {'name': 'target_publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'source_publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'reference'},
    },
    "illustrators_to_publishers_for_old_featured_illustrators": {
        "schema": [
            {'name': 'illustrator_uid', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'reference'},
    },
    "illustrators_to_publishers_for_new_featured_illustrators": {
        "schema": [
            {'name': 'illustrator_uid', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'reference'},
    },
    "authors_to_books": {
        "schema": [
            {'name': 'author_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'reference'},
    },

    # Builtin tables.
    "annotations": {
        "schema": [
            {"name": "object_id", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "object_type", "type": "int64", "sort_order": "ascending", "group": "default"},
            {"name": "name", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "value", "type": "any", "group": "default"},
        ],
    },
    "subject_to_type": {
        "schema": [
            {"name": "subject_id", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "type", "type": "int64", "group": "default"},
        ],
    },
    "pending_removals": {
        "schema": [
            {"name": "object_type", "type": "int64", "sort_order": "ascending", "group": "default"},
            {"name": "object_id_hash", "type": "uint64", "expression": "farm_hash([object_id])", "sort_order": "ascending", "group": "default"},
            {"name": "object_id", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "removal_time", "type": "uint64", "group": "default"},
        ],
    },
    "history_events": {
        "schema": [
            {
                "name": "hash",
                "type": "uint64",
                "expression": "farm_hash(object_type, object_id)",
                "sort_order": "ascending",
                "group": "default",
            },
            {"name": "object_type", "type": "int64", "sort_order": "ascending", "group": "default"},
            {"name": "object_id", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "time", "type": "uint64", "sort_order": "ascending", "group": "default"},
            {"name": "transaction_id", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "event_type", "type": "int64", "sort_order": "ascending", "group": "default"},
            {"name": "uuid", "type": "string", "lock": "api", "group": "default"},
            {"name": "user", "type": "string", "lock": "api", "group": "default"},
            {"name": "value", "type": "any", "lock": "api", "group": "default"},
            {"name": "history_enabled_attributes", "type": "any", "lock": "api", "group": "default"},
            {"name": "etc", "type": "any", "lock": "api", "group": "default"},
        ],
        "attributes": {
            "in_memory_mode": "none",
        }
    },
    "history_index": {
        "schema": [
            {
                "name": "hash",
                "type": "uint64",
                "expression": "farm_hash(object_type, history_event_type, index_event_type, object_id)",
                "sort_order": "ascending",
                "group": "default",
            },
            {"name": "object_type", "type": "int64", "sort_order": "ascending", "group": "default"},
            {"name": "history_event_type", "type": "int64", "sort_order": "ascending", "group": "default"},
            {"name": "index_event_type", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "object_id", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "time", "type": "uint64", "sort_order": "ascending", "group": "default"},
            {"name": "transaction_id", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "uuid", "type": "string", "lock": "api", "group": "default"},
            {"name": "user", "type": "string", "lock": "api", "group": "default"},
            {"name": "value", "type": "any", "lock": "api", "group": "default"},
            {"name": "etc", "type": "any", "lock": "api", "group": "default"},
        ],
        "attributes": {
            "in_memory_mode": "none",
        }
    },
    "history_events_v2": {
        "schema": [
            {
                "name": "hash",
                "type": "uint64",
                "expression": "farm_hash(object_type, object_id)",
                "sort_order": "ascending",
                "group": "default",
            },
            {"name": "object_type", "type": "int64", "sort_order": "ascending", "group": "default"},
            {"name": "object_id", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "inverted_time", "type": "uint64", "sort_order": "ascending", "group": "default"},
            {"name": "transaction_id", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "event_type", "type": "int64", "sort_order": "ascending", "group": "default"},
            {"name": "uuid", "type": "string", "lock": "api", "group": "default"},
            {"name": "user", "type": "string", "lock": "api", "group": "default"},
            {"name": "value", "type": "any", "lock": "api", "group": "default"},
            {"name": "history_enabled_attributes", "type": "any", "lock": "api", "group": "default"},
            {"name": "etc", "type": "any", "lock": "api", "group": "default"},
        ],
        "attributes": {
            "in_memory_mode": "none",
        }
    },
    "history_index_v2": {
        "schema": [
            {
                "name": "hash",
                "type": "uint64",
                "expression": "farm_hash(object_type, object_id)",
                "sort_order": "ascending",
                "group": "default",
            },
            {"name": "object_type", "type": "int64", "sort_order": "ascending", "group": "default"},
            {"name": "history_event_type", "type": "int64", "sort_order": "ascending", "group": "default"},
            {"name": "index_event_type", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "object_id", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "inverted_time", "type": "uint64", "sort_order": "ascending", "group": "default"},
            {"name": "transaction_id", "type": "string", "sort_order": "ascending", "group": "default"},
            {"name": "uuid", "type": "string", "lock": "api", "group": "default"},
            {"name": "user", "type": "string", "lock": "api", "group": "default"},
            {"name": "value", "type": "any", "lock": "api", "group": "default"},
            {"name": "etc", "type": "any", "lock": "api", "group": "default"},
        ],
        "attributes": {
            "in_memory_mode": "none",
        }
    },
}

WATCH_LOGS = {
    "authors_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "author"},
    },
    "books_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "book"},
    },
    "books_tagged_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "book"},
    },
    "cats_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "cat"},
    },
    "employers_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "employer"},
    },
    "executors_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "executor"},
    },
    "executors_khalai_rank_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "executor"},
    },
    "executors_selector_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "executor"},
    },
    "groups_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "group"},
    },
    "interceptors_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "interceptor"},
    },
    "mother_ships_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "mother_ship"},
    },
    "nexus_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "nexus"},
    },
    "nirvana_dm_process_instances_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "nirvana_dm_process_instance"},
    },
    "publishers_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "publisher"},
    },
    "schemas_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "schema"},
    },
    "users_watch_log": {
        "schema": [
            {"name": "$timestamp", "type": "uint64", "group": "default"},
            {"name": "record", "type": "any", "group": "default"},
        ],
        "attributes": {
            "commit_ordering": "strong",
            "tablet_count": 6,
            "min_data_ttl": 600000,
            "max_data_ttl": 600000,
            "max_data_versions": 1,
            "min_data_versions": 0,
        },
        "orm_flags": {"table_group": "watch_log", "type": "user"},
    },
}

INDEXES = {
    "books_by_cover_dpi": {
        "schema": [
            {'name': 'design_cover_dpi', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_cover_image": {
        "schema": [
            {'name': 'design_cover_image', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_cover_size": {
        "schema": [
            {'name': 'design_cover_size', 'type': 'uint64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_creation_time": {
        "schema": [
            {'name': 'creation_time', 'type': 'uint64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_editor_and_year_with_predicate": {
        "schema": [
            {'name': 'editor_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'year', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_font": {
        "schema": [
            {'name': 'font', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_genres": {
        "schema": [
            {'name': 'genres', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_illustrations": {
        "schema": [
            {'name': 'design_illustrations', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_illustrations_with_predicate": {
        "schema": [
            {'name': 'design_illustrations', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_isbn": {
        "schema": [
            {'name': 'hash', 'type': 'uint64', 'sort_order': 'ascending', 'expression': 'farm_hash([isbn])', 'group': 'default'},
            {'name': 'isbn', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_isbn_with_predicate": {
        "schema": [
            {'name': 'isbn', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_keywords": {
        "schema": [
            {'name': 'hash', 'type': 'uint64', 'sort_order': 'ascending', 'expression': 'farm_hash([keywords])', 'group': 'default'},
            {'name': 'keywords', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_name": {
        "schema": [
            {'name': 'name', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_page_count": {
        "schema": [
            {'name': 'page_count', 'type': 'uint64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_store_rating": {
        "schema": [
            {'name': 'store_rating', 'type': 'double', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_year": {
        "schema": [
            {'name': 'hash', 'type': 'uint64', 'sort_order': 'ascending', 'expression': 'farm_hash([year])', 'group': 'default'},
            {'name': 'year', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_year_and_font": {
        "schema": [
            {'name': 'year', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'font', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_year_and_page_count_with_predicate": {
        "schema": [
            {'name': 'year', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'page_count', 'type': 'uint64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "books_by_cover_size_with_predicate": {
        "schema": [
            {'name': 'year', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'book_id2', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'book'},
    },
    "cats_by_names_with_predicate": {
        "schema": [
            {'name': 'name', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'cat_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'cat'},
    },
    "editors_by_achievements": {
        "schema": [
            {'name': 'achievements', 'type': 'string', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'editor_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'editor'},
    },
    "editors_by_name": {
        "schema": [
            {'name': 'name', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'editor_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'editor'},
    },
    "editors_by_phone_number": {
        "schema": [
            {'name': 'phone_number', 'type': 'string', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'editor_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'editor'},
    },
    "editors_by_post": {
        "schema": [
            {'name': 'post', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'editor_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'editor'},
    },
    "genre_by_name": {
        "schema": [
            {'name': 'name', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'genre_id', 'type': 'string', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'genre'},
    },
    "nirvana_dm_process_instances_by_created": {
        "schema": [
            {'name': 'created', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'nirvana_dm_process_instance_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'nirvana_dm_process_instance'},
    },
    "nirvana_dm_process_instances_by_definition_id": {
        "schema": [
            {'name': 'definition_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'nirvana_dm_process_instance_id', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'nirvana_dm_process_instance'},
    },
    "publishers_by_column_field": {
        "schema": [
            {'name': 'column_field', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'publisher'},
    },
    "publishers_by_number_of_awards": {
        "schema": [
            {'name': 'number_of_awards', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'publisher'},
    },
    "typographers_by_login": {
        "schema": [
            {'name': 'login', 'type': 'utf8', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'publisher_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'typographer_id', 'type': 'int64', 'sort_order': 'ascending', 'group': 'default'},
            {'name': 'dummy', 'type': 'boolean', 'group': 'default'},
        ],
        "orm_flags": {'table_group': 'index', 'type': 'typographer'},
    },
}

TYPES = [
    "author",
    "book",
    "buffered_timestamp_id",
    "cat",
    "editor",
    "employer",
    "executor",
    "genre",
    "group",
    "hitchhiker",
    "illustrator",
    "indexed_increment_id",
    "interceptor",
    "manual_id",
    "mother_ship",
    "multipolicy_id",
    "nested_columns",
    "nexus",
    "nirvana_dm_process_instance",
    "publisher",
    "random_id",
    "schema",
    "semaphore",
    "semaphore_set",
    "timestamp_id",
    "typographer",
    "user",
    "watch_log_consumer",
]

YT_SCHEMA = {
    "tables": TABLES,
    "watch_logs": WATCH_LOGS,
    "indexes": INDEXES,
    "all_tables": dict(list(TABLES.items()) + list(WATCH_LOGS.items()) + list(INDEXES.items())),
    "object_types": TYPES,
    "object_types_set": frozenset(TYPES),
}
