# Generated by devtools/yamaker.

LIBRARY()

LICENSE(
    Apache-2.0 AND
    MIT
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

PEERDIR(
    contrib/clickhouse/src/Common
    contrib/clickhouse/src/Parsers
    contrib/libs/apache/avro
    contrib/libs/aws-sdk-cpp/aws-cpp-sdk-core
    contrib/libs/aws-sdk-cpp/aws-cpp-sdk-s3
    contrib/libs/cctz
    contrib/libs/cctz/tzdata
    contrib/libs/croaring
    contrib/libs/double-conversion
    contrib/libs/farmhash
    contrib/libs/fastops/fastops
    contrib/libs/fmt
    contrib/libs/hashidsxx
    contrib/libs/libc_compat
    contrib/libs/libdivide
    contrib/libs/lz4
    contrib/libs/metrohash
    contrib/libs/miniselect
    contrib/libs/msgpack
    contrib/libs/pdqsort
    contrib/libs/poco/Crypto
    contrib/libs/poco/Data
    contrib/libs/poco/Foundation
    contrib/libs/poco/JSON
    contrib/libs/poco/MongoDB
    contrib/libs/poco/Net
    contrib/libs/poco/NetSSL_OpenSSL
    contrib/libs/poco/Redis
    contrib/libs/poco/Util
    contrib/libs/poco/XML
    contrib/libs/rapidjson
    contrib/libs/re2
    contrib/libs/sparsehash
    contrib/libs/wyhash
    contrib/libs/xxhash
    contrib/libs/zstd
    contrib/restricted/abseil-cpp/absl/container
    contrib/restricted/boost/circular_buffer
    contrib/restricted/boost/context
    contrib/restricted/boost/convert
    contrib/restricted/boost/dynamic_bitset
    contrib/restricted/boost/filesystem
    contrib/restricted/boost/geometry
    contrib/restricted/boost/heap
    contrib/restricted/boost/multi_index
    contrib/restricted/boost/program_options
    contrib/restricted/boost/system
    contrib/restricted/boost/tti
    contrib/restricted/cityhash-1.0.2
    contrib/restricted/dragonbox
    contrib/restricted/fast_float
    contrib/restricted/magic_enum
    contrib/restricted/murmurhash
    contrib/restricted/patched/replxx
    contrib/restricted/turbo_base64
    library/cpp/clickhouse_h3_compat
    library/cpp/consistent_hashing
    library/cpp/re2_st
    library/cpp/sanitizer/include
)

ADDINCL(
    GLOBAL contrib/clickhouse/includes/configs
    GLOBAL contrib/clickhouse/src
    GLOBAL contrib/clickhouse/src/Core/include
    GLOBAL contrib/libs/wyhash
    GLOBAL contrib/libs/xxhash
    GLOBAL contrib/restricted/murmurhash
    contrib/clickhouse/base
    contrib/clickhouse/base/pcg-random
    contrib/clickhouse/contrib/libdivide-cmake
    contrib/libs/apache/avro
    contrib/libs/apache/avro/api
    contrib/libs/croaring/include/roaring
    contrib/libs/double-conversion
    contrib/libs/farmhash
    contrib/libs/fastops
    contrib/libs/hashidsxx
    contrib/libs/libc_compat/include
    contrib/libs/libdivide
    contrib/libs/lz4
    contrib/libs/miniselect/include
    contrib/libs/msgpack/include
    contrib/libs/pdqsort
    contrib/libs/rapidjson/include
    contrib/libs/sparsehash/src
    contrib/libs/zstd/include
    contrib/restricted/cityhash-1.0.2
    contrib/restricted/fast_float/include
    contrib/restricted/turbo_base64
    library/cpp/clickhouse_h3_compat
    library/cpp/consistent_hashing
)

NO_COMPILER_WARNINGS()

NO_UTIL()

IF (OS_DARWIN)
    CFLAGS(
        GLOBAL -DOS_DARWIN
    )
ELSEIF (OS_LINUX)
    CFLAGS(
        GLOBAL -DOS_LINUX
    )
ENDIF()

CFLAGS(
    -DAWS_SDK_VERSION_MAJOR=1
    -DAWS_SDK_VERSION_MINOR=7
    -DAWS_SDK_VERSION_PATCH=231
    -DBOOST_ASIO_HAS_STD_INVOKE_RESULT=1
    -DBOOST_ASIO_STANDALONE=1
    -DENABLE_MULTITARGET_CODE=1
    -DENABLE_OPENSSL_ENCRYPTION
    -DHAS_RESERVED_IDENTIFIER
    -DHAS_SUGGEST_DESTRUCTOR_OVERRIDE
    -DHAS_SUGGEST_OVERRIDE
    -DLZ4_DISABLE_DEPRECATE_WARNINGS=1
    -DPOCO_ENABLE_CPP11
    -DPOCO_HAVE_FD_EPOLL
    -DPOCO_OS_FAMILY_UNIX
    -DSNAPPY_CODEC_AVAILABLE
    -DUNALIGNED_OK
    -DWITH_COVERAGE=0
    -DWITH_GZFILEOP
    -DWITH_TEXT_LOG=1
    -DX86_64
    -DZLIB_COMPAT
    -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS
    -D__GCC_HAVE_DWARF2_CFI_ASM=1
)

SRCS(
    Access/AccessBackup.cpp
    Access/AccessChangesNotifier.cpp
    Access/AccessControl.cpp
    Access/AccessEntityIO.cpp
    Access/AccessRights.cpp
    Access/Authentication.cpp
    Access/CachedAccessChecking.cpp
    Access/Common/AccessEntityType.cpp
    Access/Common/AccessFlags.cpp
    Access/Common/AccessRightsElement.cpp
    Access/Common/AccessType.cpp
    Access/Common/AllowedClientHosts.cpp
    Access/Common/AuthenticationData.cpp
    Access/Common/QuotaDefs.cpp
    Access/Common/RowPolicyDefs.cpp
    Access/ContextAccess.cpp
    Access/Credentials.cpp
    Access/DiskAccessStorage.cpp
    Access/EnabledQuota.cpp
    Access/EnabledRoles.cpp
    Access/EnabledRolesInfo.cpp
    Access/EnabledRowPolicies.cpp
    Access/EnabledSettings.cpp
    Access/ExternalAuthenticators.cpp
    Access/GSSAcceptor.cpp
    Access/GrantedRoles.cpp
    Access/IAccessEntity.cpp
    Access/IAccessStorage.cpp
    Access/KerberosInit.cpp
    Access/LDAPAccessStorage.cpp
    Access/LDAPClient.cpp
    Access/MemoryAccessStorage.cpp
    Access/MultipleAccessStorage.cpp
    Access/Quota.cpp
    Access/QuotaCache.cpp
    Access/QuotaUsage.cpp
    Access/ReplicatedAccessStorage.cpp
    Access/Role.cpp
    Access/RoleCache.cpp
    Access/RolesOrUsersSet.cpp
    Access/RowPolicy.cpp
    Access/RowPolicyCache.cpp
    Access/SettingsConstraints.cpp
    Access/SettingsProfile.cpp
    Access/SettingsProfileElement.cpp
    Access/SettingsProfilesCache.cpp
    Access/SettingsProfilesInfo.cpp
    Access/User.cpp
    Access/UsersConfigAccessStorage.cpp
    AggregateFunctions/AggregateFunctionAggThrow.cpp
    AggregateFunctions/AggregateFunctionAny.cpp
    AggregateFunctions/AggregateFunctionArray.cpp
    AggregateFunctions/AggregateFunctionAvg.cpp
    AggregateFunctions/AggregateFunctionAvgWeighted.cpp
    AggregateFunctions/AggregateFunctionBitwise.cpp
    AggregateFunctions/AggregateFunctionBoundingRatio.cpp
    AggregateFunctions/AggregateFunctionCategoricalInformationValue.cpp
    AggregateFunctions/AggregateFunctionCombinatorFactory.cpp
    AggregateFunctions/AggregateFunctionContingencyCoefficient.cpp
    AggregateFunctions/AggregateFunctionCount.cpp
    AggregateFunctions/AggregateFunctionCramersV.cpp
    AggregateFunctions/AggregateFunctionCramersVBiasCorrected.cpp
    AggregateFunctions/AggregateFunctionDeltaSum.cpp
    AggregateFunctions/AggregateFunctionDeltaSumTimestamp.cpp
    AggregateFunctions/AggregateFunctionDistinct.cpp
    AggregateFunctions/AggregateFunctionEntropy.cpp
    AggregateFunctions/AggregateFunctionExponentialMovingAverage.cpp
    AggregateFunctions/AggregateFunctionFactory.cpp
    AggregateFunctions/AggregateFunctionForEach.cpp
    AggregateFunctions/AggregateFunctionGroupArray.cpp
    AggregateFunctions/AggregateFunctionGroupArrayInsertAt.cpp
    AggregateFunctions/AggregateFunctionGroupArrayMoving.cpp
    AggregateFunctions/AggregateFunctionGroupBitmap.cpp
    AggregateFunctions/AggregateFunctionGroupUniqArray.cpp
    AggregateFunctions/AggregateFunctionHistogram.cpp
    AggregateFunctions/AggregateFunctionIf.cpp
    AggregateFunctions/AggregateFunctionIntervalLengthSum.cpp
    AggregateFunctions/AggregateFunctionMLMethod.cpp
    AggregateFunctions/AggregateFunctionMannWhitney.cpp
    AggregateFunctions/AggregateFunctionMap.cpp
    AggregateFunctions/AggregateFunctionMax.cpp
    AggregateFunctions/AggregateFunctionMaxIntersections.cpp
    AggregateFunctions/AggregateFunctionMeanZTest.cpp
    AggregateFunctions/AggregateFunctionMerge.cpp
    AggregateFunctions/AggregateFunctionMin.cpp
    AggregateFunctions/AggregateFunctionNothing.cpp
    AggregateFunctions/AggregateFunctionNull.cpp
    AggregateFunctions/AggregateFunctionOrFill.cpp
    AggregateFunctions/AggregateFunctionQuantile.cpp
    AggregateFunctions/AggregateFunctionRankCorrelation.cpp
    AggregateFunctions/AggregateFunctionResample.cpp
    AggregateFunctions/AggregateFunctionRetention.cpp
    AggregateFunctions/AggregateFunctionSequenceMatch.cpp
    AggregateFunctions/AggregateFunctionSequenceNextNode.cpp
    AggregateFunctions/AggregateFunctionSimpleLinearRegression.cpp
    AggregateFunctions/AggregateFunctionSimpleState.cpp
    AggregateFunctions/AggregateFunctionSingleValueOrNull.cpp
    AggregateFunctions/AggregateFunctionSparkbar.cpp
    AggregateFunctions/AggregateFunctionState.cpp
    AggregateFunctions/AggregateFunctionStatistics.cpp
    AggregateFunctions/AggregateFunctionStatisticsSimple.cpp
    AggregateFunctions/AggregateFunctionStudentTTest.cpp
    AggregateFunctions/AggregateFunctionSum.cpp
    AggregateFunctions/AggregateFunctionSumCount.cpp
    AggregateFunctions/AggregateFunctionSumMap.cpp
    AggregateFunctions/AggregateFunctionTheilsU.cpp
    AggregateFunctions/AggregateFunctionTopK.cpp
    AggregateFunctions/AggregateFunctionUniq.cpp
    AggregateFunctions/AggregateFunctionUniqCombined.cpp
    AggregateFunctions/AggregateFunctionUniqUpTo.cpp
    AggregateFunctions/AggregateFunctionWelchTTest.cpp
    AggregateFunctions/AggregateFunctionWindowFunnel.cpp
    AggregateFunctions/IAggregateFunction.cpp
    AggregateFunctions/UniqCombinedBiasData.cpp
    AggregateFunctions/UniqVariadicHash.cpp
    AggregateFunctions/parseAggregateFunctionParameters.cpp
    AggregateFunctions/registerAggregateFunctions.cpp
    Backups/BackupCoordinationLocal.cpp
    Backups/BackupCoordinationRemote.cpp
    Backups/BackupCoordinationReplicatedAccess.cpp
    Backups/BackupCoordinationReplicatedTables.cpp
    Backups/BackupCoordinationStage.cpp
    Backups/BackupCoordinationStageSync.cpp
    Backups/BackupEntriesCollector.cpp
    Backups/BackupEntryFromAppendOnlyFile.cpp
    Backups/BackupEntryFromImmutableFile.cpp
    Backups/BackupEntryFromMemory.cpp
    Backups/BackupEntryFromSmallFile.cpp
    Backups/BackupFactory.cpp
    Backups/BackupIO_Disk.cpp
    Backups/BackupIO_File.cpp
    Backups/BackupImpl.cpp
    Backups/BackupInfo.cpp
    Backups/BackupSettings.cpp
    Backups/BackupStatus.cpp
    Backups/BackupUtils.cpp
    Backups/BackupsWorker.cpp
    Backups/DDLAdjustingForBackupVisitor.cpp
    Backups/IBackupEntriesLazyBatch.cpp
    Backups/RestoreCoordinationLocal.cpp
    Backups/RestoreCoordinationRemote.cpp
    Backups/RestoreSettings.cpp
    Backups/RestorerFromBackup.cpp
    Backups/registerBackupEnginesFileAndDisk.cpp
    BridgeHelper/ExternalDictionaryLibraryBridgeHelper.cpp
    BridgeHelper/IBridgeHelper.cpp
    BridgeHelper/LibraryBridgeHelper.cpp
    Client/ClientBase.cpp
    Client/ClientBaseHelpers.cpp
    Client/Connection.cpp
    Client/ConnectionEstablisher.cpp
    Client/ConnectionParameters.cpp
    Client/ConnectionPool.cpp
    Client/ConnectionPoolWithFailover.cpp
    Client/HedgedConnections.cpp
    Client/HedgedConnectionsFactory.cpp
    Client/IConnections.cpp
    Client/InternalTextLogs.cpp
    Client/LocalConnection.cpp
    Client/MultiplexedConnections.cpp
    Client/QueryFuzzer.cpp
    Client/Suggest.cpp
    Client/TestHint.cpp
    Client/TestTags.cpp
    Columns/Collator.cpp
    Columns/ColumnAggregateFunction.cpp
    Columns/ColumnArray.cpp
    Columns/ColumnCompressed.cpp
    Columns/ColumnConst.cpp
    Columns/ColumnDecimal.cpp
    Columns/ColumnFixedString.cpp
    Columns/ColumnFunction.cpp
    Columns/ColumnLowCardinality.cpp
    Columns/ColumnMap.cpp
    Columns/ColumnNullable.cpp
    Columns/ColumnObject.cpp
    Columns/ColumnSparse.cpp
    Columns/ColumnString.cpp
    Columns/ColumnTuple.cpp
    Columns/ColumnVector.cpp
    Columns/ColumnsCommon.cpp
    Columns/FilterDescription.cpp
    Columns/IColumn.cpp
    Columns/MaskOperations.cpp
    Columns/getLeastSuperColumn.cpp
    Compression/CachedCompressedReadBuffer.cpp
    Compression/CheckingCompressedReadBuffer.cpp
    Compression/CompressedReadBuffer.cpp
    Compression/CompressedReadBufferBase.cpp
    Compression/CompressedReadBufferFromFile.cpp
    Compression/CompressedWriteBuffer.cpp
    Compression/CompressionCodecDeflateQpl.cpp
    Compression/CompressionCodecDelta.cpp
    Compression/CompressionCodecDoubleDelta.cpp
    Compression/CompressionCodecEncrypted.cpp
    Compression/CompressionCodecFPC.cpp
    Compression/CompressionCodecGorilla.cpp
    Compression/CompressionCodecLZ4.cpp
    Compression/CompressionCodecMultiple.cpp
    Compression/CompressionCodecNone.cpp
    Compression/CompressionCodecT64.cpp
    Compression/CompressionCodecZSTD.cpp
    Compression/CompressionFactory.cpp
    Compression/CompressionFactoryAdditions.cpp
    Compression/ICompressionCodec.cpp
    Compression/LZ4_decompress_faster.cpp
    Compression/getCompressionCodecForFile.cpp
    Core/BackgroundSchedulePool.cpp
    Core/BaseSettings.cpp
    Core/Block.cpp
    Core/BlockInfo.cpp
    Core/ColumnWithTypeAndName.cpp
    Core/ExternalResultDescription.cpp
    Core/ExternalTable.cpp
    Core/Field.cpp
    Core/InterpolateDescription.cpp
    Core/Joins.cpp
    Core/MySQL/Authentication.cpp
    Core/MySQL/IMySQLReadPacket.cpp
    Core/MySQL/IMySQLWritePacket.cpp
    Core/MySQL/MySQLClient.cpp
    Core/MySQL/MySQLGtid.cpp
    Core/MySQL/MySQLReplication.cpp
    Core/MySQL/PacketEndpoint.cpp
    Core/MySQL/PacketsConnection.cpp
    Core/MySQL/PacketsGeneric.cpp
    Core/MySQL/PacketsProtocolText.cpp
    Core/MySQL/PacketsReplication.cpp
    Core/NamesAndTypes.cpp
    Core/PostgreSQLProtocol.cpp
    Core/QueryProcessingStage.cpp
    Core/ServerUUID.cpp
    Core/Settings.cpp
    Core/SettingsEnums.cpp
    Core/SettingsFields.cpp
    Core/SettingsQuirks.cpp
    Core/SortDescription.cpp
    Core/UUID.cpp
    Core/iostream_debug_helpers.cpp
    Daemon/BaseDaemon.cpp
    Daemon/GraphiteWriter.cpp
    Daemon/SentryWriter.cpp
    DataTypes/DataTypeAggregateFunction.cpp
    DataTypes/DataTypeArray.cpp
    DataTypes/DataTypeCustomGeo.cpp
    DataTypes/DataTypeCustomIPv4AndIPv6.cpp
    DataTypes/DataTypeCustomSimpleAggregateFunction.cpp
    DataTypes/DataTypeDate.cpp
    DataTypes/DataTypeDate32.cpp
    DataTypes/DataTypeDateTime.cpp
    DataTypes/DataTypeDateTime64.cpp
    DataTypes/DataTypeDecimalBase.cpp
    DataTypes/DataTypeDomainBool.cpp
    DataTypes/DataTypeEnum.cpp
    DataTypes/DataTypeFactory.cpp
    DataTypes/DataTypeFixedString.cpp
    DataTypes/DataTypeFunction.cpp
    DataTypes/DataTypeInterval.cpp
    DataTypes/DataTypeLowCardinality.cpp
    DataTypes/DataTypeLowCardinalityHelpers.cpp
    DataTypes/DataTypeMap.cpp
    DataTypes/DataTypeNested.cpp
    DataTypes/DataTypeNothing.cpp
    DataTypes/DataTypeNullable.cpp
    DataTypes/DataTypeNumberBase.cpp
    DataTypes/DataTypeObject.cpp
    DataTypes/DataTypeString.cpp
    DataTypes/DataTypeTuple.cpp
    DataTypes/DataTypeUUID.cpp
    DataTypes/DataTypesDecimal.cpp
    DataTypes/DataTypesNumber.cpp
    DataTypes/EnumValues.cpp
    DataTypes/FieldToDataType.cpp
    DataTypes/IDataType.cpp
    DataTypes/NestedUtils.cpp
    DataTypes/ObjectUtils.cpp
    DataTypes/Serializations/ISerialization.cpp
    DataTypes/Serializations/JSONDataParser.cpp
    DataTypes/Serializations/PathInData.cpp
    DataTypes/Serializations/SerializationAggregateFunction.cpp
    DataTypes/Serializations/SerializationArray.cpp
    DataTypes/Serializations/SerializationBool.cpp
    DataTypes/Serializations/SerializationCustomSimpleText.cpp
    DataTypes/Serializations/SerializationDate.cpp
    DataTypes/Serializations/SerializationDate32.cpp
    DataTypes/Serializations/SerializationDateTime.cpp
    DataTypes/Serializations/SerializationDateTime64.cpp
    DataTypes/Serializations/SerializationDecimal.cpp
    DataTypes/Serializations/SerializationDecimalBase.cpp
    DataTypes/Serializations/SerializationEnum.cpp
    DataTypes/Serializations/SerializationFixedString.cpp
    DataTypes/Serializations/SerializationIP.cpp
    DataTypes/Serializations/SerializationInfo.cpp
    DataTypes/Serializations/SerializationInfoTuple.cpp
    DataTypes/Serializations/SerializationLowCardinality.cpp
    DataTypes/Serializations/SerializationMap.cpp
    DataTypes/Serializations/SerializationNamed.cpp
    DataTypes/Serializations/SerializationNothing.cpp
    DataTypes/Serializations/SerializationNullable.cpp
    DataTypes/Serializations/SerializationNumber.cpp
    DataTypes/Serializations/SerializationObject.cpp
    DataTypes/Serializations/SerializationSparse.cpp
    DataTypes/Serializations/SerializationString.cpp
    DataTypes/Serializations/SerializationTuple.cpp
    DataTypes/Serializations/SerializationUUID.cpp
    DataTypes/Serializations/SerializationWrapper.cpp
    DataTypes/convertMySQLDataType.cpp
    DataTypes/getLeastSupertype.cpp
    DataTypes/getMostSubtype.cpp
    DataTypes/hasNullable.cpp
    DataTypes/registerDataTypeDateTime.cpp
    DataTypes/transformTypesRecursively.cpp
    Databases/DDLDependencyVisitor.cpp
    Databases/DDLRenamingVisitor.cpp
    Databases/DatabaseAtomic.cpp
    Databases/DatabaseDictionary.cpp
    Databases/DatabaseFactory.cpp
    Databases/DatabaseLazy.cpp
    Databases/DatabaseMemory.cpp
    Databases/DatabaseOnDisk.cpp
    Databases/DatabaseOrdinary.cpp
    Databases/DatabaseReplicated.cpp
    Databases/DatabaseReplicatedHelpers.cpp
    Databases/DatabaseReplicatedSettings.cpp
    Databases/DatabaseReplicatedWorker.cpp
    Databases/DatabasesCommon.cpp
    Databases/IDatabase.cpp
    Databases/LoadingStrictnessLevel.cpp
    Databases/MySQL/ConnectionMySQLSettings.cpp
    Databases/MySQL/DatabaseMaterializedMySQL.cpp
    Databases/MySQL/DatabaseMySQL.cpp
    Databases/MySQL/FetchTablesColumnsList.cpp
    Databases/MySQL/MaterializeMetadata.cpp
    Databases/MySQL/MaterializedMySQLSettings.cpp
    Databases/MySQL/MaterializedMySQLSyncThread.cpp
    Databases/TablesLoader.cpp
    Dictionaries/CacheDictionary.cpp
    Dictionaries/CacheDictionaryUpdateQueue.cpp
    Dictionaries/CassandraDictionarySource.cpp
    Dictionaries/CassandraHelpers.cpp
    Dictionaries/CassandraSource.cpp
    Dictionaries/ClickHouseDictionarySource.cpp
    Dictionaries/DictionaryFactory.cpp
    Dictionaries/DictionaryHelpers.cpp
    Dictionaries/DictionarySource.cpp
    Dictionaries/DictionarySourceFactory.cpp
    Dictionaries/DictionarySourceHelpers.cpp
    Dictionaries/DictionaryStructure.cpp
    Dictionaries/DirectDictionary.cpp
    Dictionaries/Embedded/GeoDictionariesLoader.cpp
    Dictionaries/Embedded/GeodataProviders/HierarchiesProvider.cpp
    Dictionaries/Embedded/GeodataProviders/HierarchyFormatReader.cpp
    Dictionaries/Embedded/GeodataProviders/NamesFormatReader.cpp
    Dictionaries/Embedded/GeodataProviders/NamesProvider.cpp
    Dictionaries/Embedded/RegionsHierarchies.cpp
    Dictionaries/Embedded/RegionsHierarchy.cpp
    Dictionaries/Embedded/RegionsNames.cpp
    Dictionaries/ExecutableDictionarySource.cpp
    Dictionaries/ExecutablePoolDictionarySource.cpp
    Dictionaries/ExternalQueryBuilder.cpp
    Dictionaries/FileDictionarySource.cpp
    Dictionaries/FlatDictionary.cpp
    Dictionaries/HTTPDictionarySource.cpp
    Dictionaries/HashedArrayDictionary.cpp
    Dictionaries/HashedDictionary.cpp
    Dictionaries/HierarchyDictionariesUtils.cpp
    Dictionaries/IPAddressDictionary.cpp
    Dictionaries/LibraryDictionarySource.cpp
    Dictionaries/MongoDBDictionarySource.cpp
    Dictionaries/MySQLDictionarySource.cpp
    Dictionaries/PolygonDictionary.cpp
    Dictionaries/PolygonDictionaryImplementations.cpp
    Dictionaries/PolygonDictionaryUtils.cpp
    Dictionaries/PostgreSQLDictionarySource.cpp
    Dictionaries/RangeHashedDictionary.cpp
    Dictionaries/RedisDictionarySource.cpp
    Dictionaries/RedisSource.cpp
    Dictionaries/XDBCDictionarySource.cpp
    Dictionaries/getDictionaryConfigurationFromAST.cpp
    Dictionaries/readInvalidateQuery.cpp
    Dictionaries/registerCacheDictionaries.cpp
    Dictionaries/registerDictionaries.cpp
    Disks/DiskDecorator.cpp
    Disks/DiskEncrypted.cpp
    Disks/DiskFactory.cpp
    Disks/DiskLocal.cpp
    Disks/DiskLocalCheckThread.cpp
    Disks/DiskMemory.cpp
    Disks/DiskRestartProxy.cpp
    Disks/DiskSelector.cpp
    Disks/IDisk.cpp
    Disks/IO/AsynchronousReadIndirectBufferFromRemoteFS.cpp
    Disks/IO/CachedOnDiskReadBufferFromFile.cpp
    Disks/IO/CachedOnDiskWriteBufferFromFile.cpp
    Disks/IO/ReadBufferFromAzureBlobStorage.cpp
    Disks/IO/ReadBufferFromRemoteFSGather.cpp
    Disks/IO/ReadBufferFromWebServer.cpp
    Disks/IO/ReadIndirectBufferFromRemoteFS.cpp
    Disks/IO/ThreadPoolReader.cpp
    Disks/IO/ThreadPoolRemoteFSReader.cpp
    Disks/IO/WriteBufferFromAzureBlobStorage.cpp
    Disks/IO/WriteIndirectBufferFromRemoteFS.cpp
    Disks/IO/createReadBufferFromFileBase.cpp
    Disks/IStoragePolicy.cpp
    Disks/IVolume.cpp
    Disks/LocalDirectorySyncGuard.cpp
    Disks/ObjectStorages/Cached/CachedObjectStorage.cpp
    Disks/ObjectStorages/Cached/registerDiskCache.cpp
    Disks/ObjectStorages/DiskObjectStorage.cpp
    Disks/ObjectStorages/DiskObjectStorageCommon.cpp
    Disks/ObjectStorages/DiskObjectStorageMetadata.cpp
    Disks/ObjectStorages/DiskObjectStorageRemoteMetadataRestoreHelper.cpp
    Disks/ObjectStorages/DiskObjectStorageTransaction.cpp
    Disks/ObjectStorages/FakeMetadataStorageFromDisk.cpp
    Disks/ObjectStorages/IObjectStorage.cpp
    Disks/ObjectStorages/LocalObjectStorage.cpp
    Disks/ObjectStorages/MetadataFromDiskTransactionState.cpp
    Disks/ObjectStorages/MetadataStorageFromDisk.cpp
    Disks/ObjectStorages/MetadataStorageFromDiskTransactionOperations.cpp
    Disks/ObjectStorages/S3/ProxyListConfiguration.cpp
    Disks/ObjectStorages/S3/ProxyResolverConfiguration.cpp
    Disks/ObjectStorages/S3/S3Capabilities.cpp
    Disks/ObjectStorages/S3/S3ObjectStorage.cpp
    Disks/ObjectStorages/S3/diskSettings.cpp
    Disks/ObjectStorages/S3/registerDiskS3.cpp
    Disks/ObjectStorages/StoredObject.cpp
    Disks/ObjectStorages/Web/MetadataStorageFromStaticFilesWebServer.cpp
    Disks/ObjectStorages/Web/WebObjectStorage.cpp
    Disks/ObjectStorages/Web/registerDiskWebServer.cpp
    Disks/StoragePolicy.cpp
    Disks/TemporaryFileOnDisk.cpp
    Disks/VolumeJBOD.cpp
    Disks/createVolume.cpp
    Disks/registerDisks.cpp
    Formats/CapnProtoUtils.cpp
    Formats/ColumnMapping.cpp
    Formats/EscapingRuleUtils.cpp
    Formats/FormatFactory.cpp
    Formats/FormatSchemaInfo.cpp
    Formats/IndexForNativeFormat.cpp
    Formats/JSONUtils.cpp
    Formats/NativeReader.cpp
    Formats/NativeWriter.cpp
    Formats/ParsedTemplateFormatString.cpp
    Formats/ProtobufReader.cpp
    Formats/ProtobufSchemas.cpp
    Formats/ProtobufSerializer.cpp
    Formats/ProtobufWriter.cpp
    Formats/ReadSchemaUtils.cpp
    Formats/RowInputMissingColumnsFiller.cpp
    Formats/TemporaryFileStream.cpp
    Formats/formatBlock.cpp
    Formats/registerFormats.cpp
    Formats/registerWithNamesAndTypes.cpp
    Formats/verbosePrintString.cpp
    Functions/GatherUtils/concat.cpp
    Functions/GatherUtils/createArraySink.cpp
    Functions/GatherUtils/createArraySource.cpp
    Functions/GatherUtils/createValueSource.cpp
    Functions/GatherUtils/ends_with.cpp
    Functions/GatherUtils/has_all.cpp
    Functions/GatherUtils/has_any.cpp
    Functions/GatherUtils/has_substr.cpp
    Functions/GatherUtils/push.cpp
    Functions/GatherUtils/resizeConstantSize.cpp
    Functions/GatherUtils/resizeDynamicSize.cpp
    Functions/GatherUtils/sliceDynamicOffsetBounded.cpp
    Functions/GatherUtils/sliceDynamicOffsetUnbounded.cpp
    Functions/GatherUtils/sliceFromLeftConstantOffsetBounded.cpp
    Functions/GatherUtils/sliceFromLeftConstantOffsetUnbounded.cpp
    Functions/GatherUtils/sliceFromLeftDynamicLength.cpp
    Functions/GatherUtils/sliceFromRightConstantOffsetBounded.cpp
    Functions/GatherUtils/sliceFromRightConstantOffsetUnbounded.cpp
    Functions/GatherUtils/sliceFromRightDynamicLength.cpp
    Functions/GatherUtils/starts_with.cpp
    Functions/JSONPath/Parsers/ParserJSONPath.cpp
    Functions/JSONPath/Parsers/ParserJSONPathMemberAccess.cpp
    Functions/JSONPath/Parsers/ParserJSONPathQuery.cpp
    Functions/JSONPath/Parsers/ParserJSONPathRange.cpp
    Functions/JSONPath/Parsers/ParserJSONPathRoot.cpp
    Functions/JSONPath/Parsers/ParserJSONPathStar.cpp
    Functions/divide/divide.cpp
    GLOBAL Functions/CRC.cpp
    GLOBAL Functions/CastOverloadResolver.cpp
    GLOBAL Functions/FunctionChar.cpp
    GLOBAL Functions/FunctionFQDN.cpp
    GLOBAL Functions/FunctionFactory.cpp
    GLOBAL Functions/FunctionFile.cpp
    GLOBAL Functions/FunctionHashID.cpp
    GLOBAL Functions/FunctionHelpers.cpp
    GLOBAL Functions/FunctionJoinGet.cpp
    GLOBAL Functions/FunctionSQLJSON.cpp
    GLOBAL Functions/FunctionShowCertificate.cpp
    GLOBAL Functions/FunctionsAES.cpp
    GLOBAL Functions/FunctionsBase58.cpp
    GLOBAL Functions/FunctionsBinaryRepresentation.cpp
    GLOBAL Functions/FunctionsBitToArray.cpp
    GLOBAL Functions/FunctionsBitmap.cpp
    GLOBAL Functions/FunctionsCharsetClassification.cpp
    GLOBAL Functions/FunctionsCodingIP.cpp
    GLOBAL Functions/FunctionsCodingUUID.cpp
    GLOBAL Functions/FunctionsConversion.cpp
    GLOBAL Functions/FunctionsEmbeddedDictionaries.cpp
    GLOBAL Functions/FunctionsExternalDictionaries.cpp
    GLOBAL Functions/FunctionsHashing.cpp
    GLOBAL Functions/FunctionsJSON.cpp
    GLOBAL Functions/FunctionsLanguageClassification.cpp
    GLOBAL Functions/FunctionsLogical.cpp
    GLOBAL Functions/FunctionsProgrammingClassification.cpp
    GLOBAL Functions/FunctionsRandom.cpp
    GLOBAL Functions/FunctionsRound.cpp
    GLOBAL Functions/FunctionsStringArray.cpp
    GLOBAL Functions/FunctionsStringHash.cpp
    GLOBAL Functions/FunctionsStringSimilarity.cpp
    GLOBAL Functions/FunctionsTimeWindow.cpp
    GLOBAL Functions/FunctionsTonalityClassification.cpp
    GLOBAL Functions/FunctionsTransactionCounters.cpp
    GLOBAL Functions/GeoHash.cpp
    GLOBAL Functions/IFunction.cpp
    GLOBAL Functions/SubtractSubSeconds.cpp
    GLOBAL Functions/URL/URLHierarchy.cpp
    GLOBAL Functions/URL/URLPathHierarchy.cpp
    GLOBAL Functions/URL/basename.cpp
    GLOBAL Functions/URL/cutFragment.cpp
    GLOBAL Functions/URL/cutQueryString.cpp
    GLOBAL Functions/URL/cutQueryStringAndFragment.cpp
    GLOBAL Functions/URL/cutToFirstSignificantSubdomain.cpp
    GLOBAL Functions/URL/cutToFirstSignificantSubdomainCustom.cpp
    GLOBAL Functions/URL/cutURLParameter.cpp
    GLOBAL Functions/URL/cutWWW.cpp
    GLOBAL Functions/URL/decodeURLComponent.cpp
    GLOBAL Functions/URL/domain.cpp
    GLOBAL Functions/URL/domainWithoutWWW.cpp
    GLOBAL Functions/URL/extractURLParameter.cpp
    GLOBAL Functions/URL/extractURLParameterNames.cpp
    GLOBAL Functions/URL/extractURLParameters.cpp
    GLOBAL Functions/URL/firstSignificantSubdomain.cpp
    GLOBAL Functions/URL/firstSignificantSubdomainCustom.cpp
    GLOBAL Functions/URL/fragment.cpp
    GLOBAL Functions/URL/netloc.cpp
    GLOBAL Functions/URL/path.cpp
    GLOBAL Functions/URL/pathFull.cpp
    GLOBAL Functions/URL/port.cpp
    GLOBAL Functions/URL/protocol.cpp
    GLOBAL Functions/URL/queryString.cpp
    GLOBAL Functions/URL/queryStringAndFragment.cpp
    GLOBAL Functions/URL/tldLookup.generated.cpp
    GLOBAL Functions/URL/topLevelDomain.cpp
    GLOBAL Functions/abs.cpp
    GLOBAL Functions/acos.cpp
    GLOBAL Functions/acosh.cpp
    GLOBAL Functions/addDays.cpp
    GLOBAL Functions/addHours.cpp
    GLOBAL Functions/addMinutes.cpp
    GLOBAL Functions/addMonths.cpp
    GLOBAL Functions/addQuarters.cpp
    GLOBAL Functions/addSeconds.cpp
    GLOBAL Functions/addSubSeconds.cpp
    GLOBAL Functions/addWeeks.cpp
    GLOBAL Functions/addYears.cpp
    GLOBAL Functions/addressToLine.cpp
    GLOBAL Functions/addressToLineWithInlines.cpp
    GLOBAL Functions/addressToSymbol.cpp
    GLOBAL Functions/aes_decrypt_mysql.cpp
    GLOBAL Functions/aes_encrypt_mysql.cpp
    GLOBAL Functions/appendTrailingCharIfAbsent.cpp
    GLOBAL Functions/array/array.cpp
    GLOBAL Functions/array/arrayAUC.cpp
    GLOBAL Functions/array/arrayAggregation.cpp
    GLOBAL Functions/array/arrayAll.cpp
    GLOBAL Functions/array/arrayCompact.cpp
    GLOBAL Functions/array/arrayConcat.cpp
    GLOBAL Functions/array/arrayCount.cpp
    GLOBAL Functions/array/arrayCumSum.cpp
    GLOBAL Functions/array/arrayCumSumNonNegative.cpp
    GLOBAL Functions/array/arrayDifference.cpp
    GLOBAL Functions/array/arrayDistance.cpp
    GLOBAL Functions/array/arrayDistinct.cpp
    GLOBAL Functions/array/arrayElement.cpp
    GLOBAL Functions/array/arrayEnumerate.cpp
    GLOBAL Functions/array/arrayEnumerateDense.cpp
    GLOBAL Functions/array/arrayEnumerateDenseRanked.cpp
    GLOBAL Functions/array/arrayEnumerateRanked.cpp
    GLOBAL Functions/array/arrayEnumerateUniq.cpp
    GLOBAL Functions/array/arrayEnumerateUniqRanked.cpp
    GLOBAL Functions/array/arrayExists.cpp
    GLOBAL Functions/array/arrayFill.cpp
    GLOBAL Functions/array/arrayFilter.cpp
    GLOBAL Functions/array/arrayFirstLast.cpp
    GLOBAL Functions/array/arrayFirstLastIndex.cpp
    GLOBAL Functions/array/arrayFlatten.cpp
    GLOBAL Functions/array/arrayIntersect.cpp
    GLOBAL Functions/array/arrayJoin.cpp
    GLOBAL Functions/array/arrayMap.cpp
    GLOBAL Functions/array/arrayNorm.cpp
    GLOBAL Functions/array/arrayPopBack.cpp
    GLOBAL Functions/array/arrayPopFront.cpp
    GLOBAL Functions/array/arrayPushBack.cpp
    GLOBAL Functions/array/arrayPushFront.cpp
    GLOBAL Functions/array/arrayReduce.cpp
    GLOBAL Functions/array/arrayReduceInRanges.cpp
    GLOBAL Functions/array/arrayResize.cpp
    GLOBAL Functions/array/arrayReverse.cpp
    GLOBAL Functions/array/arraySlice.cpp
    GLOBAL Functions/array/arraySort.cpp
    GLOBAL Functions/array/arraySplit.cpp
    GLOBAL Functions/array/arrayUniq.cpp
    GLOBAL Functions/array/arrayWithConstant.cpp
    GLOBAL Functions/array/arrayZip.cpp
    GLOBAL Functions/array/countEqual.cpp
    GLOBAL Functions/array/emptyArray.cpp
    GLOBAL Functions/array/emptyArrayToSingle.cpp
    GLOBAL Functions/array/has.cpp
    GLOBAL Functions/array/hasAll.cpp
    GLOBAL Functions/array/hasAny.cpp
    GLOBAL Functions/array/hasSubstr.cpp
    GLOBAL Functions/array/indexOf.cpp
    GLOBAL Functions/array/length.cpp
    GLOBAL Functions/array/mapOp.cpp
    GLOBAL Functions/array/mapPopulateSeries.cpp
    GLOBAL Functions/array/range.cpp
    GLOBAL Functions/asin.cpp
    GLOBAL Functions/asinh.cpp
    GLOBAL Functions/assumeNotNull.cpp
    GLOBAL Functions/atan.cpp
    GLOBAL Functions/atan2.cpp
    GLOBAL Functions/atanh.cpp
    GLOBAL Functions/bar.cpp
    GLOBAL Functions/base64Decode.cpp
    GLOBAL Functions/base64Encode.cpp
    GLOBAL Functions/bitAnd.cpp
    GLOBAL Functions/bitBoolMaskAnd.cpp
    GLOBAL Functions/bitBoolMaskOr.cpp
    GLOBAL Functions/bitCount.cpp
    GLOBAL Functions/bitHammingDistance.cpp
    GLOBAL Functions/bitNot.cpp
    GLOBAL Functions/bitOr.cpp
    GLOBAL Functions/bitRotateLeft.cpp
    GLOBAL Functions/bitRotateRight.cpp
    GLOBAL Functions/bitShiftLeft.cpp
    GLOBAL Functions/bitShiftRight.cpp
    GLOBAL Functions/bitSlice.cpp
    GLOBAL Functions/bitSwapLastTwo.cpp
    GLOBAL Functions/bitTest.cpp
    GLOBAL Functions/bitTestAll.cpp
    GLOBAL Functions/bitTestAny.cpp
    GLOBAL Functions/bitWrapperFunc.cpp
    GLOBAL Functions/bitXor.cpp
    GLOBAL Functions/blockNumber.cpp
    GLOBAL Functions/blockSerializedSize.cpp
    GLOBAL Functions/blockSize.cpp
    GLOBAL Functions/byteSize.cpp
    GLOBAL Functions/caseWithExpression.cpp
    GLOBAL Functions/castOrDefault.cpp
    GLOBAL Functions/cbrt.cpp
    GLOBAL Functions/checkHyperscanRegexp.cpp
    GLOBAL Functions/coalesce.cpp
    GLOBAL Functions/concat.cpp
    GLOBAL Functions/connectionId.cpp
    GLOBAL Functions/convertCharset.cpp
    GLOBAL Functions/cos.cpp
    GLOBAL Functions/cosh.cpp
    GLOBAL Functions/countDigits.cpp
    GLOBAL Functions/countMatches.cpp
    GLOBAL Functions/countSubstrings.cpp
    GLOBAL Functions/countSubstringsCaseInsensitive.cpp
    GLOBAL Functions/countSubstringsCaseInsensitiveUTF8.cpp
    GLOBAL Functions/currentDatabase.cpp
    GLOBAL Functions/currentProfiles.cpp
    GLOBAL Functions/currentRoles.cpp
    GLOBAL Functions/currentUser.cpp
    GLOBAL Functions/dateDiff.cpp
    GLOBAL Functions/dateName.cpp
    GLOBAL Functions/date_trunc.cpp
    GLOBAL Functions/decodeXMLComponent.cpp
    GLOBAL Functions/decrypt.cpp
    GLOBAL Functions/defaultValueOfArgumentType.cpp
    GLOBAL Functions/defaultValueOfTypeName.cpp
    GLOBAL Functions/degrees.cpp
    GLOBAL Functions/demange.cpp
    GLOBAL Functions/divide.cpp
    GLOBAL Functions/dumpColumnStructure.cpp
    GLOBAL Functions/empty.cpp
    GLOBAL Functions/encodeXMLComponent.cpp
    GLOBAL Functions/encrypt.cpp
    GLOBAL Functions/endsWith.cpp
    GLOBAL Functions/equals.cpp
    GLOBAL Functions/erf.cpp
    GLOBAL Functions/erfc.cpp
    GLOBAL Functions/errorCodeToName.cpp
    GLOBAL Functions/evalMLMethod.cpp
    GLOBAL Functions/exp.cpp
    GLOBAL Functions/exp10.cpp
    GLOBAL Functions/exp2.cpp
    GLOBAL Functions/extract.cpp
    GLOBAL Functions/extractAllGroupsHorizontal.cpp
    GLOBAL Functions/extractAllGroupsVertical.cpp
    GLOBAL Functions/extractGroups.cpp
    GLOBAL Functions/extractTextFromHTML.cpp
    GLOBAL Functions/extractTimeZoneFromFunctionArguments.cpp
    GLOBAL Functions/filesystem.cpp
    GLOBAL Functions/finalizeAggregation.cpp
    GLOBAL Functions/flattenTuple.cpp
    GLOBAL Functions/formatDateTime.cpp
    GLOBAL Functions/formatReadableQuantity.cpp
    GLOBAL Functions/formatReadableSize.cpp
    GLOBAL Functions/formatReadableTimeDelta.cpp
    GLOBAL Functions/formatRow.cpp
    GLOBAL Functions/formatString.cpp
    GLOBAL Functions/fromModifiedJulianDay.cpp
    GLOBAL Functions/fromUnixTimestamp64Micro.cpp
    GLOBAL Functions/fromUnixTimestamp64Milli.cpp
    GLOBAL Functions/fromUnixTimestamp64Nano.cpp
    GLOBAL Functions/fuzzBits.cpp
    GLOBAL Functions/gcd.cpp
    GLOBAL Functions/generateUUIDv4.cpp
    GLOBAL Functions/geoToH3.cpp
    GLOBAL Functions/geoToS2.cpp
    GLOBAL Functions/geohashDecode.cpp
    GLOBAL Functions/geohashEncode.cpp
    GLOBAL Functions/geohashesInBox.cpp
    GLOBAL Functions/getFuzzerData.cpp
    GLOBAL Functions/getMacro.cpp
    GLOBAL Functions/getScalar.cpp
    GLOBAL Functions/getServerPort.cpp
    GLOBAL Functions/getSetting.cpp
    GLOBAL Functions/getSizeOfEnumType.cpp
    GLOBAL Functions/getTypeSerializationStreams.cpp
    GLOBAL Functions/globalVariable.cpp
    GLOBAL Functions/greatCircleDistance.cpp
    GLOBAL Functions/greater.cpp
    GLOBAL Functions/greaterOrEquals.cpp
    GLOBAL Functions/greatest.cpp
    GLOBAL Functions/h3CellAreaM2.cpp
    GLOBAL Functions/h3CellAreaRads2.cpp
    GLOBAL Functions/h3Distance.cpp
    GLOBAL Functions/h3EdgeAngle.cpp
    GLOBAL Functions/h3EdgeLengthKm.cpp
    GLOBAL Functions/h3EdgeLengthM.cpp
    GLOBAL Functions/h3ExactEdgeLengthKm.cpp
    GLOBAL Functions/h3ExactEdgeLengthM.cpp
    GLOBAL Functions/h3ExactEdgeLengthRads.cpp
    GLOBAL Functions/h3GetBaseCell.cpp
    GLOBAL Functions/h3GetDestinationIndexFromUnidirectionalEdge.cpp
    GLOBAL Functions/h3GetFaces.cpp
    GLOBAL Functions/h3GetIndexesFromUnidirectionalEdge.cpp
    GLOBAL Functions/h3GetOriginIndexFromUnidirectionalEdge.cpp
    GLOBAL Functions/h3GetPentagonIndexes.cpp
    GLOBAL Functions/h3GetRes0Indexes.cpp
    GLOBAL Functions/h3GetResolution.cpp
    GLOBAL Functions/h3GetUnidirectionalEdge.cpp
    GLOBAL Functions/h3GetUnidirectionalEdgeBoundary.cpp
    GLOBAL Functions/h3GetUnidirectionalEdgesFromHexagon.cpp
    GLOBAL Functions/h3HexAreaKm2.cpp
    GLOBAL Functions/h3HexAreaM2.cpp
    GLOBAL Functions/h3HexRing.cpp
    GLOBAL Functions/h3IndexesAreNeighbors.cpp
    GLOBAL Functions/h3IsPentagon.cpp
    GLOBAL Functions/h3IsResClassIII.cpp
    GLOBAL Functions/h3IsValid.cpp
    GLOBAL Functions/h3Line.cpp
    GLOBAL Functions/h3NumHexagons.cpp
    GLOBAL Functions/h3PointDist.cpp
    GLOBAL Functions/h3ToCenterChild.cpp
    GLOBAL Functions/h3ToChildren.cpp
    GLOBAL Functions/h3ToGeoBoundary.cpp
    GLOBAL Functions/h3ToParent.cpp
    GLOBAL Functions/h3ToString.cpp
    GLOBAL Functions/h3UnidirectionalEdgeIsValid.cpp
    GLOBAL Functions/h3kRing.cpp
    GLOBAL Functions/h3toGeo.cpp
    GLOBAL Functions/hasColumnInTable.cpp
    GLOBAL Functions/hasThreadFuzzer.cpp
    GLOBAL Functions/hasToken.cpp
    GLOBAL Functions/hasTokenCaseInsensitive.cpp
    GLOBAL Functions/hypot.cpp
    GLOBAL Functions/identity.cpp
    GLOBAL Functions/if.cpp
    GLOBAL Functions/ifNotFinite.cpp
    GLOBAL Functions/ifNull.cpp
    GLOBAL Functions/ignore.cpp
    GLOBAL Functions/ilike.cpp
    GLOBAL Functions/in.cpp
    GLOBAL Functions/indexHint.cpp
    GLOBAL Functions/initialQueryID.cpp
    GLOBAL Functions/initializeAggregation.cpp
    GLOBAL Functions/intDiv.cpp
    GLOBAL Functions/intDivOrZero.cpp
    GLOBAL Functions/intExp10.cpp
    GLOBAL Functions/intExp2.cpp
    GLOBAL Functions/isConstant.cpp
    GLOBAL Functions/isDecimalOverflow.cpp
    GLOBAL Functions/isFinite.cpp
    GLOBAL Functions/isIPAddressContainedIn.cpp
    GLOBAL Functions/isInfinite.cpp
    GLOBAL Functions/isNaN.cpp
    GLOBAL Functions/isNotNull.cpp
    GLOBAL Functions/isNull.cpp
    GLOBAL Functions/isNullable.cpp
    GLOBAL Functions/isValidUTF8.cpp
    GLOBAL Functions/isZeroOrNull.cpp
    GLOBAL Functions/jumpConsistentHash.cpp
    GLOBAL Functions/kostikConsistentHash.cpp
    GLOBAL Functions/lcm.cpp
    GLOBAL Functions/least.cpp
    GLOBAL Functions/left.cpp
    GLOBAL Functions/lemmatize.cpp
    GLOBAL Functions/lengthUTF8.cpp
    GLOBAL Functions/less.cpp
    GLOBAL Functions/lessOrEquals.cpp
    GLOBAL Functions/lgamma.cpp
    GLOBAL Functions/like.cpp
    GLOBAL Functions/log.cpp
    GLOBAL Functions/log10.cpp
    GLOBAL Functions/log1p.cpp
    GLOBAL Functions/log2.cpp
    GLOBAL Functions/logTrace.cpp
    GLOBAL Functions/lowCardinalityIndices.cpp
    GLOBAL Functions/lowCardinalityKeys.cpp
    GLOBAL Functions/lower.cpp
    GLOBAL Functions/lowerUTF8.cpp
    GLOBAL Functions/makeDate.cpp
    GLOBAL Functions/map.cpp
    GLOBAL Functions/mapFilter.cpp
    GLOBAL Functions/match.cpp
    GLOBAL Functions/materialize.cpp
    GLOBAL Functions/mathConstants.cpp
    GLOBAL Functions/max2.cpp
    GLOBAL Functions/meiliMatch.cpp
    GLOBAL Functions/min2.cpp
    GLOBAL Functions/minSampleSize.cpp
    GLOBAL Functions/minus.cpp
    GLOBAL Functions/modelEvaluate.cpp
    GLOBAL Functions/modulo.cpp
    GLOBAL Functions/moduloOrZero.cpp
    GLOBAL Functions/monthName.cpp
    GLOBAL Functions/multiFuzzyMatchAllIndices.cpp
    GLOBAL Functions/multiFuzzyMatchAny.cpp
    GLOBAL Functions/multiFuzzyMatchAnyIndex.cpp
    GLOBAL Functions/multiIf.cpp
    GLOBAL Functions/multiMatchAllIndices.cpp
    GLOBAL Functions/multiMatchAny.cpp
    GLOBAL Functions/multiMatchAnyIndex.cpp
    GLOBAL Functions/multiSearchAllPositions.cpp
    GLOBAL Functions/multiSearchAllPositionsCaseInsensitive.cpp
    GLOBAL Functions/multiSearchAllPositionsCaseInsensitiveUTF8.cpp
    GLOBAL Functions/multiSearchAllPositionsUTF8.cpp
    GLOBAL Functions/multiSearchAny.cpp
    GLOBAL Functions/multiSearchAnyCaseInsensitive.cpp
    GLOBAL Functions/multiSearchAnyCaseInsensitiveUTF8.cpp
    GLOBAL Functions/multiSearchAnyUTF8.cpp
    GLOBAL Functions/multiSearchFirstIndex.cpp
    GLOBAL Functions/multiSearchFirstIndexCaseInsensitive.cpp
    GLOBAL Functions/multiSearchFirstIndexCaseInsensitiveUTF8.cpp
    GLOBAL Functions/multiSearchFirstIndexUTF8.cpp
    GLOBAL Functions/multiSearchFirstPosition.cpp
    GLOBAL Functions/multiSearchFirstPositionCaseInsensitive.cpp
    GLOBAL Functions/multiSearchFirstPositionCaseInsensitiveUTF8.cpp
    GLOBAL Functions/multiSearchFirstPositionUTF8.cpp
    GLOBAL Functions/multiply.cpp
    GLOBAL Functions/negate.cpp
    GLOBAL Functions/neighbor.cpp
    GLOBAL Functions/normalizeQuery.cpp
    GLOBAL Functions/normalizeString.cpp
    GLOBAL Functions/normalizedQueryHash.cpp
    GLOBAL Functions/notEmpty.cpp
    GLOBAL Functions/notEquals.cpp
    GLOBAL Functions/notILike.cpp
    GLOBAL Functions/notLike.cpp
    GLOBAL Functions/now.cpp
    GLOBAL Functions/now64.cpp
    GLOBAL Functions/nowInBlock.cpp
    GLOBAL Functions/nullIf.cpp
    GLOBAL Functions/padString.cpp
    GLOBAL Functions/parseTimeDelta.cpp
    GLOBAL Functions/partitionId.cpp
    GLOBAL Functions/plus.cpp
    GLOBAL Functions/pointInEllipses.cpp
    GLOBAL Functions/pointInPolygon.cpp
    GLOBAL Functions/polygonArea.cpp
    GLOBAL Functions/polygonConvexHull.cpp
    GLOBAL Functions/polygonPerimeter.cpp
    GLOBAL Functions/polygonsDistance.cpp
    GLOBAL Functions/polygonsEquals.cpp
    GLOBAL Functions/polygonsIntersection.cpp
    GLOBAL Functions/polygonsSymDifference.cpp
    GLOBAL Functions/polygonsUnion.cpp
    GLOBAL Functions/polygonsWithin.cpp
    GLOBAL Functions/position.cpp
    GLOBAL Functions/positionCaseInsensitive.cpp
    GLOBAL Functions/positionCaseInsensitiveUTF8.cpp
    GLOBAL Functions/positionUTF8.cpp
    GLOBAL Functions/pow.cpp
    GLOBAL Functions/queryID.cpp
    GLOBAL Functions/radians.cpp
    GLOBAL Functions/rand.cpp
    GLOBAL Functions/rand64.cpp
    GLOBAL Functions/randConstant.cpp
    GLOBAL Functions/randomFixedString.cpp
    GLOBAL Functions/randomPrintableASCII.cpp
    GLOBAL Functions/randomString.cpp
    GLOBAL Functions/randomStringUTF8.cpp
    GLOBAL Functions/readWkt.cpp
    GLOBAL Functions/regexpQuoteMeta.cpp
    GLOBAL Functions/registerFunctions.cpp
    GLOBAL Functions/reinterpretAs.cpp
    GLOBAL Functions/repeat.cpp
    GLOBAL Functions/replaceAll.cpp
    GLOBAL Functions/replaceOne.cpp
    GLOBAL Functions/replaceRegexpAll.cpp
    GLOBAL Functions/replaceRegexpOne.cpp
    GLOBAL Functions/replicate.cpp
    GLOBAL Functions/reverse.cpp
    GLOBAL Functions/reverseDNSQuery.cpp
    GLOBAL Functions/reverseUTF8.cpp
    GLOBAL Functions/right.cpp
    GLOBAL Functions/roundAge.cpp
    GLOBAL Functions/roundDuration.cpp
    GLOBAL Functions/roundToExp2.cpp
    GLOBAL Functions/rowNumberInAllBlocks.cpp
    GLOBAL Functions/rowNumberInBlock.cpp
    GLOBAL Functions/runningAccumulate.cpp
    GLOBAL Functions/runningConcurrency.cpp
    GLOBAL Functions/runningDifference.cpp
    GLOBAL Functions/runningDifferenceStartingWithFirstValue.cpp
    GLOBAL Functions/s2CapContains.cpp
    GLOBAL Functions/s2CapUnion.cpp
    GLOBAL Functions/s2CellsIntersect.cpp
    GLOBAL Functions/s2GetNeighbors.cpp
    GLOBAL Functions/s2RectAdd.cpp
    GLOBAL Functions/s2RectContains.cpp
    GLOBAL Functions/s2RectIntersection.cpp
    GLOBAL Functions/s2RectUnion.cpp
    GLOBAL Functions/s2ToGeo.cpp
    GLOBAL Functions/serverConstants.cpp
    GLOBAL Functions/sigmoid.cpp
    GLOBAL Functions/sign.cpp
    GLOBAL Functions/sin.cpp
    GLOBAL Functions/sinh.cpp
    GLOBAL Functions/sleep.cpp
    GLOBAL Functions/sleepEachRow.cpp
    GLOBAL Functions/snowflake.cpp
    GLOBAL Functions/sqrt.cpp
    GLOBAL Functions/startsWith.cpp
    GLOBAL Functions/stem.cpp
    GLOBAL Functions/stringCutToZero.cpp
    GLOBAL Functions/stringToH3.cpp
    GLOBAL Functions/substring.cpp
    GLOBAL Functions/subtractDays.cpp
    GLOBAL Functions/subtractHours.cpp
    GLOBAL Functions/subtractMinutes.cpp
    GLOBAL Functions/subtractMonths.cpp
    GLOBAL Functions/subtractQuarters.cpp
    GLOBAL Functions/subtractSeconds.cpp
    GLOBAL Functions/subtractWeeks.cpp
    GLOBAL Functions/subtractYears.cpp
    GLOBAL Functions/svg.cpp
    GLOBAL Functions/synonyms.cpp
    GLOBAL Functions/tan.cpp
    GLOBAL Functions/tanh.cpp
    GLOBAL Functions/tgamma.cpp
    GLOBAL Functions/throwIf.cpp
    GLOBAL Functions/tid.cpp
    GLOBAL Functions/timeSlot.cpp
    GLOBAL Functions/timeSlots.cpp
    GLOBAL Functions/timezoneOf.cpp
    GLOBAL Functions/timezoneOffset.cpp
    GLOBAL Functions/toBool.cpp
    GLOBAL Functions/toColumnTypeName.cpp
    GLOBAL Functions/toCustomWeek.cpp
    GLOBAL Functions/toDayOfMonth.cpp
    GLOBAL Functions/toDayOfWeek.cpp
    GLOBAL Functions/toDayOfYear.cpp
    GLOBAL Functions/toFixedString.cpp
    GLOBAL Functions/toHour.cpp
    GLOBAL Functions/toISOWeek.cpp
    GLOBAL Functions/toISOYear.cpp
    GLOBAL Functions/toJSONString.cpp
    GLOBAL Functions/toLastDayOfMonth.cpp
    GLOBAL Functions/toLowCardinality.cpp
    GLOBAL Functions/toMinute.cpp
    GLOBAL Functions/toModifiedJulianDay.cpp
    GLOBAL Functions/toMonday.cpp
    GLOBAL Functions/toMonth.cpp
    GLOBAL Functions/toNullable.cpp
    GLOBAL Functions/toQuarter.cpp
    GLOBAL Functions/toRelativeDayNum.cpp
    GLOBAL Functions/toRelativeHourNum.cpp
    GLOBAL Functions/toRelativeMinuteNum.cpp
    GLOBAL Functions/toRelativeMonthNum.cpp
    GLOBAL Functions/toRelativeQuarterNum.cpp
    GLOBAL Functions/toRelativeSecondNum.cpp
    GLOBAL Functions/toRelativeWeekNum.cpp
    GLOBAL Functions/toRelativeYearNum.cpp
    GLOBAL Functions/toSecond.cpp
    GLOBAL Functions/toStartOfDay.cpp
    GLOBAL Functions/toStartOfFifteenMinutes.cpp
    GLOBAL Functions/toStartOfFiveMinutes.cpp
    GLOBAL Functions/toStartOfHour.cpp
    GLOBAL Functions/toStartOfISOYear.cpp
    GLOBAL Functions/toStartOfInterval.cpp
    GLOBAL Functions/toStartOfMinute.cpp
    GLOBAL Functions/toStartOfMonth.cpp
    GLOBAL Functions/toStartOfQuarter.cpp
    GLOBAL Functions/toStartOfSecond.cpp
    GLOBAL Functions/toStartOfSubsecond.cpp
    GLOBAL Functions/toStartOfTenMinutes.cpp
    GLOBAL Functions/toStartOfYear.cpp
    GLOBAL Functions/toTime.cpp
    GLOBAL Functions/toTimezone.cpp
    GLOBAL Functions/toTypeName.cpp
    GLOBAL Functions/toUnixTimestamp64Micro.cpp
    GLOBAL Functions/toUnixTimestamp64Milli.cpp
    GLOBAL Functions/toUnixTimestamp64Nano.cpp
    GLOBAL Functions/toValidUTF8.cpp
    GLOBAL Functions/toYYYYMM.cpp
    GLOBAL Functions/toYYYYMMDD.cpp
    GLOBAL Functions/toYYYYMMDDhhmmss.cpp
    GLOBAL Functions/toYear.cpp
    GLOBAL Functions/today.cpp
    GLOBAL Functions/tokenExtractors.cpp
    GLOBAL Functions/transform.cpp
    GLOBAL Functions/translate.cpp
    GLOBAL Functions/trap.cpp
    GLOBAL Functions/trim.cpp
    GLOBAL Functions/tryBase64Decode.cpp
    GLOBAL Functions/tuple.cpp
    GLOBAL Functions/tupleElement.cpp
    GLOBAL Functions/tupleHammingDistance.cpp
    GLOBAL Functions/tupleToNameValuePairs.cpp
    GLOBAL Functions/upper.cpp
    GLOBAL Functions/upperUTF8.cpp
    GLOBAL Functions/validateNestedArraySizes.cpp
    GLOBAL Functions/vectorFunctions.cpp
    GLOBAL Functions/visibleWidth.cpp
    GLOBAL Functions/visitParamExtractBool.cpp
    GLOBAL Functions/visitParamExtractFloat.cpp
    GLOBAL Functions/visitParamExtractInt.cpp
    GLOBAL Functions/visitParamExtractRaw.cpp
    GLOBAL Functions/visitParamExtractString.cpp
    GLOBAL Functions/visitParamExtractUInt.cpp
    GLOBAL Functions/visitParamHas.cpp
    GLOBAL Functions/wkt.cpp
    GLOBAL Functions/yesterday.cpp
    GLOBAL Functions/ztest.cpp
    Interpreters/Access/InterpreterCreateQuotaQuery.cpp
    Interpreters/Access/InterpreterCreateRoleQuery.cpp
    Interpreters/Access/InterpreterCreateRowPolicyQuery.cpp
    Interpreters/Access/InterpreterCreateSettingsProfileQuery.cpp
    Interpreters/Access/InterpreterCreateUserQuery.cpp
    Interpreters/Access/InterpreterDropAccessEntityQuery.cpp
    Interpreters/Access/InterpreterGrantQuery.cpp
    Interpreters/Access/InterpreterSetRoleQuery.cpp
    Interpreters/Access/InterpreterShowAccessEntitiesQuery.cpp
    Interpreters/Access/InterpreterShowAccessQuery.cpp
    Interpreters/Access/InterpreterShowCreateAccessEntityQuery.cpp
    Interpreters/Access/InterpreterShowGrantsQuery.cpp
    Interpreters/Access/InterpreterShowPrivilegesQuery.cpp
    Interpreters/ActionLocksManager.cpp
    Interpreters/ActionsDAG.cpp
    Interpreters/ActionsVisitor.cpp
    Interpreters/AddIndexConstraintsOptimizer.cpp
    Interpreters/AggregateDescription.cpp
    Interpreters/Aggregator.cpp
    Interpreters/ApplyWithAliasVisitor.cpp
    Interpreters/ApplyWithGlobalVisitor.cpp
    Interpreters/ApplyWithSubqueryVisitor.cpp
    Interpreters/ArithmeticOperationsInAgrFuncOptimize.cpp
    Interpreters/ArrayJoinAction.cpp
    Interpreters/AsynchronousInsertQueue.cpp
    Interpreters/AsynchronousMetricLog.cpp
    Interpreters/AsynchronousMetrics.cpp
    Interpreters/BloomFilter.cpp
    Interpreters/CatBoostModel.cpp
    Interpreters/ClientInfo.cpp
    Interpreters/Cluster.cpp
    Interpreters/ClusterDiscovery.cpp
    Interpreters/ClusterProxy/SelectStreamFactory.cpp
    Interpreters/ClusterProxy/executeQuery.cpp
    Interpreters/CollectJoinOnKeysVisitor.cpp
    Interpreters/ColumnAliasesVisitor.cpp
    Interpreters/ComparisonGraph.cpp
    Interpreters/ConcurrentHashJoin.cpp
    Interpreters/Context.cpp
    Interpreters/ConvertFunctionOrLikeVisitor.cpp
    Interpreters/ConvertStringsToEnumVisitor.cpp
    Interpreters/CrashLog.cpp
    Interpreters/CrossToInnerJoinVisitor.cpp
    Interpreters/DDLTask.cpp
    Interpreters/DDLWorker.cpp
    Interpreters/DNSCacheUpdater.cpp
    Interpreters/DatabaseAndTableWithAlias.cpp
    Interpreters/DatabaseCatalog.cpp
    Interpreters/DirectJoin.cpp
    Interpreters/DuplicateOrderByVisitor.cpp
    Interpreters/EmbeddedDictionaries.cpp
    Interpreters/ExecuteScalarSubqueriesVisitor.cpp
    Interpreters/ExpressionActions.cpp
    Interpreters/ExpressionActionsSettings.cpp
    Interpreters/ExpressionAnalyzer.cpp
    Interpreters/ExpressionJIT.cpp
    Interpreters/ExternalDictionariesLoader.cpp
    Interpreters/ExternalLoader.cpp
    Interpreters/ExternalLoaderDictionaryStorageConfigRepository.cpp
    Interpreters/ExternalLoaderTempConfigRepository.cpp
    Interpreters/ExternalLoaderXMLConfigRepository.cpp
    Interpreters/ExternalModelsLoader.cpp
    Interpreters/ExternalUserDefinedExecutableFunctionsLoader.cpp
    Interpreters/ExtractExpressionInfoVisitor.cpp
    Interpreters/FilesystemCacheLog.cpp
    Interpreters/FillingRow.cpp
    Interpreters/FunctionNameNormalizer.cpp
    Interpreters/GatherFunctionQuantileVisitor.cpp
    Interpreters/GetAggregatesVisitor.cpp
    Interpreters/GroupingSetsRewriterVisitor.cpp
    Interpreters/HashJoin.cpp
    Interpreters/IExternalLoadable.cpp
    Interpreters/IInterpreter.cpp
    Interpreters/IInterpreterUnionOrSelectQuery.cpp
    Interpreters/ITokenExtractor.cpp
    Interpreters/IdentifierSemantic.cpp
    Interpreters/InJoinSubqueriesPreprocessor.cpp
    Interpreters/InternalTextLogsQueue.cpp
    Interpreters/InterpreterAlterQuery.cpp
    Interpreters/InterpreterBackupQuery.cpp
    Interpreters/InterpreterCheckQuery.cpp
    Interpreters/InterpreterCreateFunctionQuery.cpp
    Interpreters/InterpreterCreateIndexQuery.cpp
    Interpreters/InterpreterCreateQuery.cpp
    Interpreters/InterpreterDeleteQuery.cpp
    Interpreters/InterpreterDescribeCacheQuery.cpp
    Interpreters/InterpreterDescribeQuery.cpp
    Interpreters/InterpreterDropFunctionQuery.cpp
    Interpreters/InterpreterDropIndexQuery.cpp
    Interpreters/InterpreterDropQuery.cpp
    Interpreters/InterpreterExistsQuery.cpp
    Interpreters/InterpreterExplainQuery.cpp
    Interpreters/InterpreterExternalDDLQuery.cpp
    Interpreters/InterpreterFactory.cpp
    Interpreters/InterpreterInsertQuery.cpp
    Interpreters/InterpreterKillQueryQuery.cpp
    Interpreters/InterpreterOptimizeQuery.cpp
    Interpreters/InterpreterRenameQuery.cpp
    Interpreters/InterpreterSelectIntersectExceptQuery.cpp
    Interpreters/InterpreterSelectQuery.cpp
    Interpreters/InterpreterSelectWithUnionQuery.cpp
    Interpreters/InterpreterSetQuery.cpp
    Interpreters/InterpreterShowCreateQuery.cpp
    Interpreters/InterpreterShowProcesslistQuery.cpp
    Interpreters/InterpreterShowTablesQuery.cpp
    Interpreters/InterpreterSystemQuery.cpp
    Interpreters/InterpreterTransactionControlQuery.cpp
    Interpreters/InterpreterUseQuery.cpp
    Interpreters/InterpreterWatchQuery.cpp
    Interpreters/InterserverCredentials.cpp
    Interpreters/JIT/CHJIT.cpp
    Interpreters/JIT/CompileDAG.cpp
    Interpreters/JIT/CompiledExpressionCache.cpp
    Interpreters/JIT/compileFunction.cpp
    Interpreters/JoinSwitcher.cpp
    Interpreters/JoinToSubqueryTransformVisitor.cpp
    Interpreters/JoinUtils.cpp
    Interpreters/JoinedTables.cpp
    Interpreters/Lemmatizers.cpp
    Interpreters/LogicalExpressionsOptimizer.cpp
    Interpreters/MarkTableIdentifiersVisitor.cpp
    Interpreters/MergeJoin.cpp
    Interpreters/MergeTreeTransaction.cpp
    Interpreters/MergeTreeTransactionHolder.cpp
    Interpreters/MetricLog.cpp
    Interpreters/MutationsInterpreter.cpp
    Interpreters/MySQL/InterpretersMySQLDDLQuery.cpp
    Interpreters/NormalizeSelectWithUnionQueryVisitor.cpp
    Interpreters/NullableUtils.cpp
    Interpreters/OpenTelemetrySpanLog.cpp
    Interpreters/OptimizeIfChains.cpp
    Interpreters/OptimizeIfWithConstantConditionVisitor.cpp
    Interpreters/OptimizeShardingKeyRewriteInVisitor.cpp
    Interpreters/PartLog.cpp
    Interpreters/PredicateExpressionsOptimizer.cpp
    Interpreters/PredicateRewriteVisitor.cpp
    Interpreters/PreparedSets.cpp
    Interpreters/ProcessList.cpp
    Interpreters/ProcessorsProfileLog.cpp
    Interpreters/ProfileEventsExt.cpp
    Interpreters/QueryAliasesVisitor.cpp
    Interpreters/QueryLog.cpp
    Interpreters/QueryNormalizer.cpp
    Interpreters/QueryParameterVisitor.cpp
    Interpreters/QueryThreadLog.cpp
    Interpreters/QueryViewsLog.cpp
    Interpreters/RemoveInjectiveFunctionsVisitor.cpp
    Interpreters/RenameColumnVisitor.cpp
    Interpreters/ReplaceQueryParameterVisitor.cpp
    Interpreters/RequiredSourceColumnsData.cpp
    Interpreters/RequiredSourceColumnsVisitor.cpp
    Interpreters/RewriteAnyFunctionVisitor.cpp
    Interpreters/RewriteCountDistinctVisitor.cpp
    Interpreters/RewriteCountVariantsVisitor.cpp
    Interpreters/RewriteFunctionToSubcolumnVisitor.cpp
    Interpreters/RewriteOrderByVisitor.cpp
    Interpreters/RewriteSumIfFunctionVisitor.cpp
    Interpreters/RowRefs.cpp
    Interpreters/SelectIntersectExceptQueryVisitor.cpp
    Interpreters/Session.cpp
    Interpreters/SessionLog.cpp
    Interpreters/Set.cpp
    Interpreters/SetVariants.cpp
    Interpreters/SortedBlocksWriter.cpp
    Interpreters/SquashingTransform.cpp
    Interpreters/StorageID.cpp
    Interpreters/SubstituteColumnOptimizer.cpp
    Interpreters/SynonymsExtensions.cpp
    Interpreters/SystemLog.cpp
    Interpreters/TableJoin.cpp
    Interpreters/TableOverrideUtils.cpp
    Interpreters/TablesStatus.cpp
    Interpreters/TextLog.cpp
    Interpreters/ThreadStatusExt.cpp
    Interpreters/TraceCollector.cpp
    Interpreters/TraceLog.cpp
    Interpreters/TransactionLog.cpp
    Interpreters/TransactionVersionMetadata.cpp
    Interpreters/TransactionsInfoLog.cpp
    Interpreters/TranslateQualifiedNamesVisitor.cpp
    Interpreters/TreeCNFConverter.cpp
    Interpreters/TreeOptimizer.cpp
    Interpreters/TreeRewriter.cpp
    Interpreters/UserDefinedExecutableFunction.cpp
    Interpreters/UserDefinedExecutableFunctionFactory.cpp
    Interpreters/UserDefinedSQLFunctionFactory.cpp
    Interpreters/UserDefinedSQLFunctionVisitor.cpp
    Interpreters/UserDefinedSQLObjectsLoader.cpp
    Interpreters/WhereConstraintsOptimizer.cpp
    Interpreters/WindowDescription.cpp
    Interpreters/ZooKeeperLog.cpp
    Interpreters/addMissingDefaults.cpp
    Interpreters/addTypeConversionToAST.cpp
    Interpreters/applyTableOverride.cpp
    Interpreters/castColumn.cpp
    Interpreters/convertFieldToType.cpp
    Interpreters/createBlockSelector.cpp
    Interpreters/evaluateConstantExpression.cpp
    Interpreters/executeDDLQueryOnCluster.cpp
    Interpreters/executeQuery.cpp
    Interpreters/getClusterName.cpp
    Interpreters/getColumnFromBlock.cpp
    Interpreters/getHeaderForProcessingStage.cpp
    Interpreters/getTableExpressions.cpp
    Interpreters/getTableOverride.cpp
    Interpreters/inplaceBlockConversions.cpp
    Interpreters/interpretSubquery.cpp
    Interpreters/loadMetadata.cpp
    Interpreters/parseColumnsListForTableFunction.cpp
    Interpreters/processColumnTransformers.cpp
    Interpreters/replaceAliasColumnsInQuery.cpp
    Interpreters/replaceForPositionalArguments.cpp
    Interpreters/sortBlock.cpp
    Interpreters/threadPoolCallbackRunner.cpp
    Loggers/ExtendedLogChannel.cpp
    Loggers/Loggers.cpp
    Loggers/OwnFormattingChannel.cpp
    Loggers/OwnJSONPatternFormatter.cpp
    Loggers/OwnPatternFormatter.cpp
    Loggers/OwnSplitChannel.cpp
    Processors/Chunk.cpp
    Processors/ConcatProcessor.cpp
    Processors/DelayedPortsProcessor.cpp
    Processors/Executors/CompletedPipelineExecutor.cpp
    Processors/Executors/ExecutingGraph.cpp
    Processors/Executors/ExecutionThreadContext.cpp
    Processors/Executors/ExecutorTasks.cpp
    Processors/Executors/PipelineExecutor.cpp
    Processors/Executors/PollingQueue.cpp
    Processors/Executors/PullingAsyncPipelineExecutor.cpp
    Processors/Executors/PullingPipelineExecutor.cpp
    Processors/Executors/PushingAsyncPipelineExecutor.cpp
    Processors/Executors/PushingPipelineExecutor.cpp
    Processors/Executors/StreamingFormatExecutor.cpp
    Processors/ForkProcessor.cpp
    Processors/Formats/IInputFormat.cpp
    Processors/Formats/IOutputFormat.cpp
    Processors/Formats/IRowInputFormat.cpp
    Processors/Formats/IRowOutputFormat.cpp
    Processors/Formats/ISchemaReader.cpp
    Processors/Formats/Impl/ArrowBlockInputFormat.cpp
    Processors/Formats/Impl/ArrowBlockOutputFormat.cpp
    Processors/Formats/Impl/ArrowBufferedStreams.cpp
    Processors/Formats/Impl/ArrowColumnToCHColumn.cpp
    Processors/Formats/Impl/AvroRowInputFormat.cpp
    Processors/Formats/Impl/AvroRowOutputFormat.cpp
    Processors/Formats/Impl/BinaryRowInputFormat.cpp
    Processors/Formats/Impl/BinaryRowOutputFormat.cpp
    Processors/Formats/Impl/CHColumnToArrowColumn.cpp
    Processors/Formats/Impl/CSVRowInputFormat.cpp
    Processors/Formats/Impl/CSVRowOutputFormat.cpp
    Processors/Formats/Impl/CapnProtoRowInputFormat.cpp
    Processors/Formats/Impl/CapnProtoRowOutputFormat.cpp
    Processors/Formats/Impl/ConstantExpressionTemplate.cpp
    Processors/Formats/Impl/CustomSeparatedRowInputFormat.cpp
    Processors/Formats/Impl/CustomSeparatedRowOutputFormat.cpp
    Processors/Formats/Impl/HiveTextRowInputFormat.cpp
    Processors/Formats/Impl/JSONAsStringRowInputFormat.cpp
    Processors/Formats/Impl/JSONColumnsBlockInputFormat.cpp
    Processors/Formats/Impl/JSONColumnsBlockInputFormatBase.cpp
    Processors/Formats/Impl/JSONColumnsBlockOutputFormat.cpp
    Processors/Formats/Impl/JSONColumnsBlockOutputFormatBase.cpp
    Processors/Formats/Impl/JSONColumnsWithMetadataBlockOutputFormat.cpp
    Processors/Formats/Impl/JSONCompactColumnsBlockInputFormat.cpp
    Processors/Formats/Impl/JSONCompactColumnsBlockOutputFormat.cpp
    Processors/Formats/Impl/JSONCompactEachRowRowInputFormat.cpp
    Processors/Formats/Impl/JSONCompactEachRowRowOutputFormat.cpp
    Processors/Formats/Impl/JSONCompactRowOutputFormat.cpp
    Processors/Formats/Impl/JSONEachRowRowInputFormat.cpp
    Processors/Formats/Impl/JSONEachRowRowOutputFormat.cpp
    Processors/Formats/Impl/JSONEachRowWithProgressRowOutputFormat.cpp
    Processors/Formats/Impl/JSONRowOutputFormat.cpp
    Processors/Formats/Impl/LineAsStringRowInputFormat.cpp
    Processors/Formats/Impl/MarkdownRowOutputFormat.cpp
    Processors/Formats/Impl/MsgPackRowInputFormat.cpp
    Processors/Formats/Impl/MsgPackRowOutputFormat.cpp
    Processors/Formats/Impl/MySQLDumpRowInputFormat.cpp
    Processors/Formats/Impl/MySQLOutputFormat.cpp
    Processors/Formats/Impl/NativeFormat.cpp
    Processors/Formats/Impl/NullFormat.cpp
    Processors/Formats/Impl/ODBCDriver2BlockOutputFormat.cpp
    Processors/Formats/Impl/ORCBlockInputFormat.cpp
    Processors/Formats/Impl/ORCBlockOutputFormat.cpp
    Processors/Formats/Impl/ParallelFormattingOutputFormat.cpp
    Processors/Formats/Impl/ParallelParsingInputFormat.cpp
    Processors/Formats/Impl/ParquetBlockInputFormat.cpp
    Processors/Formats/Impl/ParquetBlockOutputFormat.cpp
    Processors/Formats/Impl/PostgreSQLOutputFormat.cpp
    Processors/Formats/Impl/PrettyBlockOutputFormat.cpp
    Processors/Formats/Impl/PrettyCompactBlockOutputFormat.cpp
    Processors/Formats/Impl/PrettySpaceBlockOutputFormat.cpp
    Processors/Formats/Impl/PrometheusTextOutputFormat.cpp
    Processors/Formats/Impl/ProtobufListInputFormat.cpp
    Processors/Formats/Impl/ProtobufListOutputFormat.cpp
    Processors/Formats/Impl/ProtobufRowInputFormat.cpp
    Processors/Formats/Impl/ProtobufRowOutputFormat.cpp
    Processors/Formats/Impl/RawBLOBRowInputFormat.cpp
    Processors/Formats/Impl/RawBLOBRowOutputFormat.cpp
    Processors/Formats/Impl/RegexpRowInputFormat.cpp
    Processors/Formats/Impl/SQLInsertRowOutputFormat.cpp
    Processors/Formats/Impl/TSKVRowInputFormat.cpp
    Processors/Formats/Impl/TSKVRowOutputFormat.cpp
    Processors/Formats/Impl/TabSeparatedRowInputFormat.cpp
    Processors/Formats/Impl/TabSeparatedRowOutputFormat.cpp
    Processors/Formats/Impl/TemplateBlockOutputFormat.cpp
    Processors/Formats/Impl/TemplateRowInputFormat.cpp
    Processors/Formats/Impl/ValuesBlockInputFormat.cpp
    Processors/Formats/Impl/ValuesRowOutputFormat.cpp
    Processors/Formats/Impl/VerticalRowOutputFormat.cpp
    Processors/Formats/Impl/XMLRowOutputFormat.cpp
    Processors/Formats/LazyOutputFormat.cpp
    Processors/Formats/PullingOutputFormat.cpp
    Processors/Formats/RowInputFormatWithDiagnosticInfo.cpp
    Processors/Formats/RowInputFormatWithNamesAndTypes.cpp
    Processors/IAccumulatingTransform.cpp
    Processors/IInflatingTransform.cpp
    Processors/IProcessor.cpp
    Processors/ISimpleTransform.cpp
    Processors/ISink.cpp
    Processors/ISource.cpp
    Processors/LimitTransform.cpp
    Processors/Merges/Algorithms/AggregatingSortedAlgorithm.cpp
    Processors/Merges/Algorithms/CollapsingSortedAlgorithm.cpp
    Processors/Merges/Algorithms/FinishAggregatingInOrderAlgorithm.cpp
    Processors/Merges/Algorithms/Graphite.cpp
    Processors/Merges/Algorithms/GraphiteRollupSortedAlgorithm.cpp
    Processors/Merges/Algorithms/IMergingAlgorithmWithDelayedChunk.cpp
    Processors/Merges/Algorithms/IMergingAlgorithmWithSharedChunks.cpp
    Processors/Merges/Algorithms/MergingSortedAlgorithm.cpp
    Processors/Merges/Algorithms/ReplacingSortedAlgorithm.cpp
    Processors/Merges/Algorithms/SummingSortedAlgorithm.cpp
    Processors/Merges/Algorithms/VersionedCollapsingAlgorithm.cpp
    Processors/Merges/IMergingTransform.cpp
    Processors/Merges/MergingSortedTransform.cpp
    Processors/OffsetTransform.cpp
    Processors/Port.cpp
    Processors/QueryPlan/AggregatingStep.cpp
    Processors/QueryPlan/ArrayJoinStep.cpp
    Processors/QueryPlan/BuildQueryPipelineSettings.cpp
    Processors/QueryPlan/CreatingSetsStep.cpp
    Processors/QueryPlan/CubeStep.cpp
    Processors/QueryPlan/DistinctStep.cpp
    Processors/QueryPlan/DistributedCreateLocalPlan.cpp
    Processors/QueryPlan/ExpressionStep.cpp
    Processors/QueryPlan/ExtremesStep.cpp
    Processors/QueryPlan/FillingStep.cpp
    Processors/QueryPlan/FilterStep.cpp
    Processors/QueryPlan/IQueryPlanStep.cpp
    Processors/QueryPlan/ISourceStep.cpp
    Processors/QueryPlan/ITransformingStep.cpp
    Processors/QueryPlan/IntersectOrExceptStep.cpp
    Processors/QueryPlan/JoinStep.cpp
    Processors/QueryPlan/LimitByStep.cpp
    Processors/QueryPlan/LimitStep.cpp
    Processors/QueryPlan/MergingAggregatedStep.cpp
    Processors/QueryPlan/OffsetStep.cpp
    Processors/QueryPlan/Optimizations/QueryPlanOptimizationSettings.cpp
    Processors/QueryPlan/Optimizations/filterPushDown.cpp
    Processors/QueryPlan/Optimizations/liftUpArrayJoin.cpp
    Processors/QueryPlan/Optimizations/liftUpFunctions.cpp
    Processors/QueryPlan/Optimizations/limitPushDown.cpp
    Processors/QueryPlan/Optimizations/mergeExpressions.cpp
    Processors/QueryPlan/Optimizations/optimizePrimaryKeyCondition.cpp
    Processors/QueryPlan/Optimizations/optimizeTree.cpp
    Processors/QueryPlan/Optimizations/reuseStorageOrderingForWindowFunctions.cpp
    Processors/QueryPlan/Optimizations/splitFilter.cpp
    Processors/QueryPlan/PartsSplitter.cpp
    Processors/QueryPlan/QueryIdHolder.cpp
    Processors/QueryPlan/QueryPlan.cpp
    Processors/QueryPlan/ReadFromMergeTree.cpp
    Processors/QueryPlan/ReadFromPreparedSource.cpp
    Processors/QueryPlan/ReadFromRemote.cpp
    Processors/QueryPlan/ReadNothingStep.cpp
    Processors/QueryPlan/RollupStep.cpp
    Processors/QueryPlan/SortingStep.cpp
    Processors/QueryPlan/TotalsHavingStep.cpp
    Processors/QueryPlan/UnionStep.cpp
    Processors/QueryPlan/WindowStep.cpp
    Processors/ResizeProcessor.cpp
    Processors/Sinks/SinkToStorage.cpp
    Processors/Sources/DelayedSource.cpp
    Processors/Sources/MySQLSource.cpp
    Processors/Sources/RemoteSource.cpp
    Processors/Sources/SQLiteSource.cpp
    Processors/Sources/ShellCommandSource.cpp
    Processors/Sources/SourceFromSingleChunk.cpp
    Processors/Sources/TemporaryFileLazySource.cpp
    Processors/TTL/ITTLAlgorithm.cpp
    Processors/TTL/TTLAggregationAlgorithm.cpp
    Processors/TTL/TTLColumnAlgorithm.cpp
    Processors/TTL/TTLDeleteAlgorithm.cpp
    Processors/TTL/TTLUpdateInfoAlgorithm.cpp
    Processors/Transforms/AddingDefaultsTransform.cpp
    Processors/Transforms/AggregatingInOrderTransform.cpp
    Processors/Transforms/AggregatingTransform.cpp
    Processors/Transforms/ArrayJoinTransform.cpp
    Processors/Transforms/CheckConstraintsTransform.cpp
    Processors/Transforms/CheckSortedTransform.cpp
    Processors/Transforms/ColumnGathererTransform.cpp
    Processors/Transforms/CopyTransform.cpp
    Processors/Transforms/CountingTransform.cpp
    Processors/Transforms/CreatingSetsTransform.cpp
    Processors/Transforms/CubeTransform.cpp
    Processors/Transforms/DistinctSortedChunkTransform.cpp
    Processors/Transforms/DistinctSortedTransform.cpp
    Processors/Transforms/DistinctTransform.cpp
    Processors/Transforms/ExceptionKeepingTransform.cpp
    Processors/Transforms/ExpressionTransform.cpp
    Processors/Transforms/ExtremesTransform.cpp
    Processors/Transforms/FillingTransform.cpp
    Processors/Transforms/FilterTransform.cpp
    Processors/Transforms/FinishSortingTransform.cpp
    Processors/Transforms/IntersectOrExceptTransform.cpp
    Processors/Transforms/JoiningTransform.cpp
    Processors/Transforms/LimitByTransform.cpp
    Processors/Transforms/LimitsCheckingTransform.cpp
    Processors/Transforms/MaterializingTransform.cpp
    Processors/Transforms/MergeJoinTransform.cpp
    Processors/Transforms/MergeSortingTransform.cpp
    Processors/Transforms/MergingAggregatedMemoryEfficientTransform.cpp
    Processors/Transforms/MergingAggregatedTransform.cpp
    Processors/Transforms/MongoDBSource.cpp
    Processors/Transforms/PartialSortingTransform.cpp
    Processors/Transforms/PostgreSQLSource.cpp
    Processors/Transforms/ReverseTransform.cpp
    Processors/Transforms/RollupTransform.cpp
    Processors/Transforms/SortingTransform.cpp
    Processors/Transforms/SquashingChunksTransform.cpp
    Processors/Transforms/TTLCalcTransform.cpp
    Processors/Transforms/TTLTransform.cpp
    Processors/Transforms/TotalsHavingTransform.cpp
    Processors/Transforms/WatermarkTransform.cpp
    Processors/Transforms/WindowTransform.cpp
    Processors/Transforms/buildPushingToViewsChain.cpp
    Processors/Transforms/finalizeChunk.cpp
    Processors/Transforms/getSourceFromASTInsertQuery.cpp
    QueryPipeline/BlockIO.cpp
    QueryPipeline/Chain.cpp
    QueryPipeline/ConnectionCollector.cpp
    QueryPipeline/ExecutionSpeedLimits.cpp
    QueryPipeline/Pipe.cpp
    QueryPipeline/PipelineResourcesHolder.cpp
    QueryPipeline/ProfileInfo.cpp
    QueryPipeline/QueryPipeline.cpp
    QueryPipeline/QueryPipelineBuilder.cpp
    QueryPipeline/ReadProgressCallback.cpp
    QueryPipeline/RemoteInserter.cpp
    QueryPipeline/RemoteQueryExecutor.cpp
    QueryPipeline/RemoteQueryExecutorReadContext.cpp
    QueryPipeline/SizeLimits.cpp
    QueryPipeline/narrowPipe.cpp
    QueryPipeline/printPipeline.cpp
    Server/CertificateReloader.cpp
    Server/GRPCServer.cpp
    Server/HTTP/HTMLForm.cpp
    Server/HTTP/HTTPServer.cpp
    Server/HTTP/HTTPServerConnection.cpp
    Server/HTTP/HTTPServerConnectionFactory.cpp
    Server/HTTP/HTTPServerRequest.cpp
    Server/HTTP/HTTPServerResponse.cpp
    Server/HTTP/ReadHeaders.cpp
    Server/HTTP/WriteBufferFromHTTPServerResponse.cpp
    Server/HTTPHandler.cpp
    Server/HTTPHandlerFactory.cpp
    Server/InterserverIOHTTPHandler.cpp
    Server/KeeperTCPHandler.cpp
    Server/MySQLHandler.cpp
    Server/MySQLHandlerFactory.cpp
    Server/NotFoundHandler.cpp
    Server/PostgreSQLHandler.cpp
    Server/PostgreSQLHandlerFactory.cpp
    Server/PrometheusMetricsWriter.cpp
    Server/PrometheusRequestHandler.cpp
    Server/ProtocolServerAdapter.cpp
    Server/ReplicasStatusHandler.cpp
    Server/StaticRequestHandler.cpp
    Server/TCPHandler.cpp
    Server/TCPServer.cpp
    Server/WebUIRequestHandler.cpp
    Storages/AlterCommands.cpp
    Storages/Cache/ExternalDataSourceCache.cpp
    Storages/Cache/RemoteCacheController.cpp
    Storages/Cache/RemoteFileMetadataFactory.cpp
    Storages/Cache/SchemaCache.cpp
    Storages/Cache/registerRemoteFileMetadatas.cpp
    Storages/ColumnDefault.cpp
    Storages/ColumnsDescription.cpp
    Storages/ConstraintsDescription.cpp
    Storages/Distributed/DirectoryMonitor.cpp
    Storages/Distributed/DistributedSettings.cpp
    Storages/Distributed/DistributedSink.cpp
    Storages/ExecutableSettings.cpp
    Storages/ExternalDataSourceConfiguration.cpp
    Storages/Freeze.cpp
    Storages/IStorage.cpp
    Storages/IndicesDescription.cpp
    Storages/KVStorageUtils.cpp
    Storages/KeyDescription.cpp
    Storages/LightweightDeleteDescription.cpp
    Storages/LiveView/StorageLiveView.cpp
    Storages/LiveView/TemporaryLiveViewCleaner.cpp
    Storages/MeiliSearch/MeiliSearchColumnDescriptionFetcher.cpp
    Storages/MeiliSearch/MeiliSearchConnection.cpp
    Storages/MeiliSearch/SinkMeiliSearch.cpp
    Storages/MeiliSearch/SourceMeiliSearch.cpp
    Storages/MeiliSearch/StorageMeiliSearch.cpp
    Storages/MemorySettings.cpp
    Storages/MergeTree/ActiveDataPartSet.cpp
    Storages/MergeTree/AllMergeSelector.cpp
    Storages/MergeTree/BackgroundJobsAssignee.cpp
    Storages/MergeTree/BoolMask.cpp
    Storages/MergeTree/DataPartStorageOnDisk.cpp
    Storages/MergeTree/DataPartsExchange.cpp
    Storages/MergeTree/DropPartsRanges.cpp
    Storages/MergeTree/EphemeralLockInZooKeeper.cpp
    Storages/MergeTree/FutureMergedMutatedPart.cpp
    Storages/MergeTree/IMergeTreeDataPart.cpp
    Storages/MergeTree/IMergeTreeDataPartWriter.cpp
    Storages/MergeTree/IMergeTreeReader.cpp
    Storages/MergeTree/IMergedBlockOutputStream.cpp
    Storages/MergeTree/IPartMetadataManager.cpp
    Storages/MergeTree/KeyCondition.cpp
    Storages/MergeTree/LevelMergeSelector.cpp
    Storages/MergeTree/MarkRange.cpp
    Storages/MergeTree/MergeFromLogEntryTask.cpp
    Storages/MergeTree/MergeList.cpp
    Storages/MergeTree/MergePlainMergeTreeTask.cpp
    Storages/MergeTree/MergeTask.cpp
    Storages/MergeTree/MergeTreeBackgroundExecutor.cpp
    Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp
    Storages/MergeTree/MergeTreeBlockReadUtils.cpp
    Storages/MergeTree/MergeTreeData.cpp
    Storages/MergeTree/MergeTreeDataMergerMutator.cpp
    Storages/MergeTree/MergeTreeDataPartChecksum.cpp
    Storages/MergeTree/MergeTreeDataPartCompact.cpp
    Storages/MergeTree/MergeTreeDataPartInMemory.cpp
    Storages/MergeTree/MergeTreeDataPartTTLInfo.cpp
    Storages/MergeTree/MergeTreeDataPartType.cpp
    Storages/MergeTree/MergeTreeDataPartUUID.cpp
    Storages/MergeTree/MergeTreeDataPartWide.cpp
    Storages/MergeTree/MergeTreeDataPartWriterCompact.cpp
    Storages/MergeTree/MergeTreeDataPartWriterInMemory.cpp
    Storages/MergeTree/MergeTreeDataPartWriterOnDisk.cpp
    Storages/MergeTree/MergeTreeDataPartWriterWide.cpp
    Storages/MergeTree/MergeTreeDataSelectExecutor.cpp
    Storages/MergeTree/MergeTreeDataWriter.cpp
    Storages/MergeTree/MergeTreeDeduplicationLog.cpp
    Storages/MergeTree/MergeTreeInOrderSelectProcessor.cpp
    Storages/MergeTree/MergeTreeIndexAggregatorBloomFilter.cpp
    Storages/MergeTree/MergeTreeIndexBloomFilter.cpp
    Storages/MergeTree/MergeTreeIndexConditionBloomFilter.cpp
    Storages/MergeTree/MergeTreeIndexFullText.cpp
    Storages/MergeTree/MergeTreeIndexGranularity.cpp
    Storages/MergeTree/MergeTreeIndexGranularityInfo.cpp
    Storages/MergeTree/MergeTreeIndexGranuleBloomFilter.cpp
    Storages/MergeTree/MergeTreeIndexHypothesis.cpp
    Storages/MergeTree/MergeTreeIndexHypothesisMergedCondition.cpp
    Storages/MergeTree/MergeTreeIndexMinMax.cpp
    Storages/MergeTree/MergeTreeIndexReader.cpp
    Storages/MergeTree/MergeTreeIndexSet.cpp
    Storages/MergeTree/MergeTreeIndices.cpp
    Storages/MergeTree/MergeTreeMarksLoader.cpp
    Storages/MergeTree/MergeTreeMetadataCache.cpp
    Storages/MergeTree/MergeTreeMutationEntry.cpp
    Storages/MergeTree/MergeTreeMutationStatus.cpp
    Storages/MergeTree/MergeTreePartInfo.cpp
    Storages/MergeTree/MergeTreePartition.cpp
    Storages/MergeTree/MergeTreePartsMover.cpp
    Storages/MergeTree/MergeTreeRangeReader.cpp
    Storages/MergeTree/MergeTreeReadPool.cpp
    Storages/MergeTree/MergeTreeReaderCompact.cpp
    Storages/MergeTree/MergeTreeReaderInMemory.cpp
    Storages/MergeTree/MergeTreeReaderStream.cpp
    Storages/MergeTree/MergeTreeReaderWide.cpp
    Storages/MergeTree/MergeTreeReverseSelectProcessor.cpp
    Storages/MergeTree/MergeTreeSelectProcessor.cpp
    Storages/MergeTree/MergeTreeSequentialSource.cpp
    Storages/MergeTree/MergeTreeSettings.cpp
    Storages/MergeTree/MergeTreeSink.cpp
    Storages/MergeTree/MergeTreeThreadSelectProcessor.cpp
    Storages/MergeTree/MergeTreeWhereOptimizer.cpp
    Storages/MergeTree/MergeTreeWriteAheadLog.cpp
    Storages/MergeTree/MergeType.cpp
    Storages/MergeTree/MergedBlockOutputStream.cpp
    Storages/MergeTree/MergedColumnOnlyOutputStream.cpp
    Storages/MergeTree/MutateFromLogEntryTask.cpp
    Storages/MergeTree/MutatePlainMergeTreeTask.cpp
    Storages/MergeTree/MutateTask.cpp
    Storages/MergeTree/ParallelReplicasReadingCoordinator.cpp
    Storages/MergeTree/PartMetadataManagerOrdinary.cpp
    Storages/MergeTree/PartMetadataManagerWithCache.cpp
    Storages/MergeTree/PartMovesBetweenShardsOrchestrator.cpp
    Storages/MergeTree/PartitionPruner.cpp
    Storages/MergeTree/PinnedPartUUIDs.cpp
    Storages/MergeTree/ReplicatedFetchList.cpp
    Storages/MergeTree/ReplicatedMergeMutateTaskBase.cpp
    Storages/MergeTree/ReplicatedMergeTreeAddress.cpp
    Storages/MergeTree/ReplicatedMergeTreeAltersSequence.cpp
    Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp
    Storages/MergeTree/ReplicatedMergeTreeLogEntry.cpp
    Storages/MergeTree/ReplicatedMergeTreeMergeStrategyPicker.cpp
    Storages/MergeTree/ReplicatedMergeTreeMutationEntry.cpp
    Storages/MergeTree/ReplicatedMergeTreePartCheckThread.cpp
    Storages/MergeTree/ReplicatedMergeTreePartHeader.cpp
    Storages/MergeTree/ReplicatedMergeTreeQueue.cpp
    Storages/MergeTree/ReplicatedMergeTreeRestartingThread.cpp
    Storages/MergeTree/ReplicatedMergeTreeSink.cpp
    Storages/MergeTree/ReplicatedMergeTreeTableMetadata.cpp
    Storages/MergeTree/RequestResponse.cpp
    Storages/MergeTree/SimpleMergeSelector.cpp
    Storages/MergeTree/TTLMergeSelector.cpp
    Storages/MergeTree/TemporaryParts.cpp
    Storages/MergeTree/ZeroCopyLock.cpp
    Storages/MergeTree/checkDataPart.cpp
    Storages/MergeTree/extractZkPathFromCreateQuery.cpp
    Storages/MergeTree/localBackup.cpp
    Storages/MergeTree/registerStorageMergeTree.cpp
    Storages/MutationCommands.cpp
    Storages/MySQL/MySQLHelpers.cpp
    Storages/MySQL/MySQLSettings.cpp
    Storages/PartitionCommands.cpp
    Storages/PartitionedSink.cpp
    Storages/ProjectionsDescription.cpp
    Storages/ReadFinalForExternalReplicaStorage.cpp
    Storages/ReadInOrderOptimizer.cpp
    Storages/SelectQueryDescription.cpp
    Storages/SetSettings.cpp
    Storages/StorageBuffer.cpp
    Storages/StorageDictionary.cpp
    Storages/StorageDistributed.cpp
    Storages/StorageExecutable.cpp
    Storages/StorageExternalDistributed.cpp
    Storages/StorageFactory.cpp
    Storages/StorageFile.cpp
    Storages/StorageGenerateRandom.cpp
    Storages/StorageInMemoryMetadata.cpp
    Storages/StorageInput.cpp
    Storages/StorageJoin.cpp
    Storages/StorageLog.cpp
    Storages/StorageLogSettings.cpp
    Storages/StorageMaterializedMySQL.cpp
    Storages/StorageMaterializedView.cpp
    Storages/StorageMemory.cpp
    Storages/StorageMerge.cpp
    Storages/StorageMergeTree.cpp
    Storages/StorageMongoDB.cpp
    Storages/StorageMongoDBSocketFactory.cpp
    Storages/StorageMySQL.cpp
    Storages/StorageNull.cpp
    Storages/StoragePostgreSQL.cpp
    Storages/StorageReplicatedMergeTree.cpp
    Storages/StorageS3.cpp
    Storages/StorageS3Cluster.cpp
    Storages/StorageS3Settings.cpp
    Storages/StorageSQLite.cpp
    Storages/StorageSet.cpp
    Storages/StorageSnapshot.cpp
    Storages/StorageStripeLog.cpp
    Storages/StorageURL.cpp
    Storages/StorageValues.cpp
    Storages/StorageView.cpp
    Storages/StorageXDBC.cpp
    Storages/System/StorageSystemAggregateFunctionCombinators.cpp
    Storages/System/StorageSystemAsynchronousInserts.cpp
    Storages/System/StorageSystemAsynchronousMetrics.cpp
    Storages/System/StorageSystemBackups.cpp
    Storages/System/StorageSystemBuildOptions.cpp
    Storages/System/StorageSystemBuildOptions.generated.cpp
    Storages/System/StorageSystemCertificates.cpp
    Storages/System/StorageSystemClusters.cpp
    Storages/System/StorageSystemCollations.cpp
    Storages/System/StorageSystemColumns.cpp
    Storages/System/StorageSystemContributors.cpp
    Storages/System/StorageSystemContributors.generated.cpp
    Storages/System/StorageSystemCurrentRoles.cpp
    Storages/System/StorageSystemDDLWorkerQueue.cpp
    Storages/System/StorageSystemDataSkippingIndices.cpp
    Storages/System/StorageSystemDataTypeFamilies.cpp
    Storages/System/StorageSystemDatabases.cpp
    Storages/System/StorageSystemDetachedParts.cpp
    Storages/System/StorageSystemDictionaries.cpp
    Storages/System/StorageSystemDisks.cpp
    Storages/System/StorageSystemDistributionQueue.cpp
    Storages/System/StorageSystemEnabledRoles.cpp
    Storages/System/StorageSystemErrors.cpp
    Storages/System/StorageSystemEvents.cpp
    Storages/System/StorageSystemFilesystemCache.cpp
    Storages/System/StorageSystemFormats.cpp
    Storages/System/StorageSystemFunctions.cpp
    Storages/System/StorageSystemGrants.cpp
    Storages/System/StorageSystemGraphite.cpp
    Storages/System/StorageSystemLicenses.cpp
    Storages/System/StorageSystemLicenses.generated.cpp
    Storages/System/StorageSystemMacros.cpp
    Storages/System/StorageSystemMergeTreeMetadataCache.cpp
    Storages/System/StorageSystemMergeTreeSettings.cpp
    Storages/System/StorageSystemMerges.cpp
    Storages/System/StorageSystemMetrics.cpp
    Storages/System/StorageSystemModels.cpp
    Storages/System/StorageSystemMutations.cpp
    Storages/System/StorageSystemNumbers.cpp
    Storages/System/StorageSystemOne.cpp
    Storages/System/StorageSystemPartMovesBetweenShards.cpp
    Storages/System/StorageSystemParts.cpp
    Storages/System/StorageSystemPartsBase.cpp
    Storages/System/StorageSystemPartsColumns.cpp
    Storages/System/StorageSystemPrivileges.cpp
    Storages/System/StorageSystemProcesses.cpp
    Storages/System/StorageSystemProjectionParts.cpp
    Storages/System/StorageSystemProjectionPartsColumns.cpp
    Storages/System/StorageSystemQuotaLimits.cpp
    Storages/System/StorageSystemQuotaUsage.cpp
    Storages/System/StorageSystemQuotas.cpp
    Storages/System/StorageSystemQuotasUsage.cpp
    Storages/System/StorageSystemRemoteDataPaths.cpp
    Storages/System/StorageSystemReplicas.cpp
    Storages/System/StorageSystemReplicatedFetches.cpp
    Storages/System/StorageSystemReplicationQueue.cpp
    Storages/System/StorageSystemRoleGrants.cpp
    Storages/System/StorageSystemRoles.cpp
    Storages/System/StorageSystemRowPolicies.cpp
    Storages/System/StorageSystemSchemaInferenceCache.cpp
    Storages/System/StorageSystemSettings.cpp
    Storages/System/StorageSystemSettingsChanges.cpp
    Storages/System/StorageSystemSettingsProfileElements.cpp
    Storages/System/StorageSystemSettingsProfiles.cpp
    Storages/System/StorageSystemStackTrace.cpp
    Storages/System/StorageSystemStoragePolicies.cpp
    Storages/System/StorageSystemTableEngines.cpp
    Storages/System/StorageSystemTableFunctions.cpp
    Storages/System/StorageSystemTables.cpp
    Storages/System/StorageSystemTimeZones.cpp
    Storages/System/StorageSystemTimeZones.generated.cpp
    Storages/System/StorageSystemTransactions.cpp
    Storages/System/StorageSystemUserDirectories.cpp
    Storages/System/StorageSystemUsers.cpp
    Storages/System/StorageSystemWarnings.cpp
    Storages/System/StorageSystemZeros.cpp
    Storages/System/StorageSystemZooKeeper.cpp
    Storages/System/attachInformationSchemaTables.cpp
    Storages/System/attachSystemTables.cpp
    Storages/TTLDescription.cpp
    Storages/VirtualColumnUtils.cpp
    Storages/WindowView/StorageWindowView.cpp
    Storages/checkAndGetLiteralArgument.cpp
    Storages/extractKeyExpressionList.cpp
    Storages/getStructureOfRemoteTable.cpp
    Storages/getVirtualsForStorage.cpp
    Storages/registerStorages.cpp
    Storages/transformQueryForExternalDatabase.cpp
    TableFunctions/ITableFunction.cpp
    TableFunctions/ITableFunctionFileLike.cpp
    TableFunctions/ITableFunctionXDBC.cpp
    TableFunctions/TableFunctionDictionary.cpp
    TableFunctions/TableFunctionExecutable.cpp
    TableFunctions/TableFunctionFactory.cpp
    TableFunctions/TableFunctionFile.cpp
    TableFunctions/TableFunctionFormat.cpp
    TableFunctions/TableFunctionGenerateRandom.cpp
    TableFunctions/TableFunctionHDFS.cpp
    TableFunctions/TableFunctionHDFSCluster.cpp
    TableFunctions/TableFunctionInput.cpp
    TableFunctions/TableFunctionMeiliSearch.cpp
    TableFunctions/TableFunctionMerge.cpp
    TableFunctions/TableFunctionMongoDB.cpp
    TableFunctions/TableFunctionMySQL.cpp
    TableFunctions/TableFunctionNull.cpp
    TableFunctions/TableFunctionNumbers.cpp
    TableFunctions/TableFunctionPostgreSQL.cpp
    TableFunctions/TableFunctionRemote.cpp
    TableFunctions/TableFunctionS3.cpp
    TableFunctions/TableFunctionS3Cluster.cpp
    TableFunctions/TableFunctionSQLite.cpp
    TableFunctions/TableFunctionURL.cpp
    TableFunctions/TableFunctionValues.cpp
    TableFunctions/TableFunctionView.cpp
    TableFunctions/TableFunctionViewIfPermitted.cpp
    TableFunctions/TableFunctionZeros.cpp
    TableFunctions/registerTableFunctions.cpp
)

SRC_C_SSE2(Functions/divide/divideImpl.cpp -DNAMESPACE=SSE2)

SRC_C_AVX2(Functions/divide/divideImpl.cpp -DNAMESPACE=AVX2)

IF (OS_LINUX)
    SRCS(
        Storages/FileLog/DirectoryWatcherBase.cpp
        Storages/FileLog/FileLogDirectoryWatcher.cpp
        Storages/FileLog/FileLogSettings.cpp
        Storages/FileLog/FileLogSource.cpp
        Storages/FileLog/ReadBufferFromFileLog.cpp
        Storages/FileLog/StorageFileLog.cpp
    )
ENDIF()

END()
