# This file is autogenerated, don't edit it manually

__version__ = "1.23.4b1.dev73+spyt216.015f0802"
__scala_version__ = "1.23.4-spyt216-73-015f0802-SNAPSHOT"
__spark_version__ = "3.0.1+1.23.2b1.dev28"
