scenarios:
  nightly-dev:
      k8sTemplate: base-spec.yaml
      checks:
        - common
      ttl: 600
      operator:
        package: ytop-chart-nightly
        version: dev
        repo: ytsaurus-k8s-operator
      components:
        ytsaurus:
          package: ytsaurus-nightly
          version: dev
        strawberry:
          package: strawberry-nightly
          version: dev
        query_tracker:
          package: query-tracker-nightly
          version: dev
checks:
  common:
    type: ODIN
    description:
      helmUrl: oci://ghcr.io/ytsaurus/odin-chart
      releaseName: odin
      version: 0.0.4
