#!bash

_yt_create ()
{
    opts="--type --manifest"

    local object_types
    object_types="
    string_node
    int64_node
    double_node
    map_node
    list_node

    file
    table
    chunk_map
    lost_chunk_map
    overreplicated_chunk_map
    underreplicated_chunk_map
    chunk_list_map
    transaction_map
    node_map
    lock_map
    holder
    holder_map
    orchid
    "

    if [[ $prev == "--type" ]]; then
        COMPREPLY=( $( compgen -W "${object_types}" -- ${cur}))
        return
    fi
}


_yt_lock ()
{
    opts="--mode"    
    if [[ $prev == "--mode" ]]; then
        COMPREPLY=( $( compgen -W "exclusive shared snapshot" -- ${cur} ))
        return
    fi
}

_yt_start ()
{
    # start is non-transacted command
    tx=""    
}
    
_yt ()
{
    local commands
    commands="
    abort
    commit
    create
    download
    get
    list
    lock
    read
    remove
    set
    start
    upload
    write
    "

    cur=`_get_cword`
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    common="--help --config"
    opts=""
    tx=""

    if [ $COMP_CWORD -eq 1 ]; then
        COMPREPLY=( $( compgen -W "${commands}" -- ${cur}) )
    else
        tx="--tx"
        local cmd="${COMP_WORDS[1]}"
        case $cmd in 
        start)      _yt_start ;;
        create)     _yt_create ;;
        lock)       _yt_lock ;;
        esac
    fi

    if [[ ${cur} == -* ]]; then
        COMPREPLY=( $( compgen -W "${common} ${opts} ${tx}" -- ${cur}))
    fi
}

complete -o default -F _yt yt