cp -r ../../../../../contrib/python/pytest contrib/
cp -r ../../../../../contrib/python/pytest-timeout contrib/
cp -r ../../../../../contrib/python/apipkg contrib/
cp -r ../../../../../contrib/python/six contrib/
cp -r ../../../../../contrib/python/execnet contrib/
cp -r ../../../../../contrib/python/flaky contrib/
cp -r ../../../../../contrib/python/atomicwrites contrib/
cp -r ../../../../../contrib/python/py contrib/
cp -r ../../../../../contrib/python/attrs contrib/
cp -r ../../../../../contrib/python/pluggy contrib/
cp -r ../../../../../contrib/python/pathlib2 contrib/
cp -r ../../../../../contrib/python/funcsigs contrib/
cp -r ../../../../../contrib/python/scandir contrib/
cp -r ../../../../../contrib/python/contextlib2 contrib/
cp -r ../../../../../contrib/python/configparser contrib/
cp -r ../../../../../contrib/python/importlib-metadata/py2 contrib/importlib-metadata
cp -r ../../../../../contrib/python/more-itertools/py2 contrib/more-itertools
