RECURSE(
    access_log_viewer
    bulk_acl_checker
    bulk_acl_checker_roren
    id_to_path_mapping
    resource_usage
    resource_usage_roren
    ytmsvc_initializer
)

IF (NOT OPENSOURCE)
    RECURSE(
        abcdapter
        error_manager
        excel
        firehose
        gang_tools
        grant_permissions
        hermes
        id_to_path_mapping
        job_log_viewer
        klacalka
        lib
        ml
        perfetto
        resource-pumper
        solomon-resolver
        thor
    )
ENDIF()
