# Generated by devtools/yamaker from nixpkgs 22.11.

LIBRARY()

LICENSE(
    Public-Domain AND
    Unlicense
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(2023-12-03)

ORIGINAL_SOURCE(https://github.com/wangyi-fudan/wyhash/archive/408620b6d12b7d667b3dd6ae39b7929a39e8fa05.tar.gz)

END()
