LIBRARY()

SRCS(
    configured_tablet_bootstrapper.cpp
    configured_tablet_bootstrapper.h
    defs.h
    dynamic_nameserver.cpp
    dynamic_nameserver.h
    dynamic_nameserver_impl.h
    dynamic_nameserver_mon.cpp
    labels_maintainer.cpp
    labels_maintainer.h
    lease_holder.cpp
    lease_holder.h
    local.cpp
    local.h
    node_broker__graceful_shutdown.cpp
    node_broker.cpp
    node_broker.h
    node_broker_impl.h
    node_broker__extend_lease.cpp
    node_broker__init_scheme.cpp
    node_broker__load_state.cpp
    node_broker__migrate_state.cpp
    node_broker__register_node.cpp
    node_broker__scheme.h
    node_broker__update_config.cpp
    node_broker__update_config_subscription.cpp
    node_broker__update_epoch.cpp
    slot_indexes_pool.cpp
    slot_indexes_pool.h
    table_adapter.h
    tenant_node_enumeration.cpp
    tenant_node_enumeration.h
    tenant_pool.h
    tenant_pool.cpp
    tenant_slot_broker.cpp
    tenant_slot_broker.h
    tenant_slot_broker_impl.h
    tenant_slot_broker__alter_tenant.cpp
    tenant_slot_broker__assign_free_slots.cpp
    tenant_slot_broker__check_slot_status.cpp
    tenant_slot_broker__init_scheme.cpp
    tenant_slot_broker__load_state.cpp
    tenant_slot_broker__scheme.h
    tenant_slot_broker__update_config.cpp
    tenant_slot_broker__update_pool_status.cpp
    tenant_slot_broker__update_node_location.cpp
    tenant_slot_broker__update_slot_status.cpp
)

PEERDIR(
    contrib/ydb/library/actors/core
    contrib/ydb/core/actorlib_impl
    contrib/ydb/core/base
    contrib/ydb/core/blobstorage
    contrib/ydb/core/blobstorage/crypto
    contrib/ydb/core/blobstorage/dsproxy/mock
    contrib/ydb/core/blobstorage/groupinfo
    contrib/ydb/core/blobstorage/incrhuge
    contrib/ydb/core/blobstorage/pdisk
    contrib/ydb/core/engine/minikql
    contrib/ydb/core/kesus/tablet
    contrib/ydb/core/keyvalue
    contrib/ydb/core/mind/bscontroller
    contrib/ydb/core/node_whiteboard
    contrib/ydb/core/protos
    contrib/ydb/core/sys_view/processor
    contrib/ydb/core/tablet
    contrib/ydb/core/tablet_flat
    contrib/ydb/core/test_tablet
    contrib/ydb/core/tx/replication/controller
    contrib/ydb/core/tx/scheme_board
    contrib/ydb/core/tx/scheme_cache
    contrib/ydb/core/tx/schemeshard
)

END()

RECURSE(
    address_classification
    bscontroller
    hive
)

RECURSE_FOR_TESTS(
    ut
    ut_fat
)
