package NYT.NControllerAgent.NProto;

import "yt/ytlib/chunk_client/proto/session_id.proto";

import "yt_proto/yt/client/node_tracker_client/proto/node.proto";

import "yt_proto/yt/core/misc/proto/guid.proto";

////////////////////////////////////////////////////////////////////////////////

message TReqGetShuffleWriteSession
{
    required NYT.NProto.TGuid controller_agent_incarnation_id = 1;
    required NYT.NProto.TGuid operation_id = 2;
    required NYT.NProto.TGuid job_id = 3;

    required int32 partition_index = 4;

    // The session the caller failed to write to, if any.
    optional NYT.NChunkClient.NProto.TSessionId excluded_session_id = 5;
}

message TRspGetShuffleWriteSession
{
    required NYT.NChunkClient.NProto.TSessionId session_id = 1;
    required NNodeTrackerClient.NProto.TNodeDescriptor sequencer_node = 2;
}

////////////////////////////////////////////////////////////////////////////////
