// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.22.5
// source: yt/flow/library/cpp/common/proto/message.proto

package common

import (
	_ "go.ytsaurus.tech/yt/go/proto/core/misc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId          *string `protobuf:"bytes,1,req,name=message_id,json=messageId" json:"message_id,omitempty"`
	SystemTimestamp    *uint64 `protobuf:"varint,2,req,name=system_timestamp,json=systemTimestamp" json:"system_timestamp,omitempty"`
	AlignmentTimestamp *uint64 `protobuf:"varint,7,opt,name=alignment_timestamp,json=alignmentTimestamp" json:"alignment_timestamp,omitempty"` // Empty alignment_timestamp means that it is equal to system_timestamp.
	EventTimestamp     *uint64 `protobuf:"varint,6,opt,name=event_timestamp,json=eventTimestamp" json:"event_timestamp,omitempty"`
	Payload            []byte  `protobuf:"bytes,4,req,name=payload" json:"payload,omitempty"`
	StreamSpecId       *int64  `protobuf:"varint,5,req,name=stream_spec_id,json=streamSpecId" json:"stream_spec_id,omitempty"`
}

func (x *TMessage) Reset() {
	*x = TMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yt_flow_library_cpp_common_proto_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMessage) ProtoMessage() {}

func (x *TMessage) ProtoReflect() protoreflect.Message {
	mi := &file_yt_flow_library_cpp_common_proto_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMessage.ProtoReflect.Descriptor instead.
func (*TMessage) Descriptor() ([]byte, []int) {
	return file_yt_flow_library_cpp_common_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *TMessage) GetMessageId() string {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return ""
}

func (x *TMessage) GetSystemTimestamp() uint64 {
	if x != nil && x.SystemTimestamp != nil {
		return *x.SystemTimestamp
	}
	return 0
}

func (x *TMessage) GetAlignmentTimestamp() uint64 {
	if x != nil && x.AlignmentTimestamp != nil {
		return *x.AlignmentTimestamp
	}
	return 0
}

func (x *TMessage) GetEventTimestamp() uint64 {
	if x != nil && x.EventTimestamp != nil {
		return *x.EventTimestamp
	}
	return 0
}

func (x *TMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TMessage) GetStreamSpecId() int64 {
	if x != nil && x.StreamSpecId != nil {
		return *x.StreamSpecId
	}
	return 0
}

type TMessageBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*TMessage `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
}

func (x *TMessageBatch) Reset() {
	*x = TMessageBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yt_flow_library_cpp_common_proto_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TMessageBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMessageBatch) ProtoMessage() {}

func (x *TMessageBatch) ProtoReflect() protoreflect.Message {
	mi := &file_yt_flow_library_cpp_common_proto_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMessageBatch.ProtoReflect.Descriptor instead.
func (*TMessageBatch) Descriptor() ([]byte, []int) {
	return file_yt_flow_library_cpp_common_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *TMessageBatch) GetMessages() []*TMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_yt_flow_library_cpp_common_proto_message_proto protoreflect.FileDescriptor

var file_yt_flow_library_cpp_common_proto_message_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x79, 0x74, 0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x79, 0x2f, 0x63, 0x70, 0x70, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x4e, 0x59, 0x54, 0x2e, 0x4e, 0x46, 0x6c, 0x6f, 0x77, 0x2e, 0x4e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x26, 0x79, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x79, 0x74, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x69, 0x73, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf4, 0x01, 0x0a, 0x08, 0x54,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x02, 0x28, 0x04,
	0x52, 0x0f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x2f, 0x0a, 0x13, 0x61, 0x6c, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x12,
	0x61, 0x6c, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f,
	0x73, 0x70, 0x65, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x02, 0x28, 0x03, 0x52, 0x0c, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x49, 0x64, 0x4a, 0x04, 0x08, 0x03, 0x10,
	0x04, 0x22, 0x47, 0x0a, 0x0d, 0x54, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x36, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x4e, 0x59, 0x54, 0x2e, 0x4e, 0x46, 0x6c, 0x6f, 0x77,
	0x2e, 0x4e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x42, 0x2a, 0x5a, 0x28, 0x61, 0x2e,
	0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x72, 0x75, 0x2f, 0x79,
	0x74, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
}

var (
	file_yt_flow_library_cpp_common_proto_message_proto_rawDescOnce sync.Once
	file_yt_flow_library_cpp_common_proto_message_proto_rawDescData = file_yt_flow_library_cpp_common_proto_message_proto_rawDesc
)

func file_yt_flow_library_cpp_common_proto_message_proto_rawDescGZIP() []byte {
	file_yt_flow_library_cpp_common_proto_message_proto_rawDescOnce.Do(func() {
		file_yt_flow_library_cpp_common_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_yt_flow_library_cpp_common_proto_message_proto_rawDescData)
	})
	return file_yt_flow_library_cpp_common_proto_message_proto_rawDescData
}

var file_yt_flow_library_cpp_common_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_yt_flow_library_cpp_common_proto_message_proto_goTypes = []interface{}{
	(*TMessage)(nil),      // 0: NYT.NFlow.NProto.TMessage
	(*TMessageBatch)(nil), // 1: NYT.NFlow.NProto.TMessageBatch
}
var file_yt_flow_library_cpp_common_proto_message_proto_depIdxs = []int32{
	0, // 0: NYT.NFlow.NProto.TMessageBatch.messages:type_name -> NYT.NFlow.NProto.TMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_yt_flow_library_cpp_common_proto_message_proto_init() }
func file_yt_flow_library_cpp_common_proto_message_proto_init() {
	if File_yt_flow_library_cpp_common_proto_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yt_flow_library_cpp_common_proto_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yt_flow_library_cpp_common_proto_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TMessageBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yt_flow_library_cpp_common_proto_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yt_flow_library_cpp_common_proto_message_proto_goTypes,
		DependencyIndexes: file_yt_flow_library_cpp_common_proto_message_proto_depIdxs,
		MessageInfos:      file_yt_flow_library_cpp_common_proto_message_proto_msgTypes,
	}.Build()
	File_yt_flow_library_cpp_common_proto_message_proto = out.File
	file_yt_flow_library_cpp_common_proto_message_proto_rawDesc = nil
	file_yt_flow_library_cpp_common_proto_message_proto_goTypes = nil
	file_yt_flow_library_cpp_common_proto_message_proto_depIdxs = nil
}
