# Generated by devtools/yamaker from nixpkgs 22.11.

LIBRARY()

LICENSE(
    Apache-2.0 AND
    BSD-2-Clause AND
    BSD-3-Clause AND
    ISC AND
    MIT AND
    Public-Domain AND
    Zlib
)

LICENSE_TEXTS(.yandex_meta/licenses.list.txt)

VERSION(2.4.0)

ORIGINAL_SOURCE(https://github.com/confluentinc/librdkafka/archive/v2.4.0.tar.gz)

PEERDIR(
    contrib/libs/lz4
    contrib/libs/openssl
    contrib/libs/sasl
    contrib/libs/xxhash
    contrib/libs/zlib
    contrib/libs/zstd
)

ADDINCL(
    contrib/libs/lz4
    contrib/libs/sasl/include
    contrib/libs/xxhash
    contrib/libs/zstd/include
)

NO_COMPILER_WARNINGS()

NO_RUNTIME()

SRCS(
    src/cJSON.c
    src/crc32c.c
    src/rdaddr.c
    src/rdavl.c
    src/rdbase64.c
    src/rdbuf.c
    src/rdcrc32.c
    src/rddl.c
    src/rdfnv1a.c
    src/rdgz.c
    src/rdhdrhistogram.c
    src/rdkafka.c
    src/rdkafka_admin.c
    src/rdkafka_assignment.c
    src/rdkafka_assignor.c
    src/rdkafka_aux.c
    src/rdkafka_background.c
    src/rdkafka_broker.c
    src/rdkafka_buf.c
    src/rdkafka_cert.c
    src/rdkafka_cgrp.c
    src/rdkafka_conf.c
    src/rdkafka_coord.c
    src/rdkafka_error.c
    src/rdkafka_event.c
    src/rdkafka_feature.c
    src/rdkafka_fetcher.c
    src/rdkafka_header.c
    src/rdkafka_idempotence.c
    src/rdkafka_interceptor.c
    src/rdkafka_lz4.c
    src/rdkafka_metadata.c
    src/rdkafka_metadata_cache.c
    src/rdkafka_mock.c
    src/rdkafka_mock_cgrp.c
    src/rdkafka_mock_handlers.c
    src/rdkafka_msg.c
    src/rdkafka_msgset_reader.c
    src/rdkafka_msgset_writer.c
    src/rdkafka_offset.c
    src/rdkafka_op.c
    src/rdkafka_partition.c
    src/rdkafka_pattern.c
    src/rdkafka_plugin.c
    src/rdkafka_queue.c
    src/rdkafka_range_assignor.c
    src/rdkafka_request.c
    src/rdkafka_roundrobin_assignor.c
    src/rdkafka_sasl.c
    src/rdkafka_sasl_cyrus.c
    src/rdkafka_sasl_oauthbearer.c
    src/rdkafka_sasl_plain.c
    src/rdkafka_sasl_scram.c
    src/rdkafka_ssl.c
    src/rdkafka_sticky_assignor.c
    src/rdkafka_subscription.c
    src/rdkafka_timer.c
    src/rdkafka_topic.c
    src/rdkafka_transport.c
    src/rdkafka_txnmgr.c
    src/rdkafka_zstd.c
    src/rdlist.c
    src/rdlog.c
    src/rdmap.c
    src/rdmurmur2.c
    src/rdports.c
    src/rdrand.c
    src/rdregex.c
    src/rdstring.c
    src/rdunittest.c
    src/rdvarint.c
    src/snappy.c
    src/tinycthread.c
    src/tinycthread_extra.c
)

END()

RECURSE(
    src-cpp
)
