#pragma once

// .h autogenerated by cmake!

#define USE_AVRO 1
#define USE_CAPNP 0
#define USE_SNAPPY 1
#define USE_PARQUET 0
#define USE_ORC 0
#define USE_ARROW 0
#define USE_PROTOBUF 0
#define USE_MSGPACK 1
