# THIS FILE IS AUTOGENERATED, DO NOT EDIT !!!
# Generator: ya tool yamaker ym2; contrib/go/_std_{VER}/.yandex_meta/build.ym; contrib/go/yagogen/gen.py
# Docs: https://a.yandex-team.ru/arcadia/devtools/contrib/docs/toolchain_go.md


GO_LIBRARY()
IF (TRUE)
    SRCS(
        doc.go
        event.go
        reader.go
        textreader.go
        textwriter.go
        writer.go
    )
ENDIF()
END()
