apiVersion: v1
kind: Pod
metadata:
  name: new_stress_test
spec:
  restartPolicy: OnFailure
  containers:
  - name: ytentry
    image: {{ .Values.SystestImagePath }}
    env:
    - name: YT_CONFIG_PATCHES
      value: '{proxy={enable_proxy_discovery=%false}}'
    - name: YT_TOKEN
      value: 'password'
    - name: YT_PROXY
      value: "$(HTTP_PROXIES_LB_SERVICE_HOST):$(HTTP_PROXIES_LB_SERVICE_PORT)"
    command: ['python3.7', '/usr/new_stress_test/__main__.py', '--ipv4', '--preset', 'full', '--path', '//home']
