package chyt

import (
	"context"
	"fmt"
	"io"
	"path/filepath"
	"strings"
	"unicode"
	"unicode/utf8"

	"go.ytsaurus.tech/library/go/core/log"
	"go.ytsaurus.tech/yt/chyt/controller/internal/strawberry"
	"go.ytsaurus.tech/yt/go/ypath"
	"go.ytsaurus.tech/yt/go/yson"
)

const (
	DefaultEnableODBC     = false
	DefaultODBCBridgePath = ypath.Path("//sys/bin/odbc-drivers/clickhouse-odbc-bridge")
	DefaultODBCDriversDir = ypath.Path("//sys/bin/odbc-drivers")
)

// ODBCDriver describes an ODBC driver for odbcinst.ini.
// Path is the Cypress path to the shared library (.so) that implements the driver.
// Options is a map of additional key-value pairs for the odbcinst.ini driver section.
type ODBCDriver struct {
	Name        string            `yson:"name"`
	Description string            `yson:"description"`
	Path        ypath.Path        `yson:"path"`
	Options     map[string]string `yson:"options"`
}

// ODBCSource describes an ODBC data source for odbc.ini.
// Driver is the logical driver name from odbcinst.ini.
// Options is a map of additional key-value pairs for the data source section
// (e.g. "Database", "Server", "Port", etc.).
type ODBCSource struct {
	Name        string            `yson:"name"`
	Description string            `yson:"description"`
	Driver      string            `yson:"driver"`
	Options     map[string]string `yson:"options"`
}

// ODBCConfig groups all ODBC-related configuration.
type ODBCConfig struct {
	Enable *bool `yson:"enable"`
	// DriversDir is the Cypress path to the directory containing pre-deployed ODBC drivers.
	// The controller reads config.yson from this directory during Prepare() via loadODBCDriversConfig
	// and merges the discovered drivers and extra files into the speclet's Drivers/ExtraFiles lists.
	// This allows a cluster admin to pre-deploy a set of drivers once and have all cliques pick them up
	// automatically without each user having to list them explicitly.
	DriversDir *ypath.Path `yson:"drivers_dir"`
	// Drivers is a list of additional ODBC drivers specified manually.
	Drivers []ODBCDriver `yson:"drivers"`
	// Sources is a list of ODBC data sources. Each source references a driver by name
	// and provides connection-specific options. Used to generate odbc.ini.
	Sources []ODBCSource `yson:"sources"`
	// ExtraFiles is a list of Cypress paths to additional files needed by ODBC drivers
	// (e.g. driver dependencies, database files, certificates, etc.). These files are loaded as operation artifacts.
	ExtraFiles []ypath.Path `yson:"extra_files"`
	// BridgePath is the Cypress path to the clickhouse-odbc-bridge binary.
	BridgePath *ypath.Path `yson:"bridge_path"`
}

func (c *ODBCConfig) EnableOrDefault() bool {
	if c == nil || c.Enable == nil {
		return DefaultEnableODBC
	}
	return *c.Enable
}

func (c *ODBCConfig) DriversDirOrDefault() ypath.Path {
	if c == nil || c.DriversDir == nil {
		return DefaultODBCDriversDir
	}
	return *c.DriversDir
}

func (c *ODBCConfig) BridgePathOrDefault() ypath.Path {
	if c == nil || c.BridgePath == nil {
		return DefaultODBCBridgePath
	}
	return *c.BridgePath
}

func generateODBCInstIni(drivers []ODBCDriver) string {
	var sb strings.Builder
	for _, driver := range drivers {
		driverFile := filepath.Base(driver.Path.String())
		fmt.Fprintf(&sb, "[%s]\n", driver.Name)
		fmt.Fprintf(&sb, "Description=%s\n", driver.Description)
		fmt.Fprintf(&sb, "Driver=$PWD/%s\n", driverFile)
		fmt.Fprintf(&sb, "Setup=$PWD/%s\n", driverFile)
		for k, v := range driver.Options {
			fmt.Fprintf(&sb, "%s=%s\n", capitalizeFirst(k), v)
		}
		sb.WriteString("\n")
	}
	return sb.String()
}

func generateODBCIni(sources []ODBCSource) string {
	var sb strings.Builder
	for _, source := range sources {
		fmt.Fprintf(&sb, "[%s]\n", source.Name)
		fmt.Fprintf(&sb, "Description=%s\n", source.Description)
		fmt.Fprintf(&sb, "Driver=%s\n", source.Driver)
		for k, v := range source.Options {
			fmt.Fprintf(&sb, "%s=%s\n", capitalizeFirst(k), v)
		}
		sb.WriteString("\n")
	}
	return sb.String()
}

// loadODBCDriversConfig reads config.yson from driversDir and returns the parsed ODBCConfig.
// The file is generated by deploy_odbc_driver.py --generate-config.
func (c *Controller) loadODBCDriversConfig(ctx context.Context, driversDir ypath.Path) (cfg *ODBCConfig, err error) {
	configPath := driversDir.Child("config.yson")
	r, readErr := c.ytc.ReadFile(ctx, configPath, nil)
	if readErr != nil {
		return nil, fmt.Errorf("chyt: failed to read ODBC drivers config %s: %w", configPath, readErr)
	}
	raw, err := io.ReadAll(r)
	if closeErr := r.Close(); closeErr != nil && err == nil {
		err = closeErr
	}
	if err != nil {
		return nil, fmt.Errorf("chyt: failed to read ODBC drivers config content %s: %w", configPath, err)
	}
	func() {
		defer func() {
			if r := recover(); r != nil {
				err = fmt.Errorf("chyt: panic while parsing ODBC drivers config %s: %v", configPath, r)
			}
		}()
		var parsed ODBCConfig
		if unmarshalErr := yson.Unmarshal(raw, &parsed); unmarshalErr != nil {
			err = fmt.Errorf("chyt: failed to parse ODBC drivers config %s: %w", configPath, unmarshalErr)
			return
		}
		cfg = &parsed
	}()
	if err != nil {
		return nil, err
	}
	c.l.Info("ODBC drivers config loaded",
		log.String("path", configPath.String()),
		log.Int("driver_count", len(cfg.Drivers)),
		log.Int("extra_file_count", len(cfg.ExtraFiles)))
	return cfg, nil
}

func (c *Controller) appendODBCConfigs(ctx context.Context, oplet *strawberry.Oplet, speclet *Speclet, filePaths *[]ypath.Rich) error {
	odbcInstIniPath, err := c.uploadFile(ctx, oplet.Alias(), "odbcinst.ini", []byte(generateODBCInstIni(speclet.ODBCConfig.Drivers)))
	if err != nil {
		return fmt.Errorf("chyt: failed to upload odbcinst.ini: %w", err)
	}
	*filePaths = append(*filePaths, odbcInstIniPath)

	odbcIniPath, err := c.uploadFile(ctx, oplet.Alias(), "odbc.ini", []byte(generateODBCIni(speclet.ODBCConfig.Sources)))
	if err != nil {
		return fmt.Errorf("chyt: failed to upload odbc.ini: %w", err)
	}
	*filePaths = append(*filePaths, odbcIniPath)

	return nil
}

func capitalizeFirst(s string) string {
	if s == "" {
		return s
	}
	r, size := utf8.DecodeRuneInString(s)
	return string(unicode.ToUpper(r)) + s[size:]
}
