if(NOT DEFINED CPU_VENDOR)
  set(_vendo)
  set(_family)
  set(_model)
  set(_flags)

  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    file(READ "/proc/cpuinfo" _cpuinfo)
    string(REGEX REPLACE ".*vendor_id[ \t]*:[ \t]+([a-zA-Z0-9_-]+).*" "\\1" _vendor "${_cpuinfo}")
    string(REGEX REPLACE ".*cpu family[ \t]*:[ \t]+([a-zA-Z0-9_-]+).*" "\\1" _family "${_cpuinfo}")
    string(REGEX REPLACE ".*model[ \t]*:[ \t]+([a-zA-Z0-9_-]+).*" "\\1" _model "${_cpuinfo}")
    string(REGEX REPLACE ".*flags[ \t]*:[ \t]+([a-zA-Z0-9_-]+).*" "\\1" _flags "${_cpuinfo}")
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    get_filename_component(_vendor_id "[HKEY_LOCAL_MACHINE\\Hardware\\Description\\System\\CentralProcessor\\0;VendorIdentifier]" NAME CACHE)
    get_filename_component(_cpuinfo "[HKEY_LOCAL_MACHINE\\Hardware\\Description\\System\\CentralProcessor\\0;Identifier]" NAME CACHE)
    mark_as_advanced(_vendor _cpuinfo)
    string(REGEX REPLACE ".* Family ([0-9]+) .*" "\\1" _family "${_cpuinfo}")
    string(REGEX REPLACE ".* Model ([0-9]+) .*" "\\1" _model "${_cpuinfo}")
  endif()

  message(STATUS "CPU Vendor: ${_vendor}")
  set(CPU_VENDOR "${_vendor}" CACHE STRING "")
  mark_as_advanced(CPU_VENDOR)
endif()
