INCLUDE(ya.make.inc)

IF (OPENSOURCE OR PYTHON_CONFIG MATCHES "python3" OR USE_SYSTEM_PYTHON MATCHES "3.")
  EXPORTS_SCRIPT(driver3.exports)
  PYTHON3_MODULE()
ELSE()
  EXPORTS_SCRIPT(driver.exports)
  PYTHON2_MODULE()
ENDIF()

END()
