main:
  source: dev
  show_in_matrix: false
  constraints:
    operator: main
    query_tracker: main
    chyt: main
    strawberry: main
24.2:
  source: release
  constraints:
    chyt: "2.16.0"
    operator: ">=0.23.1 && <= 0.26.0"
    query_tracker: "0.0.8"
    strawberry: "0.0.12"
    spyt: ">=2.6.5"
25.1:
  source: release
  constraints:
    query_tracker: ">=0.0.8"
    operator: ">=0.25.0 && <=0.27.0"
    chyt: ">=2.16.0"
    strawberry: "0.0.13"
    spyt: ">=2.6.5"
25.2:
  source: release
  constraints:
    operator: ">=0.25.0"
    strawberry: ">=0.0.15"
    chyt: ">=2.17.3"
    spyt: ">=2.6.5"
    query_tracker: ">=0.0.11"
25.3:
  source: release
  constraints:
    operator: ">=0.25.0"
    strawberry: ">=0.0.15"
    chyt: ">=2.17.3"
    spyt: ">=2.6.5"
    query_tracker: ">=0.0.11"
25.4:
  source: release
  constraints:
    operator: ">=0.25.0 && main"
    strawberry: ">=0.0.15"
    chyt: ">=2.17.3"
    spyt: ">=2.6.5"
    query_tracker: ">=0.0.11"
