main:
  source: dev
  show_in_matrix: false
0.23.1:
  source: stable
0.24.0:
  source: stable
0.25.0:
  source: stable
0.26.0:
  source: stable
0.27.0:
  source: stable
0.28.0:
  source: stable
0.29.0:
  source: stable
0.30.0:
  source: stable
0.31.0:
  source: stable
