name: Check jobs
on:
  workflow_call:
    inputs:
      runs-on-value:
        required: true
        type: string

jobs:
  check:
    runs-on: ${{ inputs.runs-on-value }}
    steps:
      - name: Unittests (cmake)
        shell: bash
        run: |
          ./ytsaurus/yt/yt/scripts/run_tests.sh unittests --build-path ../build_cmake_release

      - name: Unittests (ya-make)
        shell: bash
        run: |
          ./ytsaurus/yt/yt/scripts/run_tests.sh unittests --build-path ../build_ya-make_release

      - name: Setup build symlink
        shell: bash
        run: |
          rm -rf "$(pwd)/../build"
          ln -sfn "$(pwd)/../build_ya-make_release" "$(pwd)/../build"

      - name: Integration tests
        shell: bash
        run: |
          ./ytsaurus/yt/yt/scripts/run_tests.sh integration

      - name: Python tests
        shell: bash
        run: |
          ./ytsaurus/yt/yt/scripts/run_tests.sh python

      - name: Odin tests
        shell: bash
        run: |
          ytsaurus/yt/odin/tests/run_tests.sh
