name: Release cron

on:
  push:
    tags:
      - 'docker/cron/0\.[0-0]+\.[0-9]+'

jobs:
  release:
    name: Run release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.11.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Guthub Packages Login
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse Tag
        id: tag
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/docker/cron/})" >> $GITHUB_OUTPUT

      - name: Package And Push Helm Chart
        run: |
          sed -i 's/tag: .*/tag: "${{ steps.tag.outputs.RELEASE_VERSION }}"/' yt/docker/charts/ytsaurus-cron/values.yaml
          helm package yt/docker/charts/ytsaurus-cron --version ${{ steps.tag.outputs.RELEASE_VERSION }}
          helm push cron-chart-${{ steps.tag.outputs.RELEASE_VERSION }}.tgz oci://ghcr.io/ytsaurus

      - name: Build And Push Docker Image
        run: |
          cd yt/docker/ytsaurus-cron
          make docker-build IMAGE_TAG=${{ steps.tag.outputs.RELEASE_VERSION }}
          make docker-push IMAGE_TAG=${{ steps.tag.outputs.RELEASE_VERSION }}

