name: Issue notifications

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  telegram:
    name: Telegram
    uses: ./.github/workflows/send_telegram_notification.yaml
    with:
      notification_type: issue
      runner: ubuntu-latest
    secrets:
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_NOTIFICATIONS_CHAT_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
