name: Release strawberry controller

on:
  push:
    tags:
      - 'yt/chyt/controller/v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  tag:
    name: Parse tag
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.IMAGE_TAG }}
    steps:
      - name: Parse tag
        id: tag
        run: |
          echo "IMAGE_TAG=$(echo ${GITHUB_REF#refs/*/yt/chyt/controller/v})" >> $GITHUB_OUTPUT

  release:
    needs: tag
    uses: ./.github/workflows/strawberry-action.yaml
    with:
      runs-on-value: ubuntu-latest
      push-release-tag: ${{ needs.tag.outputs.image-tag }}
      push-nightly-tag: ${{ needs.tag.outputs.image-tag }}
    secrets:
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}

  send-notifications:
    name: Send notifications
    needs: release
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            Workflow *${{github.workflow}}* failed: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}.
            Git ${{github.ref_type}}: *${{github.ref_name}}*.
            Commit:
            ```
            ${{github.event.head_commit.message}}
            ```
