name: Systest

on:
  schedule:
    - cron: '0 0 1 1 *'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  start-vm:
    name: Start VM
    runs-on: trampoline
    if: github.repository == 'ytsaurus/ytsaurus'
    outputs:
      label: ${{ steps.start-yc-runner.outputs.label }}
      instance-id: ${{ steps.start-yc-runner.outputs.instance-id }}
    steps:
      - name: Start YC runner
        id: start-yc-runner
        uses: yc-actions/yc-github-runner@v1
        with:
          mode: start
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          folder-id: ${{ vars.YC_FOLDER_ID }}
          image-id: ${{ vars.YC_DEFAULT_IMAGE_ID }}
          zone-id: ${{ vars.YC_ZONE_ID }}
          subnet-id: ${{ vars.YC_SUBNET_ID }}
          cores: 16
          memory: 32GB
          core-fraction: 100
          disk-type: network-ssd-nonreplicated
          disk-size: 93GB
          user: ${{ secrets.YC_VM_USERNAME }}
          ssh-public-key: ${{ secrets.YC_VM_SSH_PUBLIC_KEY }}
          public-ip: false
          ttl: PT24H
          runner-home-dir: /actions-runner

  checkout:
    name: Checkout sources
    needs: start-vm
    runs-on: ${{ needs.start-vm.outputs.label }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  check:
    name: Run checks
    needs:
      - start-vm
      - checkout

    runs-on: ${{ needs.start-vm.outputs.label }}
    timeout-minutes: 720

    steps:
      - name: Kube cluster get credentials
        shell: bash
        run: |
          echo '${{ secrets.YC_SA_JSON_CREDENTIALS }}' > sa.json
          /usr/local/bin/yc config set service-account-key sa.json
          /usr/local/bin/yc managed-kubernetes cluster get-credentials --id catam8govqco1ladv4gv --internal --force
          bash yt/systest/scripts/namespace.sh --invocation_id ${INVOCATION_ID} > /root/ns

      - name: Start YT and run systest
        shell: bash
        run: |
          export HOME=/root
          bash yt/systest/scripts/systest.sh --systest-image ghcr.io/ytsaurus/ytsaurus-systest:latest --image ghcr.io/ytsaurus/ytsaurus-nightly:$(python3.11 yt/systest/scripts/docker_version.py -r ghcr.io/ytsaurus/ytsaurus-nightly -f relwithdebinfo) --spyt-image ghcr.io/ytsaurus/spyt:$(python3.11 yt/systest/scripts/docker_version.py -r ghcr.io/ytsaurus/spyt) --namespace $(cat /root/ns) --ytsaurus-source-path $(pwd)

  shutdown-cluster:
    name: Shutdown YT
    needs:
      - start-vm
      - check

    runs-on: ${{ needs.start-vm.outputs.label }}
    if: ${{ success() }}
    steps:
      - name: Shutdown YT
        shell: bash
        run: |
          export HOME=/root
          bash yt/systest/scripts/shutdown_cluster.sh --ytsaurus-source-path $(pwd) --namespace $(cat /root/ns)

  stop-vm:
    name: Stop VM
    needs:
      - start-vm
      - check
      - shutdown-cluster
    runs-on: trampoline
    if: ${{ always() && github.repository == 'ytsaurus/ytsaurus' }}
    steps:
      - name: Stop YC runner
        uses: yc-actions/yc-github-runner@v1
        with:
          mode: stop
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-vm.outputs.label }}
          instance-id: ${{ needs.start-vm.outputs.instance-id }}

