name: Dummy CI

on:
  push:
    branches:
      - members/epsilond1/YT-25366-test-workflow

jobs:
  check:
    name: First step
    runs-on: ubuntu-latest
    steps:
      - name: Run cmd
        shell: bash
        run: |
          exit 127

  send-alert:
    needs:
      - check
    if: always()
    uses: ./.github/workflows/check-status-and-send-alert.yaml
    with:
      is_failure: ${{ contains(join(needs.*.result, ','), 'failure') }}
    secrets:
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

