name: Generate Documentation Release Notes

on:
  release:
    types: [created, updated]

permissions:
  pull-requests: write
  contents: write

jobs:
  generate-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate release notes
        run: |
          ./ya make -r yt/yt/scripts/generate_documentation_release_notes
          ./yt/yt/scripts/generate_documentation_release_notes/generate_documentation_release_notes -o "yt/docs/en/_includes/releases" -o "yt/docs/ru/_includes/releases"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.YTSAURUS_ACTIONS_APP_ID }}
          private-key: ${{ secrets.YTSAURUS_ACTIONS_CLIENT_ID }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update Documentation Release Notes
          branch: ci/update-documentation-release-notes/${{ github.event.release.tag_name }}
          base: main
          title: "Update Release Notes"
          body: |
            Update release notes in the documentation.
